### ISSUE TITLE
疑似 Extra Utilities 2 与翻译冲突

### ISSUE THREAD

**Issue by iMusynx** [CFPAOrg/Minecraft-Mod-Language-Package#1008]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；
运行在[EnigTech2](https://github.com/ET-Team/EnigTech2)整合包，资源包更新后Crash，关闭 updatemod 和资源包后正常。
[Crash Report](https://gist.github.com/iMusynx/0df88b88217a21edb71643effd7caddf)

**Comment by friendlyhj** [comment]
exu2 书的 json 文件汉化包内错误使用了 UTF8 with BOM 编码。

**Comment by exzhawk** [comment]
should be fixed in b0986c78e9a3cfad6f0d44ddbb9d4344efaaf4c6
