### ISSUE TITLE
1.12 文件位置错误, 文件名重复

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#1010]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；
![image](https://user-images.githubusercontent.com/7038938/110232114-c2613e80-7f56-11eb-85fb-4ce6c9e78b3f.png)

**Comment by dovisutu** [comment]
我去看看（把自己给assign上

**Comment by dovisutu** [comment]
补充一处错误文件位置：
assets/patchouli_books/liber_elementium/zh_cn/
（怎么图片上传不了了...hosts没调对吗
（正在写一个调查结果...

**Comment by dovisutu** [comment]
大概查出来这里炸掉的原因了
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/6c0d6549b462e2d4b2cbfed896df06dc2fe36739/src/Packer/Program.cs#L62
此处使用了`SearchOptions.AllDirectories`，用以一次性遍历手册等有次级文件结构的文本，但是...
这样的搜索并不能保证搜到的文件必定在一个次级文件夹中。

目前的文件结构是：`projects/<version>/assets/<mod-name>/<asset-domain>/<lang//others>/<path-to-the-file>`
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/6c0d6549b462e2d4b2cbfed896df06dc2fe36739/src/Packer/Program.cs#L27-L37
程序目前做的是进入`/<mod-name>/`后就立刻进行搜索，原因在于曾经出过一个mod使用了多个asset-domain的情况（例：[Chisel(]https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main/projects/1.12.2/assets/chisel)使用了`chisel`和`chisel_guide`），无法直接进入一个次级文件夹
但是问题是...可能有多个asset-domain也就算了，有的地方`/<asset-domain>/`一层压根就没有！~az~
这样的地方有好几处：
- [ ] https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main/projects/1.12.2/assets/emergingtechnology/lang
- [ ] https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main/projects/1.12.2/assets/metallurgy/lang
- [ ] https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main/projects/1.12.2/assets/deliciousdelights/lang
- [ ] https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main/projects/1.12.2/assets/elementaristics/lang
- [ ] https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main/projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium

有趣的是，在目前的压缩包里`deliciousdelights`的`zh_cn.lang`和`elementaristics`的`zh_cn.lang`合并到了一起，但是剩下两个却没有
至于重复文件...zip格式就是这个样子，不知道为什么允许重名文件的出现

要修复的话估计得等下周了

**Comment by TUsama** [comment]
我的元素秘学咋了？？

**Comment by TUsama** [comment]
> > ~我的元素秘学咋了？？~
> 
> 似乎是位置不对...~改了没（~
> 目前需要再加一层标识mod名的文件夹（如果asset-domain已经很明确了可以直接用那个），除非有特殊情况

改了（
