### ISSUE TITLE
levelup2职业选择界面无翻译

### ISSUE THREAD

**Issue by YogurtZebra** [CFPAOrg/Minecraft-Mod-Language-Package#1054]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

查看材质包内assets文件夹中的翻译时发现对应翻译文件内有翻译文本，但是最终职业选择界面显示的为全英文
![image](https://user-images.githubusercontent.com/57581480/111875361-5100a180-89d4-11eb-979d-6da601155863.png)
其他部分显示正常

**Comment by TUsama** [comment]
昨天测试了一下，这部分的内容似乎完全不依赖于语言文件，把 en_us.lang 通篇替换为 zh_cn.lang 中的内容后，发现里面的内容没有丝毫的变化。这说明这部分的内容很有可能不是汉化资源包能够加载到的。

**Comment by YogurtZebra** [comment]
观察发现有的up主视频内的职业选择界面有汉化，不知道是什么原因

**Comment by TUsama** [comment]
能给个链接吗，我去瞄一瞄。

**Comment by YogurtZebra** [comment]
> 能给个链接吗，我去瞄一瞄。

忘记了（x

**Comment by TUsama** [comment]
实在是查不出问题在哪。。。不好意思了。

**Comment by YogurtZebra** [comment]
没关系，大多数人应该也能猜到是什么意思
