### ISSUE TITLE
In The Sea 整合包汉化进度表

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#106]
- [x] aromabackup
- [x] aromabackuprecovery
- [x] bloodmoon
- [x] bq_standard
- [x] craftingtweaks
- [x] glass_shards
- [x] hardcoremapreset
- [x] magneticraft
- [x] questbook
- [x] tails
- [x] tinkersaddons （好像还有点问题）
- [x] totemic

**Comment by IrohaIsshiki** [comment]
tinkersaddons有啥问题？乱码？
