### ISSUE TITLE
文件格式错误

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#1086]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/ebbc8fd3c6a48d713a1d475e80d5d6b8e9025d80/projects/1.16.1/assets/scaffolding-behavior/ladderpower/lang/en_us.json

**Comment by exzhawk** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/b14424924e87ee4fd0ba2aff08ac2c9581f82c13
没修完后遗症?

**Comment by baka-gourd** [comment]
done
