### ISSUE TITLE
部分使用 #PARSE_ESCAPE 的.lang文本不能被 weblate 正常识别

### ISSUE THREAD

**Issue by dovisutu** [CFPAOrg/Minecraft-Mod-Language-Package#1113]
例：
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/310ababd8d05868d24e41b4da0120eb2a180a4b9/projects/1.12.2/assets/xnet/xnet/lang/en_us.lang#L49-L73

此处，使用了`#PARSE_ESCAPE`的xnet更进一步，使用了转义符转义掉了文件中的换行符，实现了多行`value`
然而，weblate似乎无法识别这一现象，结果是，`value`被识别成了下列：
`message.xnet.wireless_router=message.xnet.controller=message.xnet.antenna=message.xnet.antenna_base=message.xnet.antenna_dish=`

**Comment by TUsama** [comment]
@exzhawk

**Comment by exzhawk** [comment]
已修复
![image](https://user-images.githubusercontent.com/7038938/119234618-7c814300-bb61-11eb-97cc-a7c5f1fcb266.png)
