### ISSUE TITLE
请求移除 Extended Enchantment Numerals 的在库文本

### ISSUE THREAD

**Issue by dovisutu** [CFPAOrg/Minecraft-Mod-Language-Package#1150]
Curseforge 地址：https://www.curseforge.com/minecraft/mc-mods/extended-enchantment-numerals
Curseforge project id：323364

该模组仅仅对 minecraft 中附魔等级的文本进行了添加，然而却添加了将近 65536 条文本（由于已有文本实际值可能会偏小）；但这些文本仅为罗马数字，即使翻译也仅为照搬原文，不如移除。
值得注意的是，下载下来的文件中包含有`enchantmentlevels`与后缀有`1-3`的三个asset-domain，但目前库中似乎多出一个不在.jar中的（同时也有实际文本的）`level`domain，或许是其余模组的文件，或许需要进行分离

**Comment by baka-gourd** [comment]
哪个版本的

**Comment by baka-gourd** [comment]
我觉得这个level估计是之前的domain，现在改了

**Comment by baka-gourd** [comment]
已完成
