### ISSUE TITLE
[1.16]测试机器人是否可用

### ISSUE THREAD

**Issue by botax-issue** [CFPAOrg/Minecraft-Mod-Language-Package#1162]
## 反馈模组

星辉魔法

## 问题描述

我也不知道有啥问题

## 游戏版本

1.16

## 屏幕截图

![pic](https://i.loli.net/2021/05/22/XPJynAkL1Ww48aM.jpg)

***

Sender Platform: QQ

Sender ID: 13294853175531294853175513

**Comment by botax-issue** [comment]
114514
***
`Sender Platform: QQ`
`Sender ID: 13140511640431140511640413`

**Comment by dovisutu** [comment]
这玩意还有没有用了...没用关了

**Comment by TUsama** [comment]
？
