### ISSUE TITLE
何时支持 1.17.x？

### ISSUE THREAD

**Issue by MAX-XiaoKui** [CFPAOrg/Minecraft-Mod-Language-Package#1197]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；
什么时候开始1.17呢？

**Comment by baka-gourd** [comment]
考虑到 1.17 仅为一个仅包含“洞穴与山崖”更新前半部分内容的过渡版本，本模组汉化资源包将不会大量提供 1.17 模组的汉化内容，下一个着重维护版本（可能）将会是 1.18，也即“洞穴与山崖”第二（下半）部分。

**Comment by baka-gourd** [comment]
如果你想使用的话，可以先试试将1.16.5版本的资源包加载到1.17

**Comment by MAX-XiaoKui** [comment]
好的谢谢
