### ISSUE TITLE
tweakeroo

### ISSUE THREAD

**Issue by shane04111** [CFPAOrg/Minecraft-Mod-Language-Package#1198]
請問能支援tweakeroo的中文化嗎??

**Comment by baka-gourd** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.16/assets/tweakeroo/tweakeroo/lang/zh_cn.json
可以，已經在資料庫内了，是簡體的

**Comment by baka-gourd** [comment]
> 請問能支援tweakeroo的中文化嗎??

https://github.com/RPMTW/ResourcePack-Mod-zh_tw
