### ISSUE TITLE
余烬复刻版 Embers Rekindled 模组翻译质量较低

### ISSUE THREAD

**Issue by ZerowindSE** [CFPAOrg/Minecraft-Mod-Language-Package#1199]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

**Minecraft：1.12.2**
**Mod：余烬复刻版 Embers Rekindled | Version(1.14-hotfix)**

汉化翻译中有不少望文生意之处，比如embers:bin被译为垃圾桶（应为储物仓Bin），embers:breaker被译为工具销毁器（应为自动方块破坏器Automatic Breaker）等，且这些翻译与Mod自带指导书中翻译内容差别巨大。

[![RzbJnH.png](https://z3.ax1x.com/2021/07/10/RzbJnH.png)](https://imgtu.com/i/RzbJnH)

鉴于余烬复刻版的较新版本已经自带了完善的汉化翻译，建议从Mod翻译列表中移除此Mod。

**Comment by ChromaPIE** [comment]
不予受理，汉化包内翻译无误，该问题为与其它模组翻译键（Translation Key）相同导致。

余烬复刻版本身存在严重的翻译键命名问题，过于简单，独特性弱，导致其它模组中拥有相同翻译键的条目覆盖了其原本正常的翻译。

反馈问题请截下汉化资源包内语言文件的文本截图，请勿截取游戏内截图。
