### ISSUE TITLE
添加钠（Sodium）的翻译

### ISSUE THREAD

**Issue by MAX-XiaoKui** [CFPAOrg/Minecraft-Mod-Language-Package#1201]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

**添加[sodium](https://github.com/CaffeineMC/sodium-fabric)(1.16.5)的翻译**

**Comment by Lyaiya** [comment]
目前 Sodium 为硬编码，没法通过语言文件进行翻译。

**Comment by MAX-XiaoKui** [comment]
好，谢谢
