### ISSUE TITLE
請求漢化  Into The Maelstrom

### ISSUE THREAD

**Issue by ScoTWT** [CFPAOrg/Minecraft-Mod-Language-Package#1220]
- [ ] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [ ] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
- [ ] 非常高質量的模組 不輸暮色森林 交錯次元 可惜人氣非常低 希望有人能幫忙翻譯 也順便推廣
- [ ] https://www.curseforge.com/minecraft/mc-mods/into-the-maelstrom

**Comment by TUsama** [comment]
已在群内通知，并且我在mcbbs上也投了搬运请求，希望有人能搬运这个吧。

**Comment by TUsama** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1233
