### ISSUE TITLE
UnicodeDecodeError at 1.12.2/assets/into-the-maelstrom/intothemaelstrom/lang/zh_cn.lang

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#1239]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

lang文件注释没用`#`开头
里面混着一堆方块问号
怎么过的pr #1233 @TUsama 

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/26738f164183918e096af3e2da356d5657c79980/projects/1.12.2/assets/into-the-maelstrom/intothemaelstrom/lang/zh_cn.lang#L1

**Comment by TUsama** [comment]
？？？

**Comment by TUsama** [comment]
via 3bf11009d67e9361913f0da1a4ac5a036085306f

**Comment by exzhawk** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/88c01f1a78e9a62d842d4646b1f3fae7a642a9cc/projects/1.12.2/assets/into-the-maelstrom/intothemaelstrom/lang/en_us.lang
