### ISSUE TITLE
1.12/1.16 文件位置（再次）错位

### ISSUE THREAD

**Issue by dovisutu** [CFPAOrg/Minecraft-Mod-Language-Package#1253]
- [x] 1.12 SRParasites：目录大写，缺失lang/一层文件夹
引入 commit： d29057ed734bb2d921c074460a07d3d6e14832d0
[en_us.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/aaabdfb82e73d1426fb391605cdd13085c79bd2e/projects/1.12.2/assets/SRParasites/SRParasites/en_us.lang) [zh_cn.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/aaabdfb82e73d1426fb391605cdd13085c79bd2e/projects/1.12.2/assets/SRParasites/SRParasites/zh_cn.lang)
- [x] 1.12 dinoutil：除去完整结构，还有一对lang与lang/平行
引入 commit： e6b82720e7fbdef266a9b4ff53d54ea3d69dd300
[en_us.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/dinoutil/dinoutil/en_us.lang) [zh_cn.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/dinoutil/dinoutil/zh_cn.lang)
-  [x] 1.12 ender-compass：除去完整结构，还有一对lang与lang/平行，且文件大小写不正确
引入 commit： 39931b4fcf5a37f097f2d845e55d86fcaca34ec1
[en_US.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/ender-compass/endercompass/en_US.lang) [zh_CN.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/ender-compass/endercompass/zh_CN.lang)
- [ ] 1.12 i18nupdatemod：~我翻译我自己~根本不是assets的assets，根本不是语言文件的语言文件
引入 commit： f597e0b7c317242b23789e4e0e8e988438d829c5（存疑）
[asset_map.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/i18nupdatemod/i18nmod/asset_map/asset_map.json)
- [x] 1.12 future-minecraft：疑似asset-domain出现typo（future-minecraf~t~）
引入 commit： f597e0b7c317242b23789e4e0e8e988438d829c5（存疑）
[en_us.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/future-minecraft/futureminecraf/lang/en_us.lang) [zh_cn.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/future-minecraft/futureminecraf/lang/zh_cn.lang)
- [x] 1.12 iblis：除去完整结构，还有一对lang与lang/平行
引入 commit： 763e8790ea0bc028f4d335646551fe32828caba2
[en_us.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/iblis/iblis/en_us.lang) [zh_cn.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.12.2/assets/iblis/iblis/zh_cn.lang)
- [x] 1.16 customquests：除去完整结构，还有一个zh_cn.json与lang/平行
引入 commit： 6ab398e1a9d71a989823dc3ff73a18d4bb186836（存疑）
[zh_cn.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/6f40a85f8c8e4d953b7f44a740f52cae470abf4c/projects/1.16/assets/customquests/customquests/zh_cn.json)
- [x] 1.16 extended-nether-backport：缺失lang/一层文件夹
引入 commit： 6ab398e1a9d71a989823dc3ff73a18d4bb186836（存疑）
[en_us.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/2a794d1d1a0250ab8e911d5512bcb30869e33128/projects/1.16/assets/extended-nether-backport/extendednether/en_us.json) [zh_cn.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/2a794d1d1a0250ab8e911d5512bcb30869e33128/projects/1.16/assets/extended-nether-backport/extendednether/zh_cn.json)
- [x] 1.16 melon-slabs：缺失lang/一层文件夹
引入 commit： bad872c0f2c12a24ec2e6fa791cb4c098a79520e
[en_us.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/0d512e480722002957fc1e836d0dcf140ca9fc8a/projects/1.16/assets/melon-slabs/melonslabs/en_us.json) [zh_cn.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/0d512e480722002957fc1e836d0dcf140ca9fc8a/projects/1.16/assets/melon-slabs/melonslabs/zh_cn.json)
- [x] 1.16 scannable：除去完整结构，还有一对json与lang/平行
引入 commit： 2bd844c41f2c5f81d548e2e00c95d91968ce2566（存疑）
[en_us.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.16/assets/scannable/en_us.json) [zh_cn.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/999a1bda5babd45e21ef3a5eaf2b9e272a1e59bd/projects/1.16/assets/scannable/zh_cn.json)

**Comment by TUsama** [comment]
就剩一个了，这个怎么搞？

**Comment by dovisutu** [comment]
> 就剩一个了，这个怎么搞？

这个删了吧，反正又不是语言文件
如果后面又给爬回来了再说

**Comment by TUsama** [comment]
行了。
