### ISSUE TITLE
请问支持 Wynncraft 吗？

### ISSUE THREAD

**Issue by GF-Huang** [CFPAOrg/Minecraft-Mod-Language-Package#1263]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

https://wynncraft.com/

**Comment by dovisutu** [comment]
看了一下，这个并不属于 Minecraft 本体。
目前的翻译仅限于 Minecraft Java版 1.12.2/1.16 的模组翻译，Wynncraft 并不在此列；且目前也没有扩张翻译范围的计划（以后可能也不会有）。

**Comment by GF-Huang** [comment]
@dovisutu 支持 Better Minecraft 这种整合包吗？https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack
