### ISSUE TITLE
有没有一个列表列出具体已经翻译了哪些 mod？

### ISSUE THREAD

**Issue by GF-Huang** [CFPAOrg/Minecraft-Mod-Language-Package#1267]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

**Comment by TUsama** [comment]
没有，一般都是资源包查询或是仓库查询。

**Comment by GF-Huang** [comment]
具体怎么查？

**Comment by TUsama** [comment]
你下个对应版本的资源包，解压出来，手动查；或者你的压缩软件支持直接查询的话，就在压缩包内直接查；你也可以进到仓库的 project 文件夹内直接网页搜索。

**Comment by GF-Huang** [comment]
好的，谢谢。
