### ISSUE TITLE
为什么找不到 1.16.5 版本的？

### ISSUE THREAD

**Issue by GF-Huang** [CFPAOrg/Minecraft-Mod-Language-Package#1268]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

为什么找不到 1.16.5 版本的？

https://www.curseforge.com/minecraft/texture-packs/simplified-chinese-localization-resource-package/files

**Comment by Lyaiya** [comment]
这个已经很久没更新了。现在获取资源包有两种方法，一是安装 [I18nUpdateMod](https://www.curseforge.com/minecraft/mc-mods/i18nupdatemod) 模组自动下载资源包，二是在本仓库的 [Releases](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases) 手动下载资源包（有 1.16 字段的）。

**Comment by GF-Huang** [comment]
试过i18n，启动也没安装汉化的过程，他们的库也没说明怎么排错，太糟糕了。

**Comment by Lyaiya** [comment]
模组是无感下载资源包并直接加载到游戏中，如果进游戏没有效果可能是下载资源包这个过程出了问题。
