### ISSUE TITLE
请求汉化 jurassic world mod 侏罗纪世界重生

### ISSUE THREAD

**Issue by ScoTWT** [CFPAOrg/Minecraft-Mod-Language-Package#1277]
- [ ] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [ ] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
高质量的mod 没汉化很可惜
https://www.curseforge.com/minecraft/mc-mods/jurassic-world-reborn-mod

**Comment by TUsama** [comment]
via https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1320
