### ISSUE TITLE
模组翻译请求公示

### ISSUE THREAD

**Issue by TUsama** [CFPAOrg/Minecraft-Mod-Language-Package#1319]
本 issue 用于公示工单系统受到的翻译请求。

请注意，此公示不具有任何强制性要求，凡是载入此公示的模组翻译请求，均为介绍类性质，亦即，仅是介绍此模组，并陈述其并未被本库收录/版本落后的事实。任何对公示模组感兴趣的翻译者都可以尝试对你感兴趣的模组进行翻译。

对于并未使用工单系统，而是直接与仓库 issue 页面创建新 issue 的请求者，亦可将你的请求回复至此 issue。

如果你不知道这个issue使用来干什么的，或是想要投递翻译，请勿回复。投递翻译请使用工单系统或是发PR。

**Comment by TUsama** [comment]
模组名称：Unique Enchantments
CF 地址：https://www.curseforge.com/minecraft/mc-mods/unique-enchantments
Minecraft 游戏版本：1.16.5

**Comment by TUsama** [comment]
模组名称：Kimetsu no Yaiba (Demon Slayer)
CF 地址：https://www.curseforge.com/minecraft/mc-mods/demonslayer
Minecraft 游戏版本：1.16.5

**Comment by TUsama** [comment]
模组名称：Pokecube AIO
CF 地址：https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi
Minecraft 游戏版本：1.16.5

**Comment by TUsama** [comment]
模组名称：Oh The Biomes You'll Go
CF 地址：https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go
Minecraft 游戏版本：1.16.5

**Comment by TUsama** [comment]
模组名称：Security Craft
CF 地址：https://www.curseforge.com/minecraft/mc-mods/security-craft
Minecraft 游戏版本：1.16.5

**Comment by baka-gourd** [comment]
请求添加 RFToolsBase 模组 帕秋莉手册翻译
#1259

**Comment by TUsama** [comment]
模组名称：Infernal Expansion
CF 地址：https://www.curseforge.com/minecraft/mc-mods/infernal-expansion
Minecraft 游戏版本：1.16.5

**Comment by Lyaiya** [comment]
模组名称：Structurize
CF 地址：<https://www.curseforge.com/minecraft/mc-mods/structurize>
Minecraft 游戏版本：1.16.5

来源：#1414

**Comment by Lyaiya** [comment]
模组名称：Just Enough Effect Descriptions (JEED)
CF 地址：<https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed>
Minecraft 游戏版本：1.16.5

大量效果描述的长文本。

**Comment by TUsama** [comment]
模组名称：Kimetsu no Yaiba
CF 地址：https://www.curseforge.com/minecraft/mc-mods/demonslayer
Minecraft 游戏版本：1.16.5

请求更新。

**Comment by TUsama** [comment]
模组名称：advanced-hook-launchers
CF 地址：https://www.curseforge.com/minecraft/mc-mods/advanced-hook-launchers
Minecraft 游戏版本：1.16.5

**Comment by EnterFor** [comment]
模组名称：Silent Gear
CF 地址：https://www.curseforge.com/minecraft/mc-mods/silent-gear
Minecraft 游戏版本：1.16.5

未被本库收录，官中汉化版本落后，请求更新汉化文本。

**Comment by EnterFor** [comment]
模组名称：Buddycards
CF 地址：https://www.curseforge.com/minecraft/mc-mods/buddycards
Minecraft 游戏版本：1.16.5

模组未被本库收录，请求翻译手册。
https://github.com/wildcardgamez/BuddyCards/tree/1.16.5/src/main/resources/data/buddycards/patchouli_books/buddycard_guidebook

**Comment by CMZ-GuaYan** [comment]
模组名称：Grappling Hook Mod
CF 地址：https://www.curseforge.com/minecraft/mc-mods/grappling-hook-mod
Minecraft 游戏版本：1.16.5

官中汉化版本落后，请求更新汉化文本。

**Comment by Re107312** [comment]
模组名称：TragicMC 3
CF 地址：https://www.curseforge.com/minecraft/mc-mods/tragicmc3
Minecraft 游戏版本：1.12.2
请求添加汉化。

链接：https://pan.baidu.com/s/1YfqVZv4yGW_y5LzK1OVh_w?pwd=1234 
提取码：1234

**Comment by TUsama** [comment]
> 模组名称：TragicMC 3 CF 地址：[curseforge.com/minecraft/mc-mods/tragicmc3](https://www.curseforge.com/minecraft/mc-mods/tragicmc3) Minecraft 游戏版本：1.12.2 请求添加汉化。
> 
> 链接：[pan.baidu.com/s/1YfqVZv4yGW_y5LzK1OVh_w?pwd=1234](https://pan.baidu.com/s/1YfqVZv4yGW_y5LzK1OVh_w?pwd=1234) 提取码：1234

你好，若想投递翻译，请开PR。

关于如何开PR，请参阅这篇文章：https://github.com/LWHK/Passages/blob/master/Minecraft%20%E6%A8%A1%E7%BB%84%E7%BF%BB%E8%AF%91%EF%BC%9A%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E5%BC%80%E5%8F%91/Markdown.md#%E7%9B%B8%E5%85%B3%E6%A6%82%E5%BF%B5%E4%B8%8E%E5%B7%A5%E4%BD%9C%E6%B5%81%E7%A8%8B

如果打开有困难，也可以参考诸如：
https://www.cnblogs.com/lsgxeva/p/8540624.html
https://www.kancloud.cn/jude_ma/modtransguide/2143232#GitHub__224

你我两条回复将会在数个小时后删除，若想保存信息请及时保存。

**Comment by SlimeSB** [comment]
模组名称：oldguns
CF 地址：https://www.curseforge.com/minecraft/mc-mods/oldguns
Minecraft 游戏版本：？？

转移自#1570

**Comment by TartaricAcid** [comment]
projects 感觉更合适，Issues 还是作为专门反馈问题和建议的地方吧
