### ISSUE TITLE
Alex's mobs 与 Create Crafts & Additions 的mod汉化未生效

### ISSUE THREAD

**Issue by DuanyuV** [CFPAOrg/Minecraft-Mod-Language-Package#1397]
- [√] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [√] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

在近三个版本（最新截止至20211025）的仓库汉化资源包载入后，这两个mod的汉化均未生效。两个mod均有对应lang文件，但前者文件为空，后者有内容但是未生效。

**Comment by SlimeSB** [comment]
经查均为官中的json格式问题。
貌似alex那个已经有人给官库交了个pr修复了，create的还没有

**Comment by liuseniubi** [comment]
> 经查均为官中的json格式问题。
> 貌似alex那个已经有人给官库交了个pr修复了，create的还没有

CC&A 那边我也投了，确实是我的疏忽了。

**Comment by DuanyuV** [comment]
> 经查均为官中的json格式问题。 貌似alex那个已经有人给官库交了个pr修复了，create的还没有



> > 经查均为官中的json格式问题。
> > 貌似alex那个已经有人给官库交了个pr修复了，create的还没有
> 
> CC&A 那边我也投了，确实是我的疏忽了。

感谢各位汉化者的努力与跟进，谢谢。
