### ISSUE TITLE
匠魂3中材料Hepatizon的翻译问题

### ISSUE THREAD

**Issue by TrkvonStpd1e11** [CFPAOrg/Minecraft-Mod-Language-Package#1415]
- [ ] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [ ] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

目前而言匠魂3中Hepatizon被翻译为“黑色科林斯青铜”，应当是来自英文百科“black Corinthian bronze”的直译。但这个翻译并不合适。

匠魂中Hepatizon材料的颜色是深紫色（这个词本就来源于希腊语的“肝”，指该金属类似肝色的紫青色泽），并非是黑色；“科林斯”作为希腊地名也远不如雅典、斯巴达等为国内玩家熟知；这一材料在现实中是金银铜合金，在匠魂中是铜-钴-黑曜石合金，只能算广义青铜——综上，“黑色科林斯青铜”这一翻译并不能准确表述其性质，反而由于它和材料本身性状的不一致容易让人摸不着头脑。

此外，“黑色科林斯青铜”一词在中文互联网中几乎找不到与Hepatizon相对应的页面/词条（除MCmod百科以外），用Hepatizon一词本身能找到，但都是英文资料，考虑到国内玩家平均英语水平、查找资料的耐心，以及不安装提示类模组难以看到材料原名的现实，“黑色科林斯青铜”并不是一个好翻译。

在此，本人推荐“绀色铜”或“绀铜”这一翻译。“绀色”是一种蓝色系的颜色，又称“雪青色”“赤青色”，在服装配色和标准显示方面颜色稍有不同，但都是带有紫色的深蓝色，标准显示中RGB值为#003a6c，十分接近匠魂中Hepatizon的色彩；“绀色铜”这一名称直接指出其描述的是颜色，而“绀色”作为常见服装配色，是容易在中文互联网上找到的，且具有大量图片，不易引发歧义；“绀色铜”只描述材料颜色和归属，不包含“科林斯”这样需要额外知识的名词，易于理解，且与其余匠魂材料名称相匹配（否则“黑色科林斯青铜”一称实在过于鹤立鸡群）。

综上，提议将匠魂材料Hepatizon的翻译由“黑色科林斯青铜”变更为“绀色铜”或“绀铜”。

**Comment by ChromaPIE** [comment]
你的理由大致是：一，不易于玩家理解，缺乏资料；二，样子不像，材料不合。

首先明确的是，取“黑色科林斯青铜”的理由百分百是因为其一，Hepatizon在中文里没有直接对应的表达；其二，该材料在英语中的别称即black Corinthian bronze，能且只能译为“黑色科林斯青铜”，如果对外观上并不“黑”的“黑色”和“不能准确表述其性质”“容易让人摸不着头脑”的“青铜”有疑问，可以直接溯源并且追责英文别称的来源或者维基百科对应页面资料来源的权威性。而对于“科林斯”，译文不应因对应译文不“为国内玩家”或某个群体“熟知”而放弃采用，这不符合翻译的基本目的。

**关于“青铜”的追加说明：**“青铜”并不限制其材料中一定含有锡，如铍青铜；并且黑色科林斯青铜的配方久已失传，“金银铜”的配方也并未完全证实。

其次，你似乎在以自己的角度思考普罗大众对物品名称的态度。不可否认，绝大多数用户只视名字为代号，对汉化的要求也是是中文就行，并没有太大可能性如此刨根问底（这也印证了为何一些粗制滥造的机翻汉化的作者也能找得到排面），如若果真刨根问底，还“平均英语水平”不高，“查找资料的耐心”不足，想“看到材料原名”而不得，这类情况我们称之为**逞能**。但是，这并不意味着i18n汉化包的出品就可以“糊弄”和“想当然”，因此才选择采用维基百科这一权威来源的英文别称对应的中文译名。

最后说到你提案的“绀铜”，可谓是置原文于不顾，并且试图单纯以游戏对应物品的颜色、合成方式等属性来翻译Hepatizon这样一种在现实世界中真实存在过的材料。此外对于“十分接近”，不多言，且附上两张图供对比。上图取自colorhexa.com，使用了你给出的“绀色”（注意：#003a6c是**十六进制颜色码**，不是你所说的**RGB值**！），下图是匠魂3的黑色科林斯青铜锭纹理：

<div align=center>
<img src="https://user-images.githubusercontent.com/56111366/139884778-c2ba895b-ccc3-4671-96ee-4a3279758a3c.png"/>
</div>

<div align=center>
<img src="https://user-images.githubusercontent.com/56111366/139886433-200b6aa9-9a4b-4337-8106-4a85a5959d9b.png" width="196" height="194" />
</div>

做提案需要用权威的资料等等来支撑你的说法，我没有看到上面说法确切的的有关来源；其次做翻译首先是准确，然后才能讲易于理解，游戏翻译也是翻译，也要守规矩。
