### ISSUE TITLE
[1.18]：使用最新汉化时神秘学(Occultism)的魔灵全典 (Dictionary of Spirits)手册报错，英文版正常

### ISSUE THREAD

**Issue by GameOverUI** [CFPAOrg/Minecraft-Mod-Language-Package#1485]
### 简体中文资源包信息

1.16 2021.12.19

### 模组英文名

Occultism

### 模组版本

1.18.1-1.23.5

### 详细信息

MC版本1.18.1，使用1.16汉化资源包
测试时使用forge、Occultism及其前置模组均为目前最新版本，除此之外无其它模组
当使用汉化时，神秘学(Occultism)的魔灵全典 (Dictionary of Spirits)在使用时显示“加载时遇到错误”
![1](https://user-images.githubusercontent.com/73893589/146715620-dc914e38-7faf-46ff-89cf-b5253f683eb1.png)
当仅删除Occultism内patchouli_books的汉化文件时，手册正常打开
![2](https://user-images.githubusercontent.com/73893589/146714944-0a3834fe-120f-422a-b289-d6c76f26e59a.png)

我不知道汉化人员是否负责解决这类问题，如果不能，请提供汉化文件对应的模组版本

**Comment by TUsama** [comment]
因帕秋莉自身格式原因，本资源包无法同时支持1.16与1.18双版本的帕秋莉文本。
