### ISSUE TITLE
Modern Skyblock 2 整合包汉化进度表

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#149]
- [x] angelRingToBauble
- [ ] CapabilityProxy
- [ ] extendedcrafting
- [ ] ExtraBitManipulation
- [x] EvilCraft
- [ ] HammerCore
- [x] moartinkers
- [ ] modularmachinery
- [ ] ocsensors
- [ ] SGExtraParts
- [ ] Sky Compression
- [ ] sodiumcraft
- [ ] soot
- [ ] statues
- [ ] StructuredCrafting
- [ ] TechReborn
- [ ] TinkersComplement
- [x] tombstone
- [ ] yoyos

**Comment by meglinge** [comment]
@TartaricAcid    ActuallyAdditions  mod 自带的中文配置文件作者没有更改用的还是1.10.2的配置文件，所以1.12.2中汉化只有小部分gui界面。

**Comment by TartaricAcid** [comment]
@meglinge 实用拓展汉化已经更新，这次没有任何问题了

**Comment by sereinxx** [comment]
@TartaricAcid 这个mod玩的人真少，酒石酸菌大大可否出个视频？

**Comment by SPRshachuku** [comment]
@sereinxx 你指的是哪个mod？如果是ActuallyAddtions玩的人可不少（worldwide）然后943日常哭晕在厕所，详见http://www.bilibili.com/video/av5686854

**Comment by sereinxx** [comment]
@TartaricAcid 你bilibili上的视频都看过了，我说的是Modern Skyblock 2 整合包，好难。。。。

**Comment by TartaricAcid** [comment]
@sereinxx 视频方面的问题不要在这里反馈啊，这里只处理翻译项目。视频方面请加QQ群（我个人签名档有）
