### ISSUE TITLE
[其他]：glyph_sizes.bin 中部分全角字符宽度不正确

### ISSUE THREAD

**Issue by Dian-Jiao** [CFPAOrg/Minecraft-Mod-Language-Package#1521]
### 详细信息

全角逗号和全角小括号我看这个是改过的（（（
但是还有一些没改，比如全角中括号，大括号
BTW，像全角 26 个字母这些的宽度也不正确

1.18 更新中的 glyph_sizes.bin 修复了这些问题，建议可以直接使用 1.18 的 glyph_sizes.bin 来替换

**Comment by WuzgXY-GitHub** [comment]
提醒处理者：替换之前先把 font_map 里面的自定义区域那些的宽度改为 16。
