### ISSUE TITLE
[模组翻译]：1.18.1沉浸工程

### ISSUE THREAD

**Issue by IndigoWing** [CFPAOrg/Minecraft-Mod-Language-Package#1530]
### 简体中文资源包信息

1.18 2022-02-10/14：48

### 模组英文名

Immersive Engineering

### 模组版本

1.18.1-7.1.0-145

### 详细信息

汉化资源不完全导致沉浸工程 mod自带手册加载资源错误无法打开

**Comment by Lyaiya** [comment]
紧急修了一下，试试最新的还有没有问题

**Comment by IndigoWing** [comment]
> 紧急修了一下，试试最新的还有没有问题

已修复
