### ISSUE TITLE
[其他]：痛快

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#1541]
### 详细信息

![47c51ca9ef6f651](https://user-images.githubusercontent.com/14993992/154199617-1b26bbc2-d869-42f2-be39-df71b6f83825.jpg)

**Comment by core-exe** [comment]
好意思评价别人嘴脸？
![6N_BQBC{3_NECP~@6C0PGCK](https://user-images.githubusercontent.com/52733394/154200273-e3cc542d-7fed-4508-80e2-b53738125dad.png)

**Comment by Seedking** [comment]
派哥为什么要拳打943

**Comment by TheRealKamisama** [comment]
![9W0T {(0S1N18KGRP(50@~4](https://user-images.githubusercontent.com/35005476/154208575-2b857c48-103c-4f97-b9f3-d64ebc92c7a4.png)
