### ISSUE TITLE
[其他]：征集“硅岩”与“纳夸达”之外的“Naquadah”中文翻译！

### ISSUE THREAD

**Issue by Seedking** [CFPAOrg/Minecraft-Mod-Language-Package#1542]
### 详细信息

同志们！我们应该停止无意义的争论！齐心解决目前的问题！
既然双方争吵不休，大家却又想探究真理！那我们不如发挥开源社区的优良传统就开始讨论如何**正确的翻译“Naquadah”**吧！
以最终结果来替代“Naquadah”的现有中文翻译！

添加一个DDL，就设置在18号这个时候吧！
一起期待最后投票最多的是什么！

**Comment by 780712** [comment]
https://github.com/Cyl18/NaquadahFix
已有

**Comment by koiNoCirculation** [comment]
如果要回答这个问题，你得好好研究星际之门，然而我恰好没怎么看过，那只能保持现状。

**Comment by LasmGratel** [comment]
拿大胯

**Comment by EnderAvaritia** [comment]
个人还是建议用硅岩，毕竟是用久了的名字，要尊重用语习惯。（当然，要是只有我一个人这么用，我改）或者专有名词就不翻译了。

**Comment by colorlessfirefly** [comment]
我看石圭山石挺不错

**Comment by KuroPeach** [comment]
为什么要换？满足权力欲？社区大改动？

**Comment by koiNoCirculation** [comment]
> 我看石圭山石挺不错

搁着拆字反河蟹呢😅😅😅😅😅

**Comment by KuroPeach** [comment]
![VF{9R)06{WKL%IH~Z_0)IE4](https://user-images.githubusercontent.com/19620848/154205665-28b10345-b74f-4e40-8415-17be1d322f5d.png)
这只是其一

**Comment by KuroPeach** [comment]
![image](https://user-images.githubusercontent.com/19620848/154206037-7fa6860c-12e0-4183-b5b5-64eb484977e7.png)
![image](https://user-images.githubusercontent.com/19620848/154206096-70e82f87-b901-4866-af2a-9addf19c6d3f.png)
其二

**Comment by KuroPeach** [comment]
![image](https://user-images.githubusercontent.com/19620848/154206450-42228f1b-b8e5-4885-bf87-0052820bd686.png)
![image](https://user-images.githubusercontent.com/19620848/154206517-66b8c4e3-2fc7-44d0-a5e0-cbbd13c63396.png)
![image](https://user-images.githubusercontent.com/19620848/154206599-332c5b71-4d09-4d09-8aaf-f0083c160e3b.png)
![image](https://user-images.githubusercontent.com/19620848/154206694-9d3561ec-b6e0-43bf-a25f-081c725b4820.png)

**Comment by KuroPeach** [comment]
> 别反驳我啊QAQ，去多叫一些人来评论！

不反驳，合你心意，社区资料大改动是吧

**Comment by nadahqua** [comment]
因为硅是石英，所以取一个石英的英，即”像玉的美石“。又因为是金属，所以取金。写作英金、金英、钅英、锳。

**Comment by n0099** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1536#issuecomment-1040325259
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1536#issuecomment-1041032237
> 我强烈推荐使用“銙”，并且有以下几点原因： 1.这是一个在汉字历史中出现的字，并且不是“硅岩”和“纳夸达”其中任何一个。 2.和翻译元素周期表的先辈有差不多的道理，都是取其读音中的一块发音找到对应的带金字旁的汉字，它的读音拼音为“kuǎ” 3.这是一个可以由大家决定的机会，并不由一个人私自修改，或者由一个人私自拍板。

支持正义meaqua贴贴
![](https://user-images.githubusercontent.com/13030387/154234122-0aa96b9b-67a1-429f-8290-30070acb6efa.jpg)

**Comment by WKyouka** [comment]
我赞同上面的意见，如果选择更改，那以前留下的所有资料都将变得混乱，译者可能想未来大家会逐渐去使用新翻译，但实际上的结果是两个翻译会同时存在很长时间。举一个很明显的例子，“地狱”和“下界”这两个同样代表Nether的翻译同时存在，而且这两个词将长期共存下去。
如果真的要修改，那就要负起责任来，将以往所有的整合包中的任务书中的“硅岩”也一并改掉，同时，尽可能找到各个社区的管理人员，让他们将过去的“硅岩”一词替换为新词，以避免新手在接触这些物品时混乱。

如若不能承担更改译名所要背负的一系列责任，则不要更改该词，其余翻译同理。

**Comment by Seedking** [comment]
> 我赞同上面的意见，如果选择更改，那以前留下的所有资料都将变得混乱，译者可能想未来大家会逐渐去使用新翻译，但实际上的结果是两个翻译会同时存在很长时间。举一个很明显的例子，“地狱”和“下界”这两个同样代表Nether的翻译同时存在，而且这两个词将长期共存下去。 如果真的要修改，那就要负起责任来，将以往所有的整合包中的任务书中的“硅岩”也一并改掉，同时，尽可能找到各个社区的管理人员，让他们将过去的“硅岩”一词替换为新词，以避免新手在接触这些物品时混乱。
> 
> 如若不能承担更改译名所要背负的一系列责任，则不要更改该词，其余翻译同理。

这不是已经有人打破这个想法了，既然打破了，就要打破到底！不如创造一个全新的词来称呼Naquadah

**Comment by Seedking** [comment]
我个人建议CFPA的组员也积极参与讨论，否则最后结果可能倾向于社区哦，到时候不改可不好呢

**Comment by TheRealKamisama** [comment]
> > 我赞同上面的意见，如果选择更改，那以前留下的所有资料都将变得混乱，译者可能想未来大家会逐渐去使用新翻译，但实际上的结果是两个翻译会同时存在很长时间。举一个很明显的例子，“地狱”和“下界”这两个同样代表Nether的翻译同时存在，而且这两个词将长期共存下去。 如果真的要修改，那就要负起责任来，将以往所有的整合包中的任务书中的“硅岩”也一并改掉，同时，尽可能找到各个社区的管理人员，让他们将过去的“硅岩”一词替换为新词，以避免新手在接触这些物品时混乱。
> > 如若不能承担更改译名所要背负的一系列责任，则不要更改该词，其余翻译同理。
> 
> 这不是已经有人打破这个想法了，既然打破了，就要打破到底！不如创造一个全新的词来称呼Naquadah

破四旧是吧, 老祖宗的东西包括帝制都是好的, 可不敢乱破.

**Comment by EnderAvaritia** [comment]
> 我个人建议CFPA的组员也积极参与讨论，否则最后结果可能倾向于社区哦，到时候不改可不好呢

我寻思……译名不久应该倾向于社区吗？不然每个汉化组一上来就按自己的标准来一遍？那可太刺激了。

**Comment by EnderAvaritia** [comment]
> > > 我赞同上面的意见，如果选择更改，那以前留下的所有资料都将变得混乱，译者可能想未来大家会逐渐去使用新翻译，但实际上的结果是两个翻译会同时存在很长时间。举一个很明显的例子，“地狱”和“下界”这两个同样代表Nether的翻译同时存在，而且这两个词将长期共存下去。 如果真的要修改，那就要负起责任来，将以往所有的整合包中的任务书中的“硅岩”也一并改掉，同时，尽可能找到各个社区的管理人员，让他们将过去的“硅岩”一词替换为新词，以避免新手在接触这些物品时混乱。
> > > 如若不能承担更改译名所要背负的一系列责任，则不要更改该词，其余翻译同理。
> > 
> > 
> > 这不是已经有人打破这个想法了，既然打破了，就要打破到底！不如创造一个全新的词来称呼Naquadah
> 
> 破四旧是吧, 老祖宗的东西包括帝制都是好的, 可不敢乱破.

我的看法是，目前已经成形的就这样吧，再来一遍那也不过是重复后尘，纯属讨骂行为，把最近几个乱改的改回来就好了，之后建立合理的公示与表决方式。

**Comment by nadahqua** [comment]
> 

是的，我也这么认为。同时建议库中的纹理全部改回材质。

**Comment by EnderAvaritia** [comment]
> > 
> 
> 是的，我也这么认为。同时建议库中的纹理全部改回材质。

材质就算了，之前我翻wiki的时候发现翻译改了。（但是别人改翻译搜材质也是定向到纹理，后面还注明旧译）

**Comment by xiaoACE6716** [comment]
抛开MC圈子的观点不谈，上网去搜Naquadah，看星际之门的大部分网友，直接称之为Naquadah或N矿，或硅岩（金属），而在其他游戏里面用到的Naquadah大多数也被中国网友翻译或称作硅岩（金属），所以我认为应该继续使用 硅岩 这个翻译
