### ISSUE TITLE
[其他]：关于上勾拳

### ISSUE THREAD

**Issue by Nxer** [CFPAOrg/Minecraft-Mod-Language-Package#1544]
### 详细信息

我头上这几顶 恶臭 铸币 遗老 的帽子 CFPA 负责人能不能帮我摘一下啊
我这还白挨了一记上勾拳
我又不是荷鲁斯之眼啊

**Comment by AlucardAetia** [comment]
上班摸鱼看到这条没忍住

**Comment by TartaricAcid** [comment]
我看到了 github 上面一些争吵，确实双方的言辞都非常激烈

严格来说，双方是在错误的地方为一个错误的事情打了一场错误的战争

感谢你的理解（双方已经私下和解了，对方表示了歉意）
