### ISSUE TITLE
[模组翻译]：振动合金

### ISSUE THREAD

**Issue by DoremySwee** [CFPAOrg/Minecraft-Mod-Language-Package#1545]
### 详细信息

振动合金是啥，振动合金棒吗？
我不是很认同某些自以为vibrant和vibrating一样然后乱翻的行为。
就算是瞎起名，脉冲还好点，听起来靠谱。
振动，直接当vibrating bar或者vibrating rod用吗。
我不是很能理解。

**Comment by n0099** [comment]
> 振金（英文：Vibranium；台湾译名：钒合金、泛合金，又作吸音钢），是漫威电影宇宙作品中虚构的一种金属元素，首次出现于电影《美国队长》。

https://www.zhihu.com/question/38870976

**Comment by AlucardAetia** [comment]
![QQ图片20220217132558](https://user-images.githubusercontent.com/98082092/154411360-27c68ddf-968f-4ca6-a58e-c34f10b02e17.jpg)

**Comment by iouter** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1558

**Comment by TartaricAcid** [comment]
已经修改回退 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/3ae78316e46ef1427351cb6c5450946d93831f9f
