### ISSUE TITLE
[其他]：关于材质

### ISSUE THREAD

**Issue by nadahqua** [CFPAOrg/Minecraft-Mod-Language-Package#1546]
### 详细信息

我寻思在当时社区都叫材质的时候也没几个多少人里面发帖来指正这个玩意啊？
这些人是不知道东西不坏就不要修的道理啊😅

说一嘴 材质那么长一段时间 现在就因为某些人的装逼来改掉大多数人的习惯 我只能说是吃饱了没事做 你早他妈干什么去了。

**Comment by ff98sha** [comment]
请求把Crafting Table从“工作台”改成“合成台”，因为原文在2011年1月13日就从变成了Workbench
