### ISSUE TITLE
[其他]：有没有一种可能

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#1552]
### 详细信息

![A(9BX{A~NJ 9TBWZJSIH4YC](https://user-images.githubusercontent.com/14993992/154284307-d9843f0e-57be-47ab-a727-0f3ddf35e9ad.png)

![image](https://user-images.githubusercontent.com/14993992/154284287-87e159f4-00dc-448e-9930-43f437797e08.png)

**Comment by cnlimiter** [comment]
Md,看不下去了，别在这继续搅混水了，你不是有新项目么，去维护呗。
