### ISSUE TITLE
[其他]：请问贵组的翻译目的

### ISSUE THREAD

**Issue by DSRLIN** [CFPAOrg/Minecraft-Mod-Language-Package#1553]
### 详细信息

爬完了整个PR和Issues，现在真心想请教，贵组的翻译目的是什么？
是做学究？还是服务于整个社区？

**Comment by TartaricAcid** [comment]
很显然，是提供一个看起来还算不错的翻译

物极必反，无论是随便翻译还是过于考究深究翻译，都不可取。
其次，也不应当花费太多时间在无需更改的翻译上，毕竟我们还有生活。

**Comment by TartaricAcid** [comment]
先前事件已结束，此 Issues 已关闭
