### ISSUE TITLE
[建议] 工作流程修改

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#1561]
### 详细信息

基于近期的风波，我建议采用类似 dotnet/runtime 所采用的工作模式：
- 主分支作为 beta 分支，所有工作向主分支上提交
- release 分支作为 release，汉化包打包只在 release 分支上进行
- 一段周期后将主分支 PR/rebase 至 release 分支

这样既不会更改现有大部分成员的工作流程，方便直接提交，不会提升很多人力需求，也可以 review 更多的 commit。

另外还有的可能是每个 PR 都要求有两个人 review 才能提交，当然人力不足的情况下没有办法。

另外的另外，补充出现争议的解决办法..？

**Comment by EnderAvaritia** [comment]
或许可以？
分为A，B，R分支。
A分支以快为准，B分支是在A分支的基础上经过人工审核，B经过公示后进入R分支。
自认为R分支为用于交流的翻译，在A，B分支内明显处写上该版本翻译不一定为大众认可。
只允许逐级提交。

**Comment by n0099** [comment]
硅岩社区那边提出的不也是分release beta alpha branchs吗

**Comment by n0099** [comment]
> **关键是有人做吗**

无

**Comment by EnderAvaritia** [comment]
> ABR/BR 我是觉得ABR增加复杂度 需要更多人力 不利于快速迭代 而BR不需要太多修改 *关键是有人做吗

ABR主要是怕后面审核来不及。

**Comment by Cyl18** [comment]
现在这样就挺好了，之后看拉人和翻译平台的事情
