### ISSUE TITLE
[其他]：修订 CONTRIBUTING.md，增订关于 PR Review 的相关事宜

### ISSUE THREAD

**Issue by GreyElaina** [CFPAOrg/Minecraft-Mod-Language-Package#1565]
### 详细信息

*draft*

**Comment by n0099** [comment]
#1561

**Comment by SlimeSB** [comment]
review只要做到清秋那样的就可以了 :) 你猜为啥前朝元老没写。

**Comment by n0099** [comment]
> review只要做到清秋那样的就可以了 :) 你猜为啥前朝元老没写。

经典事实标准

**Comment by TartaricAcid** [comment]
额……具体的提案呢？怎么是空的？

**Comment by GreyElaina** [comment]
> 额……具体的提案呢？怎么是空的？

这个假期我个人仍然超多事情(现实里)，所以暂时还是draft...
我大概会在下周把在我手记内的东西录入进去，当然这之前我还是得开个讨论。。。

**Comment by GreyElaina** [comment]
#1577
