### ISSUE TITLE
[其他]：关于对机翻的态度问题

### ISSUE THREAD

**Issue by SlimeSB** [CFPAOrg/Minecraft-Mod-Language-Package#1568]
### 详细信息
@n0099 
> 19年那会通过weblate提交的少数gtce翻译commit是机翻：
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/e69f1966835060a5027a71ad1ba1cbc3c814b08d#diff-fb52c743e6feb9f6914c669197ee6b4117b3e490d25a06ba2b5c3e08a9bad566R2812
> ![](https://user-images.githubusercontent.com/13030387/154808190-6c6699bb-8681-4dd6-95ca-bb2f10283cce.png)
> 
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/09bc850d75fea8d7dc9fc8d4e5cd819c718eaee6#diff-fb52c743e6feb9f6914c669197ee6b4117b3e490d25a06ba2b5c3e08a9bad566R2913
> ![](https://user-images.githubusercontent.com/13030387/154808269-3000f620-2163-4559-b96a-179b571b3b0c.png)
> ![](https://user-images.githubusercontent.com/13030387/154808267-a4646f7a-5046-4f06-a4a5-43c8f3bf3e0e.png)
> 
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/e69f1966835060a5027a71ad1ba1cbc3c814b08d/project/assets/gregtech/lang/zh_cn.lang#L2811
> ![](https://user-images.githubusercontent.com/13030387/154809109-4034bb56-f6c6-4075-93f4-f4a8f2149d37.png)
> 
> 近期引入的复制粘贴错误：
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/b7b97abb8ef14dfc20d2880a0d6b3519301cf5fc/projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang#L1961
> ![](https://user-images.githubusercontent.com/13030387/154808542-0bb42047-0a01-4f7f-aa61-fd965d243baa.png)

@SlimeSB

> **首先哈，我不是给他们洗地的，不存在前朝元老就是我心中的神，我心中的偶像。**其次想请教你在此把矛头引向gtce居心何在？如果你和我一样反对机器翻译，大可不必特意回复我。否则我想知道你支持机翻的理由。
> 说到底，我不是来对线的，在pr下面发的无关内容也够多了，你对我的不满或讽刺或这个那个的，请转战频道或者与我私聊。

@EnderAvaritia
> 首先，我知道近期发生的事对双方影响都很大，但是工作还是得继续做下去的，不能因为情绪而影响到使用者，不然就真的成乐子了，其次，还是有些路人想要共享自己的翻译的，并不是每个人都会去看守则，有的人只是自己顺手翻译了，然后看着有用，就好心过来帮助我们，以我们的标准要求并不清楚的人，这本身就很过分。再者，这句话
> > 解释解释，一是为什么把the bane丢了，二是为什么和deepl给的一样。

> 的语气委实很难让人接受。

**Comment by SlimeSB** [comment]
@n0099 @EnderAvaritia

**Comment by n0099** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1559#issuecomment-1046038319

**Comment by mamaruo** [comment]
Naquadah 事件中 ChromaPIE 遭到声讨至少一半原因是他说的话而不是做的事。

CFPA 还处在余波之中，能小心点就小心点吧。

**Comment by n0099** [comment]
@LasmGratel 如是说
![](https://user-images.githubusercontent.com/13030387/154809866-d8f594c3-4508-4d34-8e2a-43e23c802070.jpg)

**Comment by SlimeSB** [comment]
好，那么这个问题就变成了审核时的态度讨论了。尤其是什么错误是应该被声讨的？这个问题。
首先，大范围机翻应该被声讨，我想没有人有意见。那么我们就来讨论，对于翻译基本靠机器完成，人仅提供润色的，应该采取什么态度。

**Comment by EnderAvaritia** [comment]
> 好，那么这个问题就变成了审核时的态度讨论了。尤其是什么错误是应该被声讨的？这个问题。 首先，大范围机翻应该被声讨，我想没有人有意见。那么我们就来讨论，对于翻译基本靠机器完成，人仅提供润色的，应该采取什么态度。进而推而广之到自以为天衣无缝而被审核发现蛛丝马迹时（与1559无关），应该以什么态度。

我相信态度友好的话，一般人应该是都能接受的。
其次，对于翻译，个人认为机翻润色是有存在意义的，毕竟让人一条一条的去看对人的精力和能力要求还是有点高的，但是对于机翻之后基本就是直接搬过来的，那就没有接受的必要了。（拿过去翻我不会啊）但这样引出的问题就是检查是不是机翻的人力成本太高，对此，我不知道怎么解决。而对于最后哪个问题，花费大量精力伪造，贡献一个不会带来明显回报的事情，总感觉多少有点问题。（或许黑名单很适合他）

**Comment by SlimeSB** [comment]
> 但这样引出的问题就是检查是不是机翻的人力成本太高，对此，我不知道怎么解决。

我在此顺便和一些审核说一下，不逐行逐行对照，你以为审核那么容易看看中文就行了吗。去看看l113和l130，一处是中英文不相符，一处是你们花了大把时间讨论的标点问题。这还是明显的错误。长文本依然存在语病等问题。

**Comment by n0099** [comment]
> 好，那么这个问题就变成了审核时的态度讨论了。尤其是什么错误是应该被声讨的？这个问题。 首先，大范围机翻应该被声讨，我想没有人有意见。那么我们就来讨论，对于翻译基本靠机器完成，人仅提供润色的，应该采取什么态度。进而推而广之到自以为天衣无缝而被审核发现蛛丝马迹时（与1559无关），应该以什么态度。
> 
> 对于绝大多数贡献者，与CFPA的缘分仅尽于某个模组的汉化，通过工单或者github提交过来。尤其是工单，每天遭受的机翻文件尤为多，至少我在8月份就看见某些含严重错误的入库了，本来打算修然后开学了。 让各位审核去审大概比我还暴躁，只是猜测。我自认为“解释解释”属于语气比较轻的责备了。

我只知道机翻也可能会使用纳夸达或者硅岩金属这种译名，因为两者都存在于互联网上可被爬虫知晓
而反过来有时人翻译的有时可能还不如机翻准确，所以不应该只盯着是否使用了机翻本身，而是评估翻译质量文本是否通顺

工单系统我的建议是把他改成一个自动发布工单内容到github issue区的bot，回复issue也会通知工单发布者（如果他留了通讯方式）
提交者即便只是用程序完全自动化机翻过了一遍en_us.lang文件，也不代表他就一定是来恶意提交增加审核成员的工作量的（除非同一个账号/小号经常这么干），应该按照假定善意原则认为他只是普通mod玩家想要玩到中文版mod而已，他自己并不在乎翻译质量所以直接套了机翻。当然这并不代表CFPA就要全盘照收这些批量机翻提交，我在原comment中只是指出19年时weblate上仅GTCE一个mod就有许多这样的批量机翻提交

**Comment by n0099** [comment]
> > 但这样引出的问题就是检查是不是机翻的人力成本太高，对此，我不知道怎么解决。
> 
> 我在此顺便和一些审核说一下，不逐行逐行对照，你以为审核那么容易看看中文就行了吗。去看看l113和l130，一处是中英文不相符，一处是你们花了大把时间讨论的标点问题。这还是明显的错误。长文本依然存在语病等问题。

标点的问题是现行的翻译规范中并没有规定很多mod常遇到的edge cases，比如 200mg 还是 200 mg，`[]`用不用全角版
长文长句本来就很容易写出病句来，如果提交者是套的机翻那可以一眼读出机翻风格

**Comment by Nxer** [comment]
机翻就像音译，在没更好的方案前不得已临时使用
但最终对外公布的版本是一定不能使用的，所以我认为机翻没必要提交上来，因为谁都可以自己做机翻
但没必要引导冲突
走流程就完事
有参考意义就留着没参考意义简单回复一下关了就得了

**Comment by SlimeSB** [comment]
> > > 但这样引出的问题就是检查是不是机翻的人力成本太高，对此，我不知道怎么解决。
> > 
> > 
> > 我在此顺便和一些审核说一下，不逐行逐行对照，你以为审核那么容易看看中文就行了吗。去看看l113和l130，一处是中英文不相符，一处是你们花了大把时间讨论的标点问题。这还是明显的错误。长文本依然存在语病等问题。
> 
> 标点的问题是现行的翻译规范中并没有规定很多mod常遇到的edge cases，比如 200mg 还是 200 mg，`[]`用不用全角版 长文长句本来就很容易写出病句来，如果提交者是套的机翻那可以一眼读出机翻风格

我的意思是，假如未来的某一天，你花了差不多三个小时看了一个5k行改动的pr。结果在最后一行终于发现（此时才出现重大错误让你断定），之前那些勉强说得过去的句子全是按照百度翻译的。在你知道其大面积使用机翻的情况下，并做了许久无用功，你是什么心情，不妨说说。

**Comment by n0099** [comment]
> 机翻就像音译，在没更好的方案前不得已临时使用 但最终对外公布的版本是一定不能使用的，所以我认为机翻没必要提交上来，因为谁都可以自己做机翻 但没必要引导冲突 走流程就完事 有参考意义就留着没参考意义简单回复一下关了就得了

纳夸达是比硅岩更好的方案吗？

**Comment by Nxer** [comment]
> 纳夸达是比硅岩更好的方案吗？

那显然不是

**Comment by n0099** [comment]
> > > > 但这样引出的问题就是检查是不是机翻的人力成本太高，对此，我不知道怎么解决。
> > > 
> > > 
> > > 我在此顺便和一些审核说一下，不逐行逐行对照，你以为审核那么容易看看中文就行了吗。去看看l113和l130，一处是中英文不相符，一处是你们花了大把时间讨论的标点问题。这还是明显的错误。长文本依然存在语病等问题。
> > 
> > 
> > 标点的问题是现行的翻译规范中并没有规定很多mod常遇到的edge cases，比如 200mg 还是 200 mg，`[]`用不用全角版 长文长句本来就很容易写出病句来，如果提交者是套的机翻那可以一眼读出机翻风格
> 
> 我的意思是，假如未来的某一天，你花了差不多三个小时看了一个5k行改动的pr。结果在最后一行终于发现（此时才出现重大错误让你断定），之前那些勉强说得过去的句子全是按照百度翻译的。在你知道其大面积使用机翻后，才意识到做了许久无用功，你是什么心情，会怎么suggest，不妨说说。

我前面已经说了
> 而反过来有时人翻译的有时可能还不如机翻准确，所以不应该只盯着是否使用了机翻本身，而是评估翻译质量文本是否通顺

一段文本是人肉还是百度还是google还是bing还是deepl translate出来的并不重要，重要的是首先读不读的通
其次是跟en原文语义上相差多少，实际上有些en梗尤其是谐音双关是很难在中文里找到对应的隐喻的，这种情况您只能选择按字面意思直译
当然我们都知道这些不可能量化是完全主观的，就像此前https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1567#issuecomment-1045999783 所说：
> 首先是“我认为”，我来我认为下。翻译项目不可能完全社区化，因为翻译是一个完全主观的东西，独裁是必然的

**Comment by SlimeSB** [comment]
你说的十分中肯。我也没什么继续说的了。但我想你在体验了审核的滋味后，或多或少会对你的想法产生影响。那就那时再说吧。

**Comment by Nxer** [comment]
> 你说的十分中肯。我也没什么继续说的了。但我想你在体验了审核的滋味后，或多或少会对你的想法产生影响。那就那时再说吧。

审核确实是会经常吃屎。不如叫特性。

**Comment by Cyl18** [comment]
![image](https://user-images.githubusercontent.com/14993992/154813350-ef750cad-b5c6-4ec5-95d9-fab4eca8be5e.png)


> 你说的十分中肯。我也没什么继续说的了。但我想你在体验了审核的滋味后，或多或少会对你的想法产生影响。那就那时再说吧。

我昨天审EIO回退都审了一个多小时 看各种纠结 还翻 git blame
![image](https://user-images.githubusercontent.com/14993992/154813386-3a897289-d5df-4e8d-bdd2-06c419e456f9.png)

**Comment by Cyl18** [comment]
对机翻的看法：湾湾的i18n mod可以自己启用机翻功能

**Comment by n0099** [comment]
> ![image](https://user-images.githubusercontent.com/14993992/154813350-ef750cad-b5c6-4ec5-95d9-fab4eca8be5e.png)
> 
> > 你说的十分中肯。我也没什么继续说的了。但我想你在体验了审核的滋味后，或多或少会对你的想法产生影响。那就那时再说吧。
> 
> 我昨天审EIO回退都审了一个多小时 看各种纠结 还翻 git blame ![image](https://user-images.githubusercontent.com/14993992/154813386-3a897289-d5df-4e8d-bdd2-06c419e456f9.png)

对我而言保留脉冲电容库就行了，（重质）（无声）这种verbose后缀我也没办法

**Comment by n0099** [comment]
> 对机翻的看法：湾湾的i18n mod可以自己启用机翻功能

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1567#issuecomment-1045999783
> RPMTW 汉化的底子是这边的，具体你自己去看他们仓库。

> 首先我认为 .net 社区的方案是不可借鉴的。其实可能不知道的是之前开过一个更激进的仓库，没有审核即改即入，后面删库了，因为一个月除了我 init 的 commit 后面就啥都没有了。
> 我之前和他人共同的方针和对面 RPMTW 的差不多：先改，有有效反馈就改/回退，没反馈就不动了。整个投票挂个两星期投票人不超过 10 人（200 人活跃）后面出个截止一堆选看结果的我不认为这种投票有什么价值。

**Comment by Cyl18** [comment]
投票的事还是看mod的体量 还是他们说的一个mod如果完工了就不乱改了
说到底还是在绕圈 几天前就在聊这个事

**Comment by n0099** [comment]
> 投票的事还是看mod的体量 还是他们说的一个mod如果完工了就不乱改了 说到底还是在绕圈 几天前就在聊这个事


![](https://user-images.githubusercontent.com/13030387/154813964-a13bd4af-12c4-4971-8400-5dd72d527ff5.png)
![](https://user-images.githubusercontent.com/13030387/154813962-0361f8dd-fb0f-4819-ba13-2256f0645793.png)

**Comment by TartaricAcid** [comment]
……这怎么又长篇大论起来了

一句话，机翻的问题少了，审核改它就完事了；太多了，我直接回退就完事了。
