### ISSUE TITLE
[议程]：revert GT 相关修改

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#1569]
### 详细信息

这边GT改了太多东西 看GTCE仓库那边已经好久没维护了
revert的理由和EIO的一样
也不知道和GTCE汉化组那边怎么样

涉及mod
projects/1.12.2/assets/1UNKNOWN/gregtech-gregic-additions/lang/zh_cn.lang
projects/1.12.2/assets/1UNKNOWN/gregtech-gregs-construct/lang/zh_cn.lang
projects/1.12.2/assets/gregicality/gtadditions/lang/zh_cn.lang
projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
projects/1.12.2/assets/gtce-bees/gtcebees/lang/zh_cn.lang
projects/1.12.2/assets/shadows-of-greg/gtadditions/lang/zh_cn.lang

**Comment by TartaricAcid** [comment]
可以发 PR 来 revert 就行，我对 GT 不是很熟悉，看有没有其他人来整理下

**Comment by n0099** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1568#issue-1144775874

> 19年那会通过weblate提交的少数gtce翻译commit是机翻：
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/e69f1966835060a5027a71ad1ba1cbc3c814b08d#diff-fb52c743e6feb9f6914c669197ee6b4117b3e490d25a06ba2b5c3e08a9bad566R2812
> ![](https://user-images.githubusercontent.com/13030387/154808190-6c6699bb-8681-4dd6-95ca-bb2f10283cce.png)

> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/09bc850d75fea8d7dc9fc8d4e5cd819c718eaee6#diff-fb52c743e6feb9f6914c669197ee6b4117b3e490d25a06ba2b5c3e08a9bad566R2913
> ![](https://user-images.githubusercontent.com/13030387/154808269-3000f620-2163-4559-b96a-179b571b3b0c.png)
> ![](https://user-images.githubusercontent.com/13030387/154808267-a4646f7a-5046-4f06-a4a5-43c8f3bf3e0e.png)

> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/e69f1966835060a5027a71ad1ba1cbc3c814b08d/project/assets/gregtech/lang/zh_cn.lang#L2811
> ![](https://user-images.githubusercontent.com/13030387/154809109-4034bb56-f6c6-4075-93f4-f4a8f2149d37.png)
近期引入的复制粘贴错误：
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/b7b97abb8ef14dfc20d2880a0d6b3519301cf5fc/projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang#L1961

> ![](https://user-images.githubusercontent.com/13030387/154808542-0bb42047-0a01-4f7f-aa61-fd965d243baa.png)

**Comment by TartaricAcid** [comment]
GTCE 相关修正已经完成，关闭此 Issues
