### ISSUE TITLE
[其他]：审核人员的态度问题

### ISSUE THREAD

**Issue by KuroPeach** [CFPAOrg/Minecraft-Mod-Language-Package#1577]
### 详细信息

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1573
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1559
这就是审核人员的态度？过官瘾？难怪之前逐渐发展为一言堂，翻译本就是个随缘爱好，但贵组一些人员的态度却是在打击路人积极性。虽说翻译有误确实不好，指出就好，但用得着咄咄逼人一副高高在上的样子，真当翻译就是人上人啊！

**Comment by Cyl18** [comment]
关于#1559
![image](https://user-images.githubusercontent.com/14993992/155336878-9b912bc5-9e90-491a-ac83-714ff9e65ae1.png)

**Comment by MikhailTapio** [comment]
事情发展成这样，少不了你这个跳脸拱火的无耻东西。

**Comment by TartaricAcid** [comment]
FNCN 不是 CFPAOrg 的 member，我也不认识这个账户；SlimeSB 确实是 CFPAOrg 的 Collaborator，对于之前的事情我表示歉意，已经对对方提出批评了。

其次，开源项目没有管理者，只有维护者。任何一个路人都可以参与进来提供意见和建议，所以我只能做到约束自己，以及周围认识的几个人的言行。如果在遇到类似问题，可以随时 @TartaricAcid 我，或者 @Cyl18 来帮忙解决矛盾，这也算是我们目前能做到的唯一的事情了吧。

最后再次致歉。

**Comment by KuroPeach** [comment]
了解了，谢谢
