### ISSUE TITLE
[模组翻译]：Vulcanite译名

### ISSUE THREAD

**Issue by Rinko1231** [CFPAOrg/Minecraft-Mod-Language-Package#1580]
### 简体中文资源包信息

1.12.2、1.16.5

### 模组英文名

Vulcanite

### 模组版本

1.12.2

### 详细信息

实际上，这个矿物跟碲、铜都没有关系，跟“软碲铜”唯一相似的只有红红的颜色。
Vulcanite在此处更像是Vulcan（火与工匠之神）+ite，而该金属确实是“和熔岩、火有关”，且所制成的工具有自动冶炼的能力。
软碲铜或为错译，现观此mod没有什么话题度和“老玩家群体”（毕竟内容很简单，甚至用魔改mod就能做出来），或可修改译名以正视听，还望社区指点一二。

**Comment by n0099** [comment]
建议瓦肯锭（星际迷航）

**Comment by Cyl18** [comment]
为啥close了

**Comment by MikhailTapio** [comment]
> > 为啥close了
> 
> 可能害怕纳夸达

因为找到译成软碲铜的依据了
