### ISSUE TITLE
[其他]：请求更新翻译byg mod v1.3.5 mc1.16.5

### ISSUE THREAD

**Issue by xingmot** [CFPAOrg/Minecraft-Mod-Language-Package#1596]
### 详细信息

curseforge地址：https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3485079
工作量可能不是很大（（
我是在汉化另一个模组时，其联动是byg（你将去的生物群系）mod，而该mod汉化文件可能年代久远，好多物品没有翻译。有空的人可以看看。
不自己动手主要两方面原因，一是专业知识水平不足以支撑这类 生态群系mod，另一方面我手头翻译的模组可能还面临版本迁移之类的问题（毕竟我不是开坑天王。。）

**Comment by n0099** [comment]
[byg自带的zh_cn.json.txt](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/8149547/byg.zh_cn.json.txt)
byg自带翻译文件翻译了2083个key，原文en.lang里有2322个key，而cfpa只翻译了34个key
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/3183f5952ddff84d48279f0927fbe1f0b5a26a40/projects/1.16/assets/oh-the-biomes-youll-go/byg/lang/zh_cn.json#L1-L36

**Comment by n0099** [comment]
我建议删除cfpa的lang文件，或者将byg自带翻译复制过来（如果byg的开源协议允许）

**Comment by ChuijkYahus** [comment]
BYG已经在翻了，目前还没有pr，正向作者咨询一些词汇的词源
[https://github.com/AOCAWOL/BYG/pull/704](https://github.com/AOCAWOL/BYG/pull/704)

**Comment by mamaruo** [comment]
#1831 #1913
