### ISSUE TITLE
[其他]：请求翻译 Backpacked

### ISSUE THREAD

**Issue by mamaruo** [CFPAOrg/Minecraft-Mod-Language-Package#1598]
### 详细信息

https://github.com/MrCrayfish/Backpacked/
https://www.mcmod.cn/class/2228.html
https://www.curseforge.com/minecraft/mc-mods/backpacked/

**Comment by n0099** [comment]
这mod还不如sophisticated backpacks，，，

**Comment by Nxer** [comment]
![QQ截图20220305075616](https://user-images.githubusercontent.com/43300390/156857474-d4e21952-625d-48b2-895d-42c1489aff0f.jpg)
似乎自带汉化

**Comment by mamaruo** [comment]
我已查看过，en 比 zh 多了三十多行，这才来发 issue 的
