### ISSUE TITLE
[其他]：自动创建成对翻译文本以供审查

### ISSUE THREAD

**Issue by mamaruo** [CFPAOrg/Minecraft-Mod-Language-Package#1602]
### 详细信息

在现在的 GitHub 网页[审查](https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#about-pull-request-reviews)中，我没有找到一种能直接查看双语对照的方法来审查翻译。

edit: 在 PR 按下句点键自动进入 VSC 在线版的 review 界面，但做不到文件对比 / 同步滚动。
edit2：在 Web VSC 的 explorer 选项卡中可以打开对比，同步滚动。

而在本地编辑器中提交评论、更改请求虽有[插件](https://github.com/microsoft/vscode-pull-request-github)，仍有诸多不便，如 suggest change 无法自动填充等。

我的想法是在提交 PR 时，通过某种方式（GitHub Actions？）自动创建一个双语对照文件（格式 CSV？），所有审查、更改都在这个文件上进行，在 merge 时自动把该文件更新回 json。

**Comment by n0099** [comment]
按照您的建议我能想出来的流程是：
写个程序挂在现在的@cfpabot 账号名下监听github hooks的new pr提交事件，然后再对该pr的forked repo的main branch的new commit hook进行监听，一旦有commit pushed就自动生成将en_us.lang和zh_cn.lang缝合起来的csv文件，再push到fork repo main branch下（当然这需要pr作者开启了allow edits from maintainer），这样我们在网页review时就能看到缝合的csv文件了

但如果要求后续更改也在该csv上进行那同步更改就有丶麻烦，我认为应该还是让pr作者只修改zh_cn.lang（按照上面说的修改后会自动缝合csv），我们只review csv文件但除了cfpabot之外没有人应该改动它

csv文件应该用tsv（tab分割）甚至ascii 0x00分割而不是`,`分割因为`,`在许多en_us.lang中很常见，写一大堆转义了的`\,`又不利于阅读
