### ISSUE TITLE
注释表达问题及其规范

### ISSUE THREAD

**Issue by mamaruo** [CFPAOrg/Minecraft-Mod-Language-Package#1604]
您可以用不存在的key来表达注释
```suggestion
  "block.supplementaries.hanging_sign_imparius": "Imparius 挂牌",
  "_supplementaries.comment.hanging_sign_imparius": "官中未译"
  "item.supplementaries.sign_post_imparius": "Imparius 路标",
  "_supplementaries.comment.bop": "Biomes O' Plenty"
```
如果支持json5规范就可以直接注释了

_Originally posted by @n0099 in https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1603#discussion_r818929767_

**Comment by n0099** [comment]
用不存在的key来表达注释是之前你们就用了的方式，看起来也没啥问题（不会真有人使用碰撞上这些key吧）

**Comment by Cyl18** [comment]
可以通过打包器自动移除注释

**Comment by n0099** [comment]
> 可以通过打包器自动移除注释

注释应该让其他人也能读到，而不仅限于pr reviewer

**Comment by Cyl18** [comment]
> > 可以通过打包器自动移除注释
> 
> 注释应该让其他人也能读到，而不仅限于pr reviewer

我的意思是打包出来也不会出现语法错误

我建议还是使用惯用的 `"_comment.aaaa.bbbb": ""` 的形式

**Comment by n0099** [comment]
> > > 可以通过打包器自动移除注释
> > 
> > 
> > 注释应该让其他人也能读到，而不仅限于pr reviewer
> 
> 我的意思是打包出来也不会出现语法错误
> 
> 建议还是使用惯用的 `"_comment.aaaa.bbbb": ""` 的形式 库里在用
> 
> 而 `//` `/* */` 在模组里也是有的 如 `cutandcolored` 的官方英文语言文件 ![image](https://user-images.githubusercontent.com/14993992/158306363-ebfa6424-bf22-4419-99a0-d316d429989f.png)
> 
> 不过目前仓库内`formatter`会把这类注释自动删除

formatter是actions里那个打包为资源包的程序？

**Comment by Cyl18** [comment]
> > > > 可以通过打包器自动移除注释
> > > 
> > > 
> > > 注释应该让其他人也能读到，而不仅限于pr reviewer
> > 
> > 
> > 我的意思是打包出来也不会出现语法错误
> > 建议还是使用惯用的 `"_comment.aaaa.bbbb": ""` 的形式 库里在用
> > 而 `//` `/* */` 在模组里也是有的 如 `cutandcolored` 的官方英文语言文件 ![image](https://user-images.githubusercontent.com/14993992/158306363-ebfa6424-bf22-4419-99a0-d316d429989f.png)
> > 不过目前仓库内`formatter`会把这类注释自动删除
> 
> formatter是actions里那个打包为资源包的程序？

packer才是打包为资源包的

**Comment by n0099** [comment]
> > > 不过目前仓库内`formatter`会把这类注释自动删除
> > 
> > 
> > formatter是actions里那个打包为资源包的程序？
> 
> packer才是打包为资源包的

那formatter是在哪一层？

**Comment by Cyl18** [comment]
> > > > 不过目前仓库内`formatter`会把这类注释自动删除
> > > 
> > > 
> > > formatter是actions里那个打包为资源包的程序？
> > 
> > 
> > packer才是打包为资源包的
> 
> 那formatter是在哪一层？

定期格式化 去除JSON注释 语言文件key排序 然后commit

**Comment by n0099** [comment]
> > > > > 不过目前仓库内`formatter`会把这类注释自动删除
> > > > 
> > > > 
> > > > formatter是actions里那个打包为资源包的程序？
> > > 
> > > 
> > > packer才是打包为资源包的
> > 
> > 
> > 那formatter是在哪一层？
> 
> 定期格式化 去除JSON注释 移除文件末换行 语言文件key排序 然后commit

为什么要排序？改变行顺序会让git blame十分困难

**Comment by Cyl18** [comment]
> > > > > > 不过目前仓库内`formatter`会把这类注释自动删除
> > > > > 
> > > > > 
> > > > > formatter是actions里那个打包为资源包的程序？
> > > > 
> > > > 
> > > > packer才是打包为资源包的
> > > 
> > > 
> > > 那formatter是在哪一层？
> > 
> > 
> > 定期格式化 去除JSON注释 移除文件末换行 语言文件key排序 然后commit
> 
> 为什么要排序？改变行顺序会让git blame十分困难

好像没有排序的功能 我在乱说（

**Comment by n0099** [comment]
> > > > > > > 不过目前仓库内`formatter`会把这类注释自动删除
> > > > > > 
> > > > > > 
> > > > > > formatter是actions里那个打包为资源包的程序？
> > > > > 
> > > > > 
> > > > > packer才是打包为资源包的
> > > > 
> > > > 
> > > > 那formatter是在哪一层？
> > > 
> > > 
> > > 定期格式化 去除JSON注释 移除文件末换行 语言文件key排序 然后commit
> > 
> > 
> > 为什么要排序？改变行顺序会让git blame十分困难
> 
> 好像没有排序的功能 我在乱说（

所以这个bot跑在@cfpabot 上？我说之前git blame怎么这bot一堆changes

**Comment by Cyl18** [comment]
> > > > > > > > 不过目前仓库内`formatter`会把这类注释自动删除
> > > > > > > 
> > > > > > > 
> > > > > > > formatter是actions里那个打包为资源包的程序？
> > > > > > 
> > > > > > 
> > > > > > packer才是打包为资源包的
> > > > > 
> > > > > 
> > > > > 那formatter是在哪一层？
> > > > 
> > > > 
> > > > 定期格式化 去除JSON注释 移除文件末换行 语言文件key排序 然后commit
> > > 
> > > 
> > > 为什么要排序？改变行顺序会让git blame十分困难
> > 
> > 
> > 好像没有排序的功能 我在乱说（
> 
> 所以这个bot跑在@CFPABot 上？我说之前git blame怎么这bot一堆changes

是跑在 GitHub actions 上的 和 CFPABot 无关

**Comment by n0099** [comment]
> > > > > > > > > 不过目前仓库内`formatter`会把这类注释自动删除
> > > > > > > > 
> > > > > > > > 
> > > > > > > > formatter是actions里那个打包为资源包的程序？
> > > > > > > 
> > > > > > > 
> > > > > > > packer才是打包为资源包的
> > > > > > 
> > > > > > 
> > > > > > 那formatter是在哪一层？
> > > > > 
> > > > > 
> > > > > 定期格式化 去除JSON注释 移除文件末换行 语言文件key排序 然后commit
> > > > 
> > > > 
> > > > 为什么要排序？改变行顺序会让git blame十分困难
> > > 
> > > 
> > > 好像没有排序的功能 我在乱说（
> > 
> > 
> > 所以这个bot跑在@CFPABot 上？我说之前git blame怎么这bot一堆changes
> 
> 是跑在 GitHub actions 上的 和 CFPABot 无关

actions可以像crontab那样定时执行？

**Comment by Cyl18** [comment]
> > > > > > > > > > 不过目前仓库内`formatter`会把这类注释自动删除
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > formatter是actions里那个打包为资源包的程序？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > packer才是打包为资源包的
> > > > > > > 
> > > > > > > 
> > > > > > > 那formatter是在哪一层？
> > > > > > 
> > > > > > 
> > > > > > 定期格式化 去除JSON注释 移除文件末换行 语言文件key排序 然后commit
> > > > > 
> > > > > 
> > > > > 为什么要排序？改变行顺序会让git blame十分困难
> > > > 
> > > > 
> > > > 好像没有排序的功能 我在乱说（
> > > 
> > > 
> > > 所以这个bot跑在@CFPABot 上？我说之前git blame怎么这bot一堆changes
> > 
> > 
> > 是跑在 GitHub actions 上的 和 CFPABot 无关
> 
> actions可以像crontab那样定时执行？

是的

**Comment by dovisutu** [comment]
其实如果需要的话可以把去注释这一步移到 Packer 里面去（
不过看样子 Formatter 似乎目前无法做到保留注释？虽然这个我没仔细看

还有，回复的连续引用看起来太诡异了......

**Comment by n0099** [comment]
> 还有，回复的连续引用看起来太诡异了......

梦回bbs版聊

**Comment by Cyl18** [comment]
> 其实如果需要的话可以把去注释这一步移到 Packer 里面去（ 不过看样子 Formatter 似乎目前无法做到保留注释？虽然这个我没仔细看
> 
> 还有，回复的连续引用看起来太诡异了......

Formmater可以保留.lang的注释 .json不行

**Comment by TartaricAcid** [comment]
Minecraft 用的是 GSON 库来读取 json 文件的，默认就可以剔除注释（`//` 形式）的

**Comment by n0099** [comment]
> Minecraft 用的是 GSON 库来读取 json 文件的，默认就可以剔除注释（`//` 形式）的

gson支持json5是吧

**Comment by TartaricAcid** [comment]
我最近打算重新爬虫脚本，所有注释规范化必须得考虑了（否则脚本没法更新汉化了）
目前想法比较暴力：
1. 去除所有的 `//` 类型注释
2. 作者用不存在的 key 作为注释：这种问题比较头疼，因为读取 json 时候会把同一 key 的内容合并。我的想法是直接读，重复合并就合并吧，反正不影响游戏内显示就行

**Comment by n0099** [comment]
> 我最近打算重新弄爬虫脚本，所有注释规范化必须得考虑了（否则脚本没法更新汉化了） 目前想法比较暴力：
> 
> 1. 去除所有的 `//` 类型注释
> 2. 作者用不存在的 key 作为注释：这种问题比较头疼，因为读取 json 时候会把同一 key 的内容合并。我的想法是直接读，重复合并就合并吧，反正不影响游戏内显示就行

建议爬虫换支持json5的解析库

**Comment by mamaruo** [comment]
```
  "block.supplementaries.hanging_sign_imparius": "Imparius 挂牌",
  "_comment.mamaruo.block.supplementaries.hanging_sign_imparius": "官中未译",
```

考虑到注释大多是网页上打，用 Bot 生成再好不过了。

@Cyl18 是否能用 Bot 命令实现自动生成这样格式的行？

**Comment by n0099** [comment]
建议`/addcomment 行号 文本`

**Comment by Cactusstudent** [comment]
Bot 已实现，具体格式如下：
/add-comment <part-of-key> <comment> 对中文语言文件添加一行注释，part-of-key 为要添加注释的行的键
