### ISSUE TITLE
翻译请求：Mob Battle Mod 怪物大乱斗 #CFPA-0602

### ISSUE THREAD

**Issue by mamaruo** [CFPAOrg/Minecraft-Mod-Language-Package#1631]
转交自工单 #CFPA-0602
https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod
https://github.com/Flemmli97/MobBattle/
https://www.mcmod.cn/class/1085.html

**Comment by n0099** [comment]
mobbattle-1.18.1-2.4.0-forge.jar里的[en_us.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/8238831/en_us.json.txt)
有54个key

**Comment by n0099** [comment]
repo里已经有了spider抓取的旧版mod的en_us.lang：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main/projects/1.16/assets/mob-battle-mod/mobbattle/lang
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/f250d80c869f9ace5a1fcfc1a32ff64a5bf5b9c6/config/spider/config.json#L664-L665
