### ISSUE TITLE
Avocado：牛油果/鳄梨

### ISSUE THREAD

**Issue by iouter** [CFPAOrg/Minecraft-Mod-Language-Package#1646]
查了一下，有把avocado翻译成牛油果的，也有翻译成鳄梨的。不过这是否需要统一，统一成什么应另行讨论。

_Originally posted by @iouter in https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1644#issuecomment-1066144357_

**Comment by n0099** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1644#issuecomment-1066155525
> 鳄梨/牛油果的使用比例大致为四六开

搜索鳄梨https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/search?q=%E9%B3%84%E6%A2%A8 使用的mod有
binnies-mods, croptopia-fabric, pmp, realword
搜索牛油果https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/search?q=%E7%89%9B%E6%B2%B9%E6%9E%9C 使用的mod有cultural-delights, sushigocrafting, pams-harvestcraft, pams-harvestcraft-2-trees, sushigocrafting
pams

pam's harvestcraft的用户基数很大所以大家应该都已经习惯了游戏里称其为牛油果

**Comment by XiaoXin1113** [comment]
我赞成：`牛油果`
