### ISSUE TITLE
[模组翻译]：格雷科技电力高炉JEI配方中温度显示Format error

### ISSUE THREAD

**Issue by xsun2001** [CFPAOrg/Minecraft-Mod-Language-Package#1655]
### 简体中文资源包信息

1.12 2022-03-14 21:27:42

### 模组英文名

GregTech Community Edition

### 模组版本

1.10.0.546

### 详细信息

![image](https://user-images.githubusercontent.com/14010993/158520805-0dc6d52d-d56c-430b-8b83-08cf1fc5d28b.png)

如图，温度显示Format error

**Comment by iouter** [comment]
汉化是适配最新版gtce的，与旧版gtce不兼容，更新gtce即可解决。

相关lang曾为`gregtech.recipe.blast_furnace_temperature=Temperature: %dK`，现被修改为`gregtech.recipe.blast_furnace_temperature=Temperature: %,dK (%s)`

**Comment by n0099** [comment]
之前在硅岩社区群里讨论过这个问题
这类问题都是由于mod作者增加/修改了format str导致的

https://github.com/GregTechCE/GregTech/commit/e3125aed395ca882ce81ef66e62b65678c82fd50#diff-b95d52cbe09f3b195b3f8d94bf73004fad7c73bdd8ebad1901bce556771204ffR32-R33

**Comment by xsun2001** [comment]
好的，谢谢各位！
