### ISSUE TITLE
[其他]：在仓库中添加 Fabric 模组的翻译存放位置

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#1697]
### 详细信息

目前仓库中已经有很多提交 Fabric 模组翻译的文件，将其和 Forge 模组翻译文件混用并不太合适。

我目前想在再此仓库中创建新的文件夹，专门用来放 Fabric 模组翻译文件，后续逐步完善打包系统，自动汉化更新模组等内容。

**Comment by mamaruo** [comment]
我不是很了解仓库里的路径能对资源包、维护带来什么影响。

比如先前选择加一层“CurseForge项目名称”文件夹时我根本没有在CFPA活跃，也就不知道是怎么回事。

**Comment by mamaruo** [comment]
@baka-gourd 请问对此有什么意见吗

@n0099 类似“重制版”会和原模组使用相同的modid，再套一层以区分它们。

**Comment by baka-gourd** [comment]
> @baka-gourd 请问对此有什么意见吗
> 
> @n0099 类似“重制版”会和原模组使用相同的modid，再套一层以区分它们。

没有

**Comment by n0099** [comment]
有许多mod是靠cf发布文件中release表达forge beta表达fabric来区分版本的，他们的modid和cfid都相同

**Comment by TartaricAcid** [comment]
@SherkeyXD 之前没有区分分支是因为这个仓库是配合 weblate 使用的，所以不好分分支

**Comment by mamaruo** [comment]
> 有许多mod是靠cf发布文件中release表达forge beta表达fabric来区分版本的，他们的modid和cfid都相同

确实如此，当然也有不这样做的。curseforge 的文件本身就有 loader 标签，可以区分 Forge 和 Fabric。

**Comment by n0099** [comment]
> > 有许多mod是靠cf发布文件中release表达forge beta表达fabric来区分版本的，他们的modid和cfid都相同
> 
> 确实如此，当然也有不这样做的。curseforge 的文件本身就有 loader 标签，可以区分 Forge 和 Fabric。

那在cf出loader标签之前上传的呢，或者说mod作者上传时没选这个

**Comment by n0099** [comment]
> > > > 有许多mod是靠cf发布文件中release表达forge beta表达fabric来区分版本的，他们的modid和cfid都相同
> > > 
> > > 
> > > 确实如此，当然也有不这样做的。curseforge 的文件本身就有 loader 标签，可以区分 Forge 和 Fabric。
> > 
> > 
> > 那在cf出loader标签之前上传的呢，或者说mod作者上传时没选这个
> 
> 无所谓了，反正都在一个 CurseForge 页里，如果混在一个主文件夹下是区分不了的。

主要是怕fabric跟forge版本的游戏内容有区别，比如多/少一些物品

**Comment by mamaruo** [comment]
暂时不merge带fabric标签的PR？

**Comment by Cyl18** [comment]
另：有的模组用CurseForgeID区分fabric和forge 如XXX-forge和XXX-fabric，而有的模组直接在一个项目下同时发布 如XXX

**Comment by n0099** [comment]
> 而有的模组直接在一个项目下同时发布 如XXX

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1697#issuecomment-1074908880

**Comment by TartaricAcid** [comment]
前期准备工作都完成了，开搞

**Comment by TartaricAcid** [comment]
okay，所有工作已经全部完成：打包系统，上传系统，标签系统
