### ISSUE TITLE
做个翻译相关资源集合

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#1799]
### 详细信息

就是各种链接合集
### 要放在哪里？
- README.md 里给个链接？
- CONTRIBUTING.md？
- `Minecraft 模组简体中文翻译规范与指南`？
- issue 里？
- 群里？

### 相关内容？
例如：
- Wiki 的译名标准化历史 https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96/%E5%8E%86%E5%8F%B2
- 译名标准化列表
- 百科词典 https://dict.mcmod.cn/
- `Minecraft 模组简体中文翻译规范与指南`
- 学术词典
- Google.com/Baidu.com

---

另外 `Minecraft 模组简体中文翻译规范与指南` 内有 `相关工具` 条目

---
看起来没多少内容 我偏向于丢 README.md/CONTRIBUTING.md

**Comment by mamaruo** [comment]
支持 Readme
另：术语在线，CNKI翻译助手

**Comment by TartaricAcid** [comment]
除了上述的，还可以往网站首页放一份
