### ISSUE TITLE
[模组翻译]：柠檬酸盐骨骼韧化？

### ISSUE THREAD

**Issue by Ironnoob73** [CFPAOrg/Minecraft-Mod-Language-Package#1809]
### 简体中文资源包信息

1.12.2 2022-04-03T17:19:30Z

### 模组英文名

Cyberware

### 模组版本

0.2.11

### 详细信息

"韧骨"被翻译为了"柠檬酸盐骨骼韧化"。

**Comment by mamaruo** [comment]
原文 Citrate Enhancement
ChromaPIE 2 月前修改
我认为没有问题

**Comment by n0099** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1616#issuecomment-1063895683
