### ISSUE TITLE
[模组翻译]：多余的（仅限创造）

### ISSUE THREAD

**Issue by Ironnoob73** [CFPAOrg/Minecraft-Mod-Language-Package#1810]
### 简体中文资源包信息

1.12.2 2022-04-03T17:19:30Z

### 模组英文名

Flan‘s mod

### 模组版本

5.10.0

### 详细信息

”加特林“后出现了多余的“（仅限创造）”

**Comment by mamaruo** [comment]
第57行
`item.minigun.name=Minigun (creative only)`
翻译无误

**Comment by Cyl18** [comment]
> 第57行 `item.minigun.name=Minigun (creative only)` 翻译无误

这不是同一个模组 这行出自franciscofunari
也就是撞Key了 目前暂时对`撞Key`没有解决方法

**Comment by n0099** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/01984a7ea1f5ade6909b253cc3813c82d4c1510a/projects/1.12.2/assets/franciscofunari/medievalcraft/lang/en_us.lang#L57

**Comment by Ironnoob73** [comment]
已向原作者curseforge界面提出反馈，暂未得到回复。
