### ISSUE TITLE
重新审核 #1786

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#1832]
![image](https://user-images.githubusercontent.com/14993992/162889656-df45d80b-20c3-4d58-9c0b-d8b79729e73b.png)

#1786 看起来有很多不相关的模组翻译被删除了

相关PR：#1828

**Comment by n0099** [comment]
支持

**Comment by Cyl18** [comment]
要在恢复文件的同时保留文件历史记录看起来[好麻烦](https://localcoder.org/git-revert-deleted-file-and-preserve-file-history)

**Comment by n0099** [comment]
> 要在恢复文件的同时保留文件历史记录看起来[好麻烦](https://localcoder.org/git-revert-deleted-file-and-preserve-file-history)

建议不管git blame，我blame都是多丶几次或者加-C的

**Comment by mamaruo** [comment]
⑨太急了，建议开启24h block

**Comment by Cyl18** [comment]
@TartaricAcid 
![image](https://user-images.githubusercontent.com/14993992/163697094-289d2c44-57aa-4dcd-98c9-77818998e774.png)
看到 info.json 中有的模组 latestFiles 没有数据，是 CurseForge API 没返回数据，这应该就是被误删的原因
