### ISSUE TITLE
缩进问题及 Formatter 修改

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#1852]
### 详细信息

*低优先级*

目前爬虫与 Formatter 冲突 导致刷了个超长的 [commit](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/bbe42d8fe26ab553960d1e71d90e396fb7a2db80)
爬虫采用 `4空格缩进` Formatter 采用 `2空格缩进`

需要的话可以用 Bot 做到在 PR 的时候就统一格式（自动或手动发命令）

还有的问题
- Formatter 会把英文语言文件 .lang 的 `//` 转为 `#` 导致每次爬虫都会更新
- 模组作者乱写（如直接多行`""`）的解决方案

相关 issue #1604

**Comment by n0099** [comment]
折中一下，建议直接不缩进，反正没有嵌套的json都是一层深度的

**Comment by mamaruo** [comment]
编辑器的 formatter 一般都带缩进

**Comment by n0099** [comment]
编辑器可以选2还是4还是tab还是不缩进
建议加个.editorconfig文件来让编辑器自动采用

**Comment by TartaricAcid** [comment]
爬虫的缩进我改成 2 空格了（爬虫还需要改进……）

**Comment by TartaricAcid** [comment]
所以统一按照 2 空格缩进来约束所有的中文文本吧，英文文本保持原样，就不格式化了。目前爬虫也是这个逻辑。

此 Issues 可以 close 了？
