### ISSUE TITLE
[其他]：Uru 乌鲁/雾金

### ISSUE THREAD

**Issue by ZHAY10086** [CFPAOrg/Minecraft-Mod-Language-Package#1863]
翻译 ATM 6 物品的时候发现了 `Uru` 这个金属，在仓库里查了下，发现在 TAIGA 里被翻译为`雾金`。
但我向 ATM 6 的作者问了问，他说 `Uru` 梗的是漫威里的`乌鲁金属`。
不知道是否有更改的必要。

**Comment by n0099** [comment]
https://marvel.fandom.com/wiki/Uru

**Comment by n0099** [comment]
雾金根本搜不到什么，疑似音译

**Comment by LiuQiYu671** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/81440821/164152807-0560b093-55e6-4e25-b4e7-7e93123374f3.png">
是这个罢

**Comment by LiuQiYu671** [comment]
> 雾金根本搜不到什么，疑似音译

<img width="383" alt="image" src="https://user-images.githubusercontent.com/81440821/164153319-3d5b2dcd-beba-4d9e-bc24-a1dbfc7b1efa.png">
出自i18对于TAIGA1.16.5版本的翻译
但是漫威里确实有乌鲁金属
<img width="747" alt="image" src="https://user-images.githubusercontent.com/81440821/164153730-dab3e098-6bd8-48cc-a95e-6ee5aa54287f.png">

**Comment by LiuQiYu671** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/81440821/164153949-32817f94-528f-4650-bca5-97f30138dc09.png">
个人感觉没有更改的必呀，因为漫威的wiki上也翻译成乌鲁

**Comment by ZHAY10086** [comment]
> 个人感觉没有更改的必呀，因为漫威的wiki上也翻译成乌鲁

这里是问要不要从`雾金`改成`乌鲁`啊

**Comment by n0099** [comment]
支持乌鲁

**Comment by mamaruo** [comment]
有没有可能是译者认为 此 Uru 非彼 乌鲁

**Comment by n0099** [comment]
atm6里大量引用漫威梗

**Comment by LiuQiYu671** [comment]
我去把TAIGA里面的雾金改一下吧

**Comment by mamaruo** [comment]
> atm6里大量引用漫威梗

和 TAIGA 关系大吗

**Comment by ZHAY10086** [comment]
> 和 TAIGA 关系大吗

TAIGA 里有同样典出漫威的 Vibranium（振金）

**Comment by n0099** [comment]
atm6里也有vibranium
