### ISSUE TITLE
[模组翻译]：Farming For Blockheads已有官方中文翻译，且与i18n有冲突，建议删除

### ISSUE THREAD

**Issue by AnzhiZhang** [CFPAOrg/Minecraft-Mod-Language-Package#1891]
### 简体中文资源包信息

1.16

### 模组英文名

Farming For Blockheads

### 模组版本

最新版？

### 详细信息

[模组CF链接](https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads)
[官方汉化文件地址](https://github.com/ModdingForBlockheads/FarmingForBlockheads/blob/1.16.x/src/main/resources/assets/farmingforblockheads/lang/zh_cn.json)
[i18n汉化文件地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.16/assets/farming-for-blockheads/farmingforblockheads/lang/zh_cn.json)
## 截图
![image](https://user-images.githubusercontent.com/37402126/164913750-64b07beb-7dff-482e-9186-abcbbda7417b.png)
![image](https://user-images.githubusercontent.com/37402126/164913754-3632b4d8-381a-4fe3-bac7-bcfbcccd40a8.png)

**Comment by n0099** [comment]
@Cyl18
