### ISSUE TITLE
[其他]：MCreator 模组的翻译文件应该如何处理？

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#1894]
### 详细信息

已经出现了提交 MCreator 制作的模组的语言文件的 PR，对于 MCreator 制作的模组应该如何处理？

MCreator 是一个 Minecraft 模组制作软件，易于上手且几乎不需要任何编程知识。但是通过它制作的模组功能简单，虽然偶有精品，但是绝大多数 MCreator 模组质量依旧低下。

是否应当不接收 MCreator 制作的模组？

**Comment by n0099** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1836#issuecomment-1107733588

我的评价是https://gist.github.com/thebrightspark/6d2bc3ca824fe2198b8979b070c4c943

**Comment by mamaruo** [comment]
> [#1836 (comment)](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1836#issuecomment-1107733588)
> 
> 我的评价是https://gist.github.com/thebrightspark/6d2bc3ca824fe2198b8979b070c4c943

Why MCreator Sucks 中文翻译：https://blog.sxjeru.top/post/Why-MCreator-Sucks/

**Comment by AnzhiZhang** [comment]
是否有可能给MCR提建议做好lang排序，并且做好独立id工作？

**Comment by n0099** [comment]
建议`vimdiff <(sort -n en_us.lang) <(sort -n zh_cn.lang)`
快进到https://github.com/Wilfred/difftastic

**Comment by Cyl18** [comment]
现在的处理方案：给 Key 排序然后常规操作

**Comment by mamaruo** [comment]
@Cyl18 的机器人已经可以为语言文件排序。

此 issue 差不多可以关了？

**Comment by n0099** [comment]
核心问题是
> 是否应当不接收 MCreator 制作的模组
