### ISSUE TITLE
[bug]：1.18 资源包连着的全角省略号在游戏内变成乱码

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [CFPAOrg/Minecraft-Mod-Language-Package#1908]
### 详细信息

连着的全角省略号`……`在生成资源包后会变成`\ue908\ue909`，游戏内乱码，单独的一个省略号字符`…`游戏内显示无异常。
项目仓库那边，这种连着的全角省略号`……`完全正常。
![2022-04-29_10 11 42](https://user-images.githubusercontent.com/37864486/165875469-0ed93466-22f2-4b78-a85f-b3c95f8c0dbc.png)

**Comment by Cyl18** [comment]
相关文件：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/config/fontmap.txt

**Comment by mc-kaishixiaxue** [comment]
已确认是Modern UI模组的自定义字体引发的乱码。
