### ISSUE TITLE
[其他]：请求合作翻译1.16.5的 Yggdrasil 和 NoCube's Sea Dwellers模组

### ISSUE THREAD

**Issue by YhaoMin365** [CFPAOrg/Minecraft-Mod-Language-Package#1922]
### 详细信息

请求大佬合作翻译两款模组，十分感谢！
因为个人时间不足和英语水平限制，请求大佬和我合作翻译这两款模组，有意者请留言，感谢！

CurseForge：
[世界树 Yggdrasil](https://www.curseforge.com/minecraft/mc-mods/yggdrasil)
[海底居民 NoCube's Sea Dwellers](https://www.curseforge.com/minecraft/mc-mods/NoCubes-Sea-Dwellers)

**Comment by Annijang** [comment]
翻译难道不是自己做完之后上传到这里么？谁跟你说的是来这里让别人给你翻译的=-=

**Comment by YhaoMin365** [comment]
> 翻译难道不是自己做完之后上传到这里么？谁跟你说的是来这里让别人给你翻译的=-=

是的，一般在时间充裕的情况下且翻译词条较少的时候我会这样做，但是世界树的词条太多了，我无法一个人准确翻译词条内容。

**Comment by Annijang** [comment]
> > 比方说自己做完之后上传到这里么？
> 
> 是的，一般情况下，我无法在一个时间段内将字条的字条充值。

你可以说请求一起翻译，虽然漏了几个字但是表达的意思就会完全不一样，从一起翻译变成命令别人给你翻译，这是两个截然相反的意思。

**Comment by AnzhiZhang** [comment]
建议发布悬赏，如果是想要合作，可以把 `请求大佬对这两款模组进行翻译` 改为 `请求大佬与我合作对这两款模组进行翻译`

**Comment by mamaruo** [comment]
推荐个东西，可能适合这项工作。
[Visual Studio Live Share: 实时代码协作工具](https://visualstudio.microsoft.com/zh-hans/services/live-share/)

**Comment by n0099** [comment]
这也能吵？

**Comment by n0099** [comment]
> 翻译难道不是自己做完之后上传到这里么？谁跟你说的是来这里让别人给你翻译的=-=

#1631
