### ISSUE TITLE
[其他]：Armor的翻译问题

### ISSUE THREAD

**Issue by AnzhiZhang** [CFPAOrg/Minecraft-Mod-Language-Package#1969]
### 详细信息

原版将Armor这个词既作为盔甲（可穿戴的衣服）的意思来使用，也作为盔甲（增加的保护效果量化）的意思来使用
![%1K$61BD~~DVNM2U69$JU_G](https://user-images.githubusercontent.com/37402126/167282096-a1710898-0fff-4500-b3c3-89bbfb81c328.png)
在 MC 维基中，相关页面有 [盔甲](https://minecraft.fandom.com/zh/wiki/%E7%9B%94%E7%94%B2?variant=zh)、[马铠](https://minecraft.fandom.com/zh/wiki/%E9%A9%AC%E9%93%A0)、[盔甲机制](https://minecraft.fandom.com/zh/wiki/%E7%9B%94%E7%94%B2%E6%9C%BA%E5%88%B6)，采用了 `护甲值` 的表述

**Comment by AnzhiZhang** [comment]
相关PR: #1916

**Comment by n0099** [comment]
mcwiki的护甲值是以前的用法，为了消歧义

**Comment by AnzhiZhang** [comment]
我们这边统一了的话，是不是可以去把原版改了

> 相关PR: #1916

这里用的还是 `护甲值`

**Comment by n0099** [comment]
疑似纳夸达-HSLA事件重演

**Comment by mamaruo** [comment]
在@Rinko1231 的提醒下，原版译者已作出更改，把tooltips中的`+1 盔甲`改为`+1 盔护甲值`。

![image](https://user-images.githubusercontent.com/37480168/167888707-58df0182-543d-40e7-b7b8-00299ed4fd35.png)

由于原版Minecraft同时维护三个大版本翻译的机制（[点此](https://launchermeta.mojang.com/mc/game/version_manifest.json)查看各版本语言文件最后更新日期），更改将被应用在最早1.17的原版游戏中。所以本库里的1.18翻译将严格要求使用“护甲值”。

鉴于早先清秋等人已把部分1.16或1.12的armor统一为“护甲值”，我也推荐之后的1.16或1.12翻译新建案使用“护甲值”。
