### ISSUE TITLE
[其他]：Pr Packer 无法直接上传 Zip，必须先解压由 actions/upload-artifact 上传，耗时过长

### ISSUE THREAD

**Issue by AnzhiZhang** [CFPAOrg/Minecraft-Mod-Language-Package#1971]
### 详细信息

相关 [Workflow](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/.github/workflows/pr-packer.yml)

问题简要描述：https://github.community/t/feature-request-download-zip-artefacts-as-zip-not-zip-zip/17580/4
开发团队 2019 年说他们会解决这个问题，目前还没解决 actions/upload-artifact#39

等更新修复了也许这边可以更新一下？

**Comment by Cyl18** [comment]
确实没有办法，因为本来是zip内套zip就很不方便，于是我改成了先解压再上传
可能的解决方法是我拿我服务器打包，不过现在这样能用，就这样吧

**Comment by n0099** [comment]
建议 直接用cyl18a的服务器打包

**Comment by AnzhiZhang** [comment]
> 建议 直接用cyl18a的服务器打包

打包了也不能传到 Action 的 Artifact，会二次打包，除非存在服务器

**Comment by Cyl18** [comment]
> > 建议 直接用cyl18a的服务器打包
> 
> 打包了也不能传到 Action 的 Artifact，会二次打包，除非存在服务器

可以不传到 Action 的 Artifact 呀

> 除非存在服务器

n0099：建议 直接用cyl18a的**服务器**打包

另外目前 bot 可以直接列出所有的 Artifact 了
![image](https://user-images.githubusercontent.com/14993992/167522077-fb4d4983-ce44-4bee-a992-e64dc671e313.png)

**Comment by Cyl18** [comment]
> > 只打包变动的文件
> 
> `zip -u`

![image](https://user-images.githubusercontent.com/14993992/167525212-7636a9b7-6d88-4be9-8f36-6626365c3864.png)
问题不在于更新那个 zip，问题是 GitHub Actions 不能直接传 zip，传 zip 会 zip 内套一个 zip，打包本身是很快的

**Comment by Cyl18** [comment]
先这样了

**Comment by AnzhiZhang** [comment]
本来打算做个记录，等官方修复了再改，先这样吧
