### ISSUE TITLE
[其他]：建议定期移工单

### ISSUE THREAD

**Issue by Wulian233** [CFPAOrg/Minecraft-Mod-Language-Package#2039]
### 详细信息

建议一个星期等定期移动工单，辛苦了

**Comment by n0099** [comment]
@Cyl18 之前写了个手动按照工单格式快速创建pr的c#桌面端wpf程序

**Comment by mamaruo** [comment]
[s]建议切断工单提交渠道[/s]很多疑问得问译文作者才知道，虽然工单回复给了PR链接，提到可以subscribe来跟进，但没几个这么做的。留我们模组没玩过，游戏没开过的reviewer自娱自乐。

**Comment by n0099** [comment]
留我们模组没玩过，游戏没开过的reviewer自娱自乐。
