### ISSUE TITLE
[其他]：版权问题讨论

### ISSUE THREAD

**Issue by AnzhiZhang** [CFPAOrg/Minecraft-Mod-Language-Package#2053]
### 详细信息

补充内容视情况整理到词条中

## 法律基础

基于以下理由，有关著作权问题建议参考 [世界知识产权组织（WIPO）](https://www.wipo.int/portal/zh/) 的 《世界知识产权组织版权条约》

1. 平台和国内无关
2. 协议不太兼容著作权法
3. 我们有完整的国际化交流能力且愿意与国际接轨

## 主要矛盾

1. 没有完整的组织授权流程和权威性，CFPA 管理众多，目前仅能个人发表态度，没有权威流程可以以组织身份授权；
2. CFPA 无权将翻译文本授权任何自然人或组织，因为翻译作者将翻译文本以 [CC Attribution-NonCommercial-ShareAlike 4.0 International](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/LICENSE) 提交给 CFPA，CFPA 只能以相同协议发布；

这条存疑，CC 协议未查询关于翻译的规定；《著作权法》规定 `第十三条　改编、翻译、注释、整理已有作品而产生的作品，其著作权由改编、翻译、注释、整理人享有，但行使著作权时不得侵犯原作品的著作权。`；《世界知识产权组织版权条约》的相关规定也未查询。
> 3. 部分作者的原文可能闭源或不允许翻译，而允许翻译的需要标准的**授权**或**保存来自开源协议的授权**方式以避免可能存在的纠纷（#1977）

### Construction Wand

在 https://github.com/Theta-Dev/ConstructionWand/issues/53 中， @chindev2012 发出来一个中文翻译并请求添加。多亏作者找到原翻译仓库并在 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/discussions/2042 中询问，否则可能会造成多达 6 名翻译作者未署名且错误地署名 @chindev2012。

 Construction Wand 是由 MIT 协议发布的，如 [上文](#主要矛盾) 所述，CFPA 无权授权给这名作者以 MIT 协议发布模组的中文翻译，且对于中文翻译是否符合 MIT 协议存疑。如果没有原始作者授权，分享这个翻译到原作者只有一种方式：作者单独对这个文件使用 CC 协议。

## 相关 Issues

- #1977
- #1972
- #1904
- #1997
- #2057

**Comment by AnzhiZhang** [comment]
这是一个可以有效解决接受翻译版权问题的方案：[github - Validity of agreement to Copyright/CLA via Pull Request merging with agreement text - Open Source Stack Exchange](https://opensource.stackexchange.com/questions/10551/validity-of-agreement-to-copyright-cla-via-pull-request-merging-with-agreement-t)
在提交 PR 的确认部分增加以下声明：
```text
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the [CFPAOrg](https://github.com/CFPAOrg) organization has the copyright to use and modify my contribution under the [CC-BY-NC-SA](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/LICENSE) License for perpetuity.
```

译文
```text
通过提交此 PR，我声明我有权放弃相关贡献的著作权和其它有关权利，并同意放弃所有可放弃的著作权和其它有关权利。我声明永久将著作权和其它有关权利转让给 [CFPAOrg](https://github.com/CFPAOrg)，该组织有权按照 [CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) 协议使用或修改我的贡献。
```

**Comment by n0099** [comment]
建议学习oracle m$ 非死不可等带企业要求pr提交者同意他们的协议（主要内容是放弃pr代码的所有权）

**Comment by AnzhiZhang** [comment]
没人管我先关了，不想放在issue列表里占地方
