### ISSUE TITLE
[其他]：建议将1.18 Forge汉化资源包分成两份用以区分

### ISSUE THREAD

**Issue by Cactusstudent** [CFPAOrg/Minecraft-Mod-Language-Package#2094]
### 详细信息

理由：
1、Minecraft 1.18.1 与 Minecraft 1.18.2 之间存在较大的差异，例如`标签（Tag）`
2、因为Minecraft版本的更新，部分模组的语言文件出现较大变动，例如`匠魂3（Tinkers' Construct 3）`
3、汉化包过于臃肿。究其原因是部分模组开发只停留在Minecraft 1.18.1，而部分模组只在Minecraft 1.18.2开发。而这样使得原`Minecraft-Mod-Language-Package-1.18`体积较大，加载速度慢。
4、Fabric版本汉化资源包诉求同上

**Comment by Cactusstudent** [comment]
虽然1.18.2之后会是主流版本，但我还是提这么个建议

**Comment by mamaruo** [comment]
其一 1.18.x 的自动汉化更新模组没有区分
其二 1.18.1 拆分后恐无人维护
其三 `1.18.2之后会是主流版本`
