### ISSUE TITLE
[其他]：无法在 Release 页便捷地下载到所有版本的资源包

### ISSUE THREAD

**Issue by mamaruo** [CFPAOrg/Minecraft-Mod-Language-Package#2116]
#### 现状

Release 中只会包含有变动的版本。

#### 问题

如果某个版本长期没有变动，将很难找到包含它的那个 Release。

#### 可能的解决方案

每次发布都包含所有版本的资源包，并在 Release Description 中包含变动说明指出该 Release 涉及的版本。

**Comment by Cyl18** [comment]
我也觉得，我之前也想过这个问题，后来觉得i18n会自动更新…

**Comment by mamaruo** [comment]
> 我也觉得，我之前也想过这个问题，后来觉得i18n会自动更新…

1.18 Fabric 现在还没有模组，在近期也应该不会有

**Comment by mamaruo** [comment]
在经历了 @TartaricAcid 的 9c7c1da5ee2a656ca5ef37a220de04d6ecb9986e、22d599ef910e542512c716d6ec6809a84c553aa8 之后，此问题重现。

**Comment by qznfbnj** [comment]
> 在经历了 @TartaricAcid 的[22d599e](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/22d599ef910e542512c716d6ec6809a84c553aa8)、[9c7c1da](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/9c7c1da5ee2a656ca5ef37a220de04d6ecb9986e)之后，此问题重现。

他又改回去了（bushi）

**Comment by qznfbnj** [comment]
> 在经历了 @TartaricAcid 的[22d599e](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/22d599ef910e542512c716d6ec6809a84c553aa8)、[9c7c1da](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/9c7c1da5ee2a656ca5ef37a220de04d6ecb9986e)之后，此问题重现。

好家伙

**Comment by djkcyl** [comment]
建议为 Release 增加 Tag

**Comment by mamaruo** [comment]
已在 https://github.com/CFPAOrg/cfpaorg.github.io/pull/313 实现[官网](https://cfpa.site/)下载资源包
