### ISSUE TITLE
[其他]：关于匠魂3（1.16.5、1.18.1、1.18.2）生物“entity.tconstruct.earth_slime”的名称

### ISSUE THREAD

**Issue by Cactusstudent** [CFPAOrg/Minecraft-Mod-Language-Package#2118]
### 详细信息

其实这只是一个key的问题，但是由于匠魂3（以下简称TiC3）1.18.1及以上版本的发布，这个问题值得再次讨论。
原文：`"entity.tconstruct.earth_slime": "Slime",`_（出自TiC3官方）_
译文：`"entity.tconstruct.earth_slime": "史莱姆",`_（出自CFPA仓库 [HaloSense等五人译]）_
_本次讨论围绕模组版本为 **Tinker's Construct 3.3.4.335 for 1.16.5** **（部分涉及TiC3 1.18.1及以上的内容）**_ 
### （1）关于en_us：
其实本身原文表述就出现了失误，冒号前明显提到了**earth_slime**，而冒号后却只写了**Slime**。
### （2）1.16.5版本的TiC3：
（不考虑1.18.1及之后版本的语言文件变动）正常情况下，其实到这里就可以了，只需要简单翻译为`史莱姆`就可以了。（下图语出HaloSense）
![image](https://user-images.githubusercontent.com/97865546/174600455-2069b8ab-0329-42ca-a1bf-f491b7056c78.png)
### （3）TiC3 1.16.5+语言文件：
1.18.1与1.18.2语言文件对此进行了更改（像是下面这样）
原文：`"entity.tconstruct.earth_slime": "Earth Slime",`（出自TiC3官方）
译文：`"entity.tconstruct.earth_slime": "大地史莱姆",`（HaloSense等多人汉化的，未正式发布的1.18.2汉化）
### （4）我的观点
其实在两个版本之中，无论是所谓的`"entity.tconstruct.earth_slime"`还是Minecraft的`Slime`，长相其实完全相同。（如下图，截自TiC3 1.18.2）（左侧为原版史莱姆，右侧为TiC3的earth_slime）**（完全没区别好吧）**
![image](https://user-images.githubusercontent.com/97865546/174603212-28deaf69-da73-499f-9ab0-ff1737c35670.png)
**遵循原文在这里没必要，希望能讨论出个好结果。**

**Comment by HaloSense** [comment]
其实我的意见就是：如果原文有问题，那么遵循原文。先不说原文如此是有意为之还是单纯的typo，至少100%遵循原文，假设出了什么问题，问题的根源也不会在翻译人员这里。搞明白出了什么问题是作为玩家的本能，但是遵循原文并准确传达原文的意思是作为译者的本职。

**Comment by Cactusstudent** [comment]
> 其实我的意见就是：如果原文有问题，那么遵循原文。先不说原文如此是有意为之还是单纯的typo，至少100%遵循原文，就算出了什么问题，问题的根源也不会在翻译人员这里。搞明白出了什么问题是作为玩家的本能，但是遵循原文并准确传达原文的意思是作为译者的本职。

这估计是目前来看的最优解了

**Comment by Cyl18** [comment]
翻译不能看Key，得看内容

**Comment by HaloSense** [comment]
> 或许我们想复杂了？也许只遵循原文就OK？但是确实是这么个意思

别想着整什么乌七八糟的东西了就，原文咋写的咱就咋翻译，完事

**Comment by Cactusstudent** [comment]
那行了，完事了，我可以close了

**Comment by n0099** [comment]
建议地球史莱姆（迫真）
