### ISSUE TITLE
关于译名标准化

### ISSUE THREAD

**Issue by RCqaq** [CFPAOrg/Minecraft-Mod-Language-Package#2124]
本人最近翻译的时候遇到不少**译名标准化**的问题，因此本着推动翻译**高质量**发展的目的，在此探讨**可能的解决方案**。

本人的想法是编写一份可供所有翻译者查阅的标准译名辞典，对常见术语的译名标准化：
- 涉及科技的常见术语如 `machine` `module` `capacity` `Mk.` 等
- 涉及物流的常见术语如 `insert/extract` `pull/push` `pipe/tube` `filter` 等
- 涉及魔法的常见术语如 `mana` `cast` `spell` `tome` 等
- 还有一些通用的术语如 `augment` `inventory` `slot` `tick` 等

因语境不同而导致译名不同或因中英文习惯不同导致翻译生硬的这类情况需要**特别关注**。
因历史遗留问题造成的翻译不统一需要**关注**。
辞典的维护模式**有待商榷**。

我认为此事需要大家共同的努力。

**Comment by RCqaq** [comment]
#2058
#2051
#2047

**Comment by n0099** [comment]
可以使用@cyl18a 新做的/diff命令

**Comment by RCqaq** [comment]
> 可以使用@cyl18a 新做的/diff命令

可以公开查看、合作编辑吗。另外我的意思不只是review的时候用，还需要对有争议的译名进行探讨以求统一，以及提供解释、可能得一词多义和对应的情景。

**Comment by mamaruo** [comment]
前辈早在2017年就已提出了模组译名标准化的构想并实践了：https://github.com/Krasjet/Mod-Translation-Styleguide/blob/master/glossary.md

但由于各种原因已停止维护。

Weblate 有术语表功能，前辈们已经积累了一些

我们有意向维护一份新的术语表，欢迎PR，https://github.com/CFPAOrg/Glossary

**Comment by n0099** [comment]
> 可以公开查看、合作编辑吗

对照表在cyl18a的bot源码里 https://github.com/Cyl18/CFPABot/commit/31c3842b517a34da06156da94835b96a2af7ce74#diff-b5dad87da396d37988515825a56896232e742d1d32f7a7eac1bbd44ec5d27fbe ，您可以给他pr
我的建议是用git submodule来把这个json表拆成独立repo

**Comment by Cyl18** [comment]
> > 可以公开查看、合作编辑吗
> 
> 对照表在cyl18a的bot源码里 [Cyl18/CFPABot@31c3842#diff-b5dad87da396d37988515825a56896232e742d1d32f7a7eac1bbd44ec5d27fbe](https://github.com/Cyl18/CFPABot/commit/31c3842b517a34da06156da94835b96a2af7ce74#diff-b5dad87da396d37988515825a56896232e742d1d32f7a7eac1bbd44ec5d27fbe) ，您可以给他pr 我的建议是用git submodule来把这个json表拆成独立repo

这个json的来源是https://github.com/CFPAOrg/Glossary/blob/main/Minecraft%20Terms%201.18.2.csv

**Comment by RCqaq** [comment]
> 其实还是那个问题 GitHub 文件编辑对于语言类处理起来太麻烦了

GitHub上那个wiki可以利用吗
最好是做一份便于一般翻译者查阅、参照的类似于词典的文本（和术语表同步更新）

**Comment by mamaruo** [comment]
需要一种同时使人类可读与机器可读的转换机制，并能自动化。

**Comment by n0099** [comment]
如果用csv存建议加空格对齐,这样更像是表格
