### ISSUE TITLE
rebornstorage 翻译问题

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/Minecraft-Mod-Language-Package#2125]
没对呀
- 是否需要和AE统一译名
- `16384k存储元件` `16384K流体存储元件` K大小写不统一

_Originally posted by @Cyl18 in https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2122#issuecomment-1165926355_

**Comment by n0099** [comment]
> 是否需要和AE统一译名

这是rs附属不是ae附属

**Comment by ArgonCrystal** [comment]
> 没对呀
> 
> * 是否需要和AE统一译名
> * `16384k存储元件` `16384K流体存储元件`K大小写不统一
> 
> _最初由 @Cyl18 在 [#2122 中发布 （评论）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2122#issuecomment-1165926355)_

你可以查看英语文本，英语文本就是没统一的，只能说遵循原文。

**Comment by mamaruo** [comment]
我看这个PR的时候注意到了，确实是原文写错
