### ISSUE TITLE
[其他]：对最近一周以来本人对奥利金德（Origind）成员的无端造谣指控以及尝试将其与纳夸达事件挂钩的行径的致歉函

### ISSUE THREAD

**Issue by n0099** [CFPAOrg/Minecraft-Mod-Language-Package#2158]
### 详细信息

我（黄灵梦）基于@LasmGratel （下称LG）于7-4 21:31在硅岩社区群提出的严重关切，对本人近期散播的以下言论进行道歉：

1. **在硅岩社区群将Origind成员@780712 称作“奥利金德皇帝LG神”**
2. **长期以来在四叶小群、硅岩社区及CFPA群将同为Origind成员的本项目Collaborator @Cyl18 指责为“受LG指使的奥利金德驻CFPA间谍”并将我与他并列（同为间谍）**

而我之所以发表上述暴论的根本原因是，自2-16本人经由Cyl18提醒、参与纳夸达事件及随后组建的硅岩社区，并通过943提拔的Cyl18邀请我加入本项目Collaborator以来，我心目一直持有这样一种阴谋论：

> 硅岩社区是由Origind主要成员LG通过联络100余位mcmod圈老人而召集来的组织，LG尝试通过其对CFPA成员修改既有硅岩译名的决定进行施压，并在施压成功后利用943同意对CFPA成员进行换血的机会将Origind成员纳入CFPA，从而支持LG正在开发的下一代翻译mod

而现在看来上述阴谋论的逻辑链不堪一击：

- 硅岩社区主群及各个分群并非是由LG创立，而是Azazel、Gyrfalcon等人创建，群成员也是早期成员们互相拉人而来，因此并不存在“LG一次性拉完了半个mcmod圈”
- 并非只有LG一个人对CFPA施压，而是当时各路势力、mod玩家和mc百科群的路人们都以硅岩社区群为据点进行施压，即便Origind从未参与过此事件也会有其他许多人参与争论
- 943于2-17 19时在硅岩社区主群内邀请各位成员报名加入CFPAOrg时，包括但不限于Cyl18在内许多硅岩社区群友都被943批量加入了CFPAOrg的Member，由于我当时没有参与群聊故选择了于18号18时私聊Cyl18请求他拉我进repo collaborator，而后在20号943又移除了包括我在内大量硅岩社区群员的权限，数日后我亲自向943申请才重新获得repo collaborator权限。

  在此过程中LG从未与我私下联系过，并且LG在纳夸达事件之前对repo具有写权限（根据其与ChromePIE在CFPA群聊），因此LG没有必要将我和Cyl18“推荐”进CFPA来扩大他的影响力
- 截止2022年7月，我仍未知道LG的下一代翻译mod具体是什么样的。仅凭此前2月在硅岩社区群视奸时注意到了LG与生信人西兔人迺逸夫@Prunoideae 在讨论能否将GT6的物品名前后缀文本复用算法用于自动化翻译常见文本的聊天记录，我就认定LG在谋划比目前本项目更先进的翻译工具链，这明显是武断和缺乏事实依据的

有介于此，我再次对@Cyl18 进行道歉，我们都不过是尝试为mcmod翻译事业添砖加瓦的路人，您加入CFPA后通过开发@CFPA-bot 对方便pr审核者所做出的贡献是有目共睹的，我没必要也不应该对您的这些贡献感到嫉妒，更不应该将您和我都称为“受LG指示的奥利金德间谍”，毕竟我自己都从未接受过LG的任何私下明示或暗示

同时也对我重回CFPA主群后所惹恼的本repo collaborator @Demonese （群名片璀境石）和@Summpot 表达歉意。

早在4月19号时943就由于我一直在主群内高强度阴阳怪气而特地私聊请我退群，7月4号时本repo collaborator @mamaruo 邀请我重回CFPA群，本意是想让我在群内能够了解更多翻译动态，避免发生未经协商的过激行为例如快速merge pr（https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2021#issuecomment-1169651036 ）。但很明显我并未理解mamruo拉我的意图，反而在进群后至21:34 mamruo开启全群禁言前没有任何建设性发言

我已不再认为我作为一位本就是在2-15纳夸达事件时为了凑LG的热闹而加入进来的纯路人引流狗，对CFPA的贵项目乃至整个mcmod中译圈能够提供任何实际性的帮助。

甚至对我个人而言在过去5个月游玩GTNH整合包的过程中也从未使用过kiwi制作的汉化包，体现了我无法理解中英名称是如何/为什么这样对应上的

而由于大多数pr我都只是无脑approve并未详细对比每个key的文本，或者启动游戏进行环境测试，因此在pr审核质量上也远不如此前提拔我的@Cyl18 ，更妄论@mamaruo 同事

因此我将在此辞去本repo collaborator的身份并退出硅岩社区和mcmod翻译圈（如果有这个圈子的话），希望上述各方能够原谅我这么做并请不要以此怨恨我

附件：

<details>
<summary>硅岩社区主群7-2聊天记录：</summary>

![硅岩社区1](https://user-images.githubusercontent.com/13030387/177200179-37067e4f-0ea2-45bb-a2ad-542210b9b5af.png)

![硅岩社区2](https://user-images.githubusercontent.com/13030387/177200182-077c2f9e-33a8-4201-a848-954f2011674f.jpg)

![硅岩社区3](https://user-images.githubusercontent.com/13030387/177200185-527e0e0f-7a75-4000-aa6c-350dc7cc8d64.jpg)

![硅岩社区4](https://user-images.githubusercontent.com/13030387/177200186-0122486b-ebe9-46d1-9837-c8f220424cf5.jpg)

![硅岩社区5](https://user-images.githubusercontent.com/13030387/177200187-c6ca305c-55ad-46db-ab99-e18363aedd23.jpg)

![硅岩社区6](https://user-images.githubusercontent.com/13030387/177200130-99980b8e-7d16-4ac0-b8cc-ea42f5fd9ddf.png)

![硅岩社区7](https://user-images.githubusercontent.com/13030387/177200168-f39fa1d7-3fd2-47ea-af65-5e62f08aedb0.jpg)

![硅岩社区8](https://user-images.githubusercontent.com/13030387/177200172-50ebbf9c-e5ee-4172-882a-268d6a7bc3a0.jpg)

![硅岩社区9](https://user-images.githubusercontent.com/13030387/177200175-0c6a1acd-f942-46e4-b619-37afbe20764d.jpg)

</details>

<details>
<summary>CFPA主群7-4聊天记录：</summary>

![CFPA 1](https://user-images.githubusercontent.com/13030387/177200370-3fa9d86b-9f28-4e75-b6dd-a2a2140dc4cb.jpg)

![CFPA 2](https://user-images.githubusercontent.com/13030387/177200372-366fe3c1-2984-4815-9a68-c149f0be2f3b.jpg)

![CFPA 3](https://user-images.githubusercontent.com/13030387/177200341-11d9c331-e3c2-452a-9ba5-4bdbbc5bab14.jpg)

![CFPA 4](https://user-images.githubusercontent.com/13030387/177200343-ddae73fa-daff-41f5-b901-4904480a632d.jpg)

![CFPA 5](https://user-images.githubusercontent.com/13030387/177200352-9adcb28a-dad9-4eee-9b0c-227f29910280.jpg)

![CFPA 6](https://user-images.githubusercontent.com/13030387/177200356-d70a3f72-cf5d-4bf2-b074-df9446851bcd.jpg)

![CFPA 7](https://user-images.githubusercontent.com/13030387/177200363-a986692d-2948-45c3-ab4b-9d85b5aeff62.jpg)

![CFPA 8](https://user-images.githubusercontent.com/13030387/177200364-ba1e4ede-b9de-46b9-9880-3ba58f7d6c26.png)

</details>

LG于7-4 21时在硅岩社区主群对我下达的最后通牒：
![LG的最后通牒](https://user-images.githubusercontent.com/13030387/177200319-54b28fe9-ac0f-4b76-89ef-a9b13c1b46c8.png)

四叶各方反应：
梨木锐评：
![梨木锐评1](https://user-images.githubusercontent.com/13030387/177200856-0553d69a-97aa-445f-b8bd-d882ea1b49a2.png)
![梨木锐评2](https://user-images.githubusercontent.com/13030387/177200861-d347eaf7-1551-4eb1-a6aa-6023470b58fc.png)

梨木对此感到失望：![梨木失望](https://user-images.githubusercontent.com/13030387/177201100-6509bc1a-4562-4961-b21e-c5d64e48eae4.png)

四叶后启示录对四叶1300人主群被永封及n9在CFPA早有预言：
![四叶启示录](https://user-images.githubusercontent.com/13030387/177201095-5589269f-eeeb-4c0a-9f92-13e20b173fae.png)

湾湾430最高指示：
![430最高指示](https://user-images.githubusercontent.com/13030387/177200862-6d80708b-5389-4121-a3d1-6218268c8d8e.png)

irol锐评：
![irol锐评1](https://user-images.githubusercontent.com/13030387/177200865-ff99bc68-5264-46d5-8daf-af9ae4369847.png)
![irol锐评2](https://user-images.githubusercontent.com/13030387/177200851-c4bc9c0f-30be-4b42-a07c-697dc468f3be.png)
![irol锐评3](https://user-images.githubusercontent.com/13030387/177200866-83bbd6cb-ed1f-4131-af27-4670844818d8.png)

**Comment by Demonese** [comment]
我当时一边校对仓库的 pr 一边水群，没注意到你也是贡献者&审核之一，怒火冲头还以为你是来闹事的。
将你直白地称呼为“贵人”实在是对不起，我当时太生气了。
希望以后还能继续友好地合作审核。

**Comment by n0099** [comment]
> 希望以后还能继续友好地合作审核。

我已不再是本repo collaborator

**Comment by mamaruo** [comment]
我已于2022年7月5日1点50分左右把你移除出Outside Collaborator行列。

我们、Git记录将永远记住你的贡献。感谢一直以来的支持。

**Comment by AnzhiZhang** [comment]
### 《停止清算施压，有效解决历史遗留问题，深化改革促发展》

我不理解“奥利金德（Origind）”，“驻CFPA间谍”等说法的意义，但显然其中有些历史渊源和遗留问题。但显然这些说法是有一定伤害性和分裂性的，会进一步冲击经历了今年纳夸达事件的 CPFA 社区。在社区创始人就酒石酸菌已基本上实质上不参与社区事务且为放权的背景下，本就发展停滞的社区会更加脆弱。

需要意识到，贵社区正处在一个十字路口，未来一段时间将充满风险。在此事（CFPA社区第一届发展与改革高峰论坛 - 2022年7月）中我看到了各种人身攻击和身份政治，例如“间谍”、“贵物”、“大爹”、“您为何不去投靠chromapie”、“前朝元老”、“我觉得你适合跟着派哥”。我对此表示坚决反对与强烈谴责，本就是同一目标的同志们，不共同建设共同的事业和伟大的理想，却要给别人打上标签看看是不是真的同志，不断清理真正做了工作的人。

n0099 于今年由于说话方式问题被劝退离开了群，现在经 mamarou 邀请重回群聊，但仍然可以看到一些说话方式上的问题，并没有收敛投入到工作中去，这是十分遗憾的，也让 mamarou 顶着压力邀请失去了意义。但其他人应该对 n0099 的发言多一些理解，我们不应当对他太过于苛刻了，要看到这些发言是有历史经纬的，被迫离开群失去了大量信息的同步，有一些情绪是正常的，应当予以疏导和帮助，使 n0099 能够尽快改正问题投入到工作中，而不是下最后通牒逼迫道歉承担责任。

我看到 n0099 在 CFPA 社区的贡献是很大的，并不像本人所说的无脑 approve，虽然在审核上并没有其它审核员严格和细致，但仍然在合理的风格不同的框架内。有活力的社区需要不同风格的人，能够快速通过对于翻译快速更新覆盖和鼓励译者是十分有益的。这样的审核风格并不是无可替代的，且在目前的紧张背景下，快速通过有可能会造成他人对审核的攻击和要求承担责任，n0099 表示退出应当得到理解和接受。

这是一位有着极高社区活跃度的玩家，现在表示要退出硅岩社区和mcmod翻译圈实属遗憾，没有任何同志提出挽留也十分可惜，虽然我本人不希望 n0099 同志离开，但我的身份显然不适合表达挽留。**我相信做出此抉择一定是经过慎重考量的，人生中还有许多更有意义的事情，离开了这些圈子和这些人或许能够帮助您走得更高更远，出于此因素做出的决定应当得到支持和鼓励。**我看到 n0099 有每日有大量时间在参与社区工作，这有可能如他说的是一种对现实生活的逃避，但是放下一些东西，去忙一忙别的事儿，人生还要继续向前走。上次发现您的时区在欧洲，希望您能与一些社区成员保持联系，维护个人关系，或许在未来能以个人关系在其他地方再次见面，继续合作。

如上文所述，CFPA 的发展正处在一个十字路口，若不彻底改革清理解决历史问题，必将被这些沉重的包袱拖累。我不相信酒石酸菌或任何人有能力和平解决历史遗留问题，那么改革必然伴随着大的动荡，这是走向更加光明伟大的未来的历史必然。我坚定地支持 CFPA 要在国内形成 MC 模组和整合包翻译的垄断地位，甚至做到繁体中文，将台湾省的同胞也覆盖到，这要求社区必须有强力的领导者和清晰的规则，以个人内心喜好为基础的管理方式是不合理且无法长远坚持的。当社区发展到理想的模式和活力后，可以拓宽到俄语、西班牙语、法语和德语，让更多的玩家能够享受到本地化的游戏，甚至各模组只需维护一个语言，其它语言全部在 CFPA 维护，做到国际垄断地位。

最后，我在此呼吁停止对同志们的打压与政治清算，共同切实有效解决问题，建立统一战线，切实有效推进社区发展与改革，必将铸造新的伟大辉煌。

---

**附录 1**

最后，贴一下本人评论文章 [《推动CFPA社区高质量发展》](http://web.archive.org/web/20220607135732/https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2050) 中的两条建议：

> 一是要着力解决今年二月以来的历史遗留问题（http://web.archive.org/web/20220607135732/https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1536）。 要充分认识到作者、译者、玩家、社区之间的关系，深刻理解影响各方立场的核心矛盾，着力建设更大更和谐的MC模组大社区。坚守立场与情怀，译者既不能脱离作者本意，也要注意玩家影响，要能团结一切力量，共创新的伟大辉煌。模组玩家切不可画地为牢，要以积极开放的态度参与建设，书写出属于模组玩家的壮丽诗篇。CFPA社区要努力推动和吸纳更多玩家参与社区工作，铸牢MC模组社区共同体意识是我们开创新局面的必然要求，只有顺应时代变化，按照增进共同性的方向改进工作、共同发展，实现各方面的有机结合，才能把新时代的社区工作做好做细做扎实。有效优化审核工作效率和程序，使译者能感受到贡献是 http://web.archive.org/web/20220607135732/https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1637#issuecomment-1066090492 的，是值得的。
> 二是要不断创新发展，巩固社区基础设施，不断扩大影响力。 要大力弘扬载人航天精神和红船精神，以开天辟地、敢为人先的首创精神，坚定理想、百折不挠的奋斗精神、奉献精神，建设更多更好的基础设施和软件。当前我们已经有[Minecraft-Mods-Translator](http://web.archive.org/web/20220607135732/https://github.com/Maz-T/Minecraft-Mods-Translator) 等一系列优秀软件，但在 公示与讨论平台 （http://web.archive.org/web/20220607135732/https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1566）、周 / 月 / 年报（http://web.archive.org/web/20220607135732/https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1637）、翻译提交平台统一等方面丞需努力。迈入新时代，科技发展需适应文化需要，希望能够推动建设一批高质量社区设施。

**附录 2**

一些网页存档

- [#2050](http://web.archive.org/web/20220607135732/https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2050) (June 7, 2022 13:57:32)
- [#2158](http://web.archive.org/web/20220704185722/https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2158) (July 4, 2022 18:57:22)

**Comment by qznfbnj** [comment]
啊这，背后破事好复杂，还好我只是个兴趣使然的基番润色者

**Comment by AnzhiZhang** [comment]
> 啊这，背后破事好复杂，还好我只是个兴趣使然的机器翻译润色者

![image](https://user-images.githubusercontent.com/37402126/177557447-ce51137c-5657-4a4b-8f59-1f9f36ab5160.png)
是不是暴露了什么东西

**Comment by qznfbnj** [comment]
> 

戳啦，因为基番机翻都在后面嘛！
![S20706-21150833](https://user-images.githubusercontent.com/100760086/177559058-701e3f26-69d0-4e91-80e9-6e16c35c9ef0.png)
