### ISSUE TITLE
[其他]：关于“树叶地毯”的问题

### ISSUE THREAD

**Issue by Kasualix** [CFPAOrg/Minecraft-Mod-Language-Package#2162]
### 详细信息

![image](https://user-images.githubusercontent.com/76616758/177351308-9c0744c3-d1f8-4425-b673-02666b7e8670.png)
平常折腾整合包的时候经常对这种“树叶地毯”有点小纠结（不止environmental，别的很多模组也有这种“树叶地毯”）
这玩意是**自然生成**的，而我觉得“地毯”则是一种人做出来的装饰品，虽然原英文确实是“carpet”，但我个人更倾向翻译成“片”“堆”，“樱桃落叶片”，“樱桃落叶堆”。如下墓园（我自己改的，原文是苔藓地毯，跟“树叶地毯”差不多）
![image](https://user-images.githubusercontent.com/76616758/177352649-d4666774-9ecb-49aa-8d78-56d079f3e9e4.png)
不知道别人有没有对这种“地毯”产生纠结（

**Comment by Cactusstudent** [comment]
我偏向于`树叶堆`，我一般遇到的时候也翻译的是`树叶堆`，特殊情况特殊对待

**Comment by mamaruo** [comment]
我倾向于直译地毯

**Comment by Kasualix** [comment]
get√
