### ISSUE TITLE
[模组翻译]：[建议]添加sodium和iris至forge包, 或者不再分forge与fabric包

### ISSUE THREAD

**Issue by ErrorPower2001** [CFPAOrg/Minecraft-Mod-Language-Package#2165]
### 简体中文资源包信息

1.18.2 2022-07-04, 1.18.2-fabric 2022-07-04

### 模组英文名

Sodium - 钠, Iris Shaders, Rubidium - 铷, Oculus

### 模组版本

sodium-fabric-0.4.1+build.15, Iris-1.2.5, rubidium-0.5.2a, oculus1.2.5

### 详细信息

Rubidium 铷和 Oculus 皆分别是 Sodium 钠和Iris的Forge非官方移植版, 采用了相同的命名空间sodium和iris, 请求将sodium和iris添加到forge分包.
![image](https://user-images.githubusercontent.com/45718918/177617400-7c432298-2204-4aa7-8fe9-ff3de564bbfe.png)

还有其他模组也可能存在移植版, fabric都是基于1.14以后, 资源包格式相同, 不存在冲突问题, 建议不再区分fabric包和forge包, 两个包直接合并发行.

**Comment by qznfbnj** [comment]
尤其是全版本更新之前，找个fabric版本资源包找半天
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2116#issuecomment-1161935542

**Comment by dovisutu** [comment]
目前想到的几个可能的方案：
 - 直接把fabric和forge包合并<br>*问题是这样子那些在fabric和forge之间存在文本差异的不好处理*
 - 复制语言文件（如1.16 -> 1.18的时候）<br>*问题是无法做到同步更新*
 - 想办法共享语言文件<br>*但是两个版本的语言文件出现分歧了怎么办？*
 
最后的选择可能还会是第二个（

**Comment by Cactusstudent** [comment]
最终方案：两边分别提交了语言文件
