### ISSUE TITLE
[其他]：检查单会出现“我不读也同意”的情况

### ISSUE THREAD

**Issue by Cactusstudent** [CFPAOrg/Minecraft-Mod-Language-Package#2265]
### 详细信息

现有检查单内容如下：

- [ ] 我已仔细阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的路径和名称均正确（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#%E6%8F%90%E4%BA%A4%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84%E7%9A%84%E4%BE%8B%E5%AD%90)）；
      - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
      - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ]  刷新 PR 的标签/状态，有需要再点击；

建议只保留`同意协议`以及`刷新PR状态`以及`确认标题格式`三条，其他的没必要，bot会检查的

**Comment by mamaruo** [comment]
#2310 又一例

**Comment by Cactusstudent** [comment]
十分建议把这个issue pin一下……

**Comment by ChuijkYahus** [comment]
合了
