### ISSUE TITLE
[模组翻译]：1.18传送石碑翻译建议

### ISSUE THREAD

**Issue by MightZero** [CFPAOrg/Minecraft-Mod-Language-Package#2292]
### 简体中文资源包信息

1.18 2022-7-26 01:49:03

### 模组英文名

Waystone

### 模组版本

10.1.0

### 详细信息

模组中“传送石碑“的对物品"Portstone"的名称"传送石座"和描述”无法传送至目标“建议改为”单向传送石碑“和”无法作为传送目标“
<img width="429" alt="image" src="https://user-images.githubusercontent.com/78603183/180965964-7874fd8d-57e4-415a-83b3-869a63b97d59.png">

**Comment by lrcno6** [comment]
译名问题给 bug 标签不大合适吧……

**Comment by lrcno6** [comment]
现在的译名已经改为了与您的建议一致
建议关闭issue
