### ISSUE TITLE
[其他]：Tom's Simple Storage模组，原生英文文本出现显示不当的情况，汉化是否应该直接按照其翻译

### ISSUE THREAD

**Issue by wyh0106** [CFPAOrg/Minecraft-Mod-Language-Package#2293]
### 详细信息

这是将语言调成英文时的模组设置界面，该设置说明已经超过单行可以显示的字数，导致无法正常显示。
![image](https://user-images.githubusercontent.com/63447609/180981123-93d10a8b-0ab7-4370-8bc5-54532ad74096.png)
这是中文时的模组设置界面，也无法正常显示。
![image](https://user-images.githubusercontent.com/63447609/180981362-2fe0d559-f054-4674-91b6-43bd476971f1.png)
以下附上提交的翻译链接：#2279

**Comment by mamaruo** [comment]
这种可能作者用的是高分辨率屏幕，没有考虑到这个问题，或者根本遇不到这问题。

我们的工作是翻译，不需要考虑原模组出现的问题。如果有问题的话，直接忠实地保留即可。另一例子是原文文本出现错字错词，翻译时转写成中文错词。

**Comment by wyh0106** [comment]
> 可能作者用的是高分辨率屏幕，没有考虑到这个问题，或者根本遇不到这问题。可以去该模组的仓库发帖。
> 
> 我们的工作是翻译，不需要考虑原模组出现的问题。如果有问题的话，直接忠实地保留即可。另一例子是原文文本出现错字错词，翻译时转写成中文错词。

ok，已提交至该模组仓库
