### ISSUE TITLE
【重大通知】部分翻译项目已经转移至Weblate

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#233]
## 其他地区：https://weblate.exz.me/
![weblate](https://public.lightpic.info/image/7688_5A39301D0.jpg)

**Comment by youyoudeminger** [comment]
emmmmmmmmmmmm

**Comment by RelaperCrystal** [comment]
@youyoudeminger 求你了！**别再Emmmm了**！ [av13482209](https://www.bilibili.com/video/av13482209/) (这，是一个梗)
