### ISSUE TITLE
[其他]：https://cfpa.team 网站证书8月十日已过期，请及时更换 

### ISSUE THREAD

**Issue by PAKingdom** [CFPAOrg/Minecraft-Mod-Language-Package#2359]
### 详细信息

![image](https://user-images.githubusercontent.com/68528277/184538912-6f6aa5f8-578c-4058-88e6-65bd91e33c6e.png)

**Comment by BreakingLead** [comment]
confirmed

**Comment by Cactusstudent** [comment]
没有更换计划，请访问cfpa.site
