### ISSUE TITLE
[其他]：1.18-3.0.2下帕秋莉手册汉化无法加载，问题包括库中已有的手册汉化

### ISSUE THREAD

**Issue by xingmot** [CFPAOrg/Minecraft-Mod-Language-Package#2387]
> EDIT：参见 https://github.com/CFPAOrg/I18nUpdateMod2/issues/46

### 详细信息

测试环境：mc1.18.2 atm7整合包，以及forge40.1.73少量mod单独测试

库中已有热力的帕秋莉手册汉化，实际测试汉化失效。
并且原本有的从资源包加载帕秋莉手册，从而实现小铅笔热加载的功能同样失效。
![C_I$LM7PTI )259D{F__8JI](https://user-images.githubusercontent.com/5901229/186892817-4b7337be-3eed-4487-a6cf-c5b875bcf329.png)
![7~VJU53F0J_%A 3S1B`%119](https://user-images.githubusercontent.com/5901229/186892832-a89f9e84-60db-4eca-b9a7-7ccfe76b9228.png)

**Comment by dovisutu** [comment]
是否同时使用了i18n模组？目前从资源包加载手册的功能是由i18n模组强行实现的
如果有的话......可能是那边的玄学问题，估计得等维护模组的管理员~复活~有时间了再看

可以试试用以前的资源包，看是否异常；或者翻一下有没有报错之类的

**Comment by dovisutu** [comment]
*可能与 CFPAOrg/I18nUpdateMod2#46 有关*

**Comment by xingmot** [comment]
我是atm7包不做修改添加i18n后直接使用，以及单独添加工业先锋以及它的前置，jei等少量辅助mod；测试下来帕秋莉手册的汉化都无效。
都添加了i18n进行测试，你说的帕秋莉手册依赖于i18n，我之前汉化手册的时候就知道了。

**Comment by dovisutu** [comment]
> 我是atm7包不做修改添加i18n后直接使用，以及单独添加工业先锋以及它的前置，jei等少量辅助mod；测试下来帕秋莉手册的汉化都无效。
都添加了i18n进行测试，你说的帕秋莉手册依赖于i18n，我之前汉化手册的时候就知道了。

确定了
我这边之前为其他事做的测试也显示patchouli加载无效，估计就是是i18n模组的问题

**Comment by Cactusstudent** [comment]
现在可以使用 https://www.mcmod.cn/class/8906.html 解决
