### ISSUE TITLE
[其他]：如何解决由于PR堆积而导致的同个模组，多个翻译

### ISSUE THREAD

**Issue by Cactusstudent** [CFPAOrg/Minecraft-Mod-Language-Package#2397]
### 详细信息

要啥详细信息，看这个issue的去看看PR列表就成（bushi）

**Comment by dovisutu** [comment]
建议把提交同模组翻译的拖到一起先出个定版（
~顺便就可以把审核的工作干了~

**Comment by Cactusstudent** [comment]
话说这样做的话……行倒是行，但遇到大量翻译不同的时候……那就不行了，得一个个看，然后选择好点的

**Comment by Cactusstudent** [comment]
还是PR太多了（）

**Comment by Cactusstudent** [comment]
> 还是PR太多了（）

如果抽出20%-35%的key来审核，没啥问题就直接打`ready to merge`的话，我觉得就行了。

**Comment by mamaruo** [comment]
利用diff生成的markdown格式表格，结合 Table Converter 网站，可以快速生成对照表。
