### ISSUE TITLE
[其他]：1.18.2 加载汉化材质包后游戏崩溃

### ISSUE THREAD

**Issue by OcrSu** [CFPAOrg/Minecraft-Mod-Language-Package#2499]
### 详细信息

我的玩家在我的整合包中加载了汉化材质包后游戏崩溃。
但是只有他有这个问题，我们正在努力排查，希望你们有空的话可以一起看一下。
整合包下载地址：https://www.curseforge.com/minecraft/modpacks/lcw/files/4027385
这里是带有崩溃报告的log。
[latest (3).log](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/9776338/latest.3.log)

我已经发现的疑点
![LJ%}V%0)TC6G`@7_6~SJGV3](https://user-images.githubusercontent.com/75876201/195590875-ae8e95dc-5a10-49c7-9282-7863a9317c9b.png)
正常的日志
![Z1X EZ%R%UKR1CEWFZY%32I](https://user-images.githubusercontent.com/75876201/195590913-57603eba-ae1a-4d44-85e1-f573c66bacc8.png)

**Comment by ZekerZhayard** [comment]
```
$ http://downloader1.meitangdehulu.com:22943/Minecraft-Mod-Language-Modpack-1-18.zip -I -L
HTTP/1.1 302 Moved Temporarily
Content-Length: 145
Connection: keep-alive
Content-Type: text/html
Date: Thu, 13 Oct 2022 14:45:15 GMT
Keep-Alive: timeout=4
Location: http://downloader3.meitangdehulu.com:10429/Minecraft-Mod-Language-Modpack-1-18.zip
Proxy-Connection: keep-alive
Server: nginx/1.18.0

HTTP/1.1 404 Not Found
Content-Length: 153
Connection: keep-alive
Content-Type: text/html
Date: Thu, 13 Oct 2022 14:45:16 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Server: nginx/1.18.0
```

**Comment by OcrSu** [comment]
暂时未见复现，所以关闭此issue
