### ISSUE TITLE
“检查单”使用说明 & 错误“检查单”使用情况报告

### ISSUE THREAD

**Issue by Cactusstudent** [CFPAOrg/Minecraft-Mod-Language-Package#2539]
### 详细信息

这只是一个用于提醒的 Issue，如果出现这种情况，只需要简单的在相关 PR 里面 Mention 一下这个 Issue 即可。

检查单正确用法

- [x] #3463
对于此项，你需要认真阅读 CONTRIBUTING.md 以保证不会出现的路径错误等问题。
 - [x] 我已确认外语原文（en_us.json）存在且完整，内容与中文对应；
对于此项，你**需要**确定你的 PR 中包含对应模组的 `en_us.json` 或 `en_us.lang` 或 `en_US.lang` 并确定其在提交时属于本模组的最新版本。若源语言非英语，则需一并提交源语言语言文件。
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
对于此项，你**必须**阅读且同意，若未勾选此项，我们有权拒收你的模组翻译。
- [ ] 刷新 PR 的标签/状态，有需要再点击；
对于此项，在 PR 创建时，你**不需要**点击，只用于特殊情况下刷新 PR 的标签或状态。

cfpa-bot 现已能在 PR 更新时自动使用 `/diff` 命令
对于与翻译相关性不大的 Pull Request 可选择性删去其中的几条或不点击，如 #2522 #2409 
必须选中的检查单条目如上所示
注：本**新版检查单**仅用于#2534之后的PR。#2534之前的 PR 则遵循旧检查单点击前五条即可。

**Comment by ChuijkYahus** [comment]
这两条就标记一下奇妙的没改过的检查单（）

**Comment by ChuijkYahus** [comment]
#2744
