### ISSUE TITLE
语言文件顺序被打乱

### ISSUE THREAD

**Issue by Snownee** [CFPAOrg/Minecraft-Mod-Language-Package#257]
`#PARSE_ESCAPES` 被打乱可能导致某些模组的词条无法正常显示。以及增加了给原项目 PR 的难度。

**Comment by TartaricAcid** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/bf44b3d20c853bd60e9365fc9fb899f866f56eb6 已经被修复

**Comment by RisingInIris2017** [comment]
... 如果“打乱”是指和模组本身的语言文件顺序不同的话，那么对于the Betweenlands模组来说，参考1.12.2的最新版本语言文件[https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12/src/main/resources/assets/thebetweenlands/lang/en_US.lang]()，中文资源包中的语言文件顺序[https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.12.2/project/assets/thebetweenlands/lang/zh_cn.lang]()应该是被打乱了的。
这个bug可能还需要进一步的修复。

**Comment by TartaricAcid** [comment]
@RisingInIris2017 无论是否有 `#PARSE_ESCAPES` 注释，都是通过 key 来寻找 value，从而加载语言文件的，所以你反馈的语言文件顺序被打乱会导致加载出问题是不存在的。
雪尼反馈的是带有  `#PARSE_ESCAPES`  注释的语言文件会以 Java Properties 方式读取。

**Comment by Snownee** [comment]
@TartaricAcid 事实上两者都有。不过鉴于目前的情况，PR 给原作者的必要性似乎减小了不少，所以这个时候只需要先保证可以正常运行即可。
