### ISSUE TITLE
NFINIT Skyblock 整合包求汉化支持

### ISSUE THREAD

**Issue by subtank** [CFPAOrg/Minecraft-Mod-Language-Package#258]
[NFINIT Skyblock](https://minecraft.curseforge.com/projects/nfinit-skyblock)这个整合包个人感觉也是一个很好的1.12.2整合包。求一个汉化支持。

**Comment by TartaricAcid** [comment]
收到，下次更新添加

**Comment by TartaricAcid** [comment]
已经添加 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/0511ab8b40a95d45fb8df9fa94950d89467a0a80

**Comment by TartaricAcid** [comment]
顺便说一句，这整合加的新模组真多啊……一下子多出来60多个……

## 本次新增了 61 个模组：

| 序号 |       模组名称        |                         语言文件地址                         |
| :--: | :-------------------: | :----------------------------------------------------------: |
|  1   |     1_13_features     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/1_13_features/lang) |
|  2   |    advancedcombat     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/advancedcombat/lang) |
|  3   |     ambidextrous      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/ambidextrous/lang) |
|  4   |      bagelsmore       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/bagelsmore/lang) |
|  5   |   betteragriculture   | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/betteragriculture/lang) |
|  6   |     betterrecords     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/betterrecords/lang) |
|  7   |    bettersprinting    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/bettersprinting/lang) |
|  8   |        bitcoin        | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/bitcoin/lang) |
|  9   |     bnbgaminglib      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/bnbgaminglib/lang) |
|  10  |       bullseye        | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/bullseye/lang) |
|  11  |      chattweaks       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/chattweaks/lang) |
|  12  |     colored_water     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/colored_water/lang) |
|  13  |        colytra        | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/colytra/lang) |
|  14  |        conarm         | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/conarm/lang) |
|  15  |     corpsecomplex     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/corpsecomplex/lang) |
|  16  |     cubicvillager     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/cubicvillager/lang) |
|  17  |       cyberware       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/cyberware/lang) |
|  18  |  dimensionalcontrol   | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/dimensionalcontrol/lang) |
|  19  |  dimensionaledibles   | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/dimensionaledibles/lang) |
|  20  |      dismantler       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/dismantler/lang) |
|  21  |   durabilityviewer    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/durabilityviewer/lang) |
|  22  |       endmetals       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/endmetals/lang) |
|  23  |     energysynergy     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/energysynergy/lang) |
|  24  | equivalentenergistics | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/equivalentenergistics/lang) |
|  25  |      exoticbirds      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/exoticbirds/lang) |
|  26  |       ezstorage       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/ezstorage/lang) |
|  27  |          ffs          | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/ffs/lang) |
|  28  |     floatingrails     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/floatingrails/lang) |
|  29  |    fluidconverters    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/fluidconverters/lang) |
|  30  |      fpsreducer       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/fpsreducer/lang) |
|  31  |    globalgamerules    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/globalgamerules/lang) |
|  32  |      hammertime       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/hammertime/lang) |
|  33  |      heartdrops       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/heartdrops/lang) |
|  34  |         iidy          | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/iidy/lang) |
|  35  |       irontanks       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/irontanks/lang) |
|  36  |     magicalwings      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/magicalwings/lang) |
|  37  |     magicfeather      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/magicfeather/lang) |
|  38  |     malisisblocks     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/malisisblocks/lang) |
|  39  |       miniheads       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/miniheads/lang) |
|  40  |    netheroverload     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/netheroverload/lang) |
|  41  |   neverenoughcandy    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/neverenoughcandy/lang) |
|  42  |     pickletweaks      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/pickletweaks/lang) |
|  43  |       quacklib        | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/quacklib/lang) |
|  44  |       rainboaks       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/rainboaks/lang) |
|  45  |    randomutilities    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/randomutilities/lang) |
|  46  |        rewired        | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/rewired/lang) |
|  47  |     rftoolspower      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/rftoolspower/lang) |
|  48  |        rswires        | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/rswires/lang) |
|  49  |        shootit        | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/shootit/lang) |
|  50  |     smarthoppers      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/smarthoppers/lang) |
|  51  |      superminer       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/superminer/lang) |
|  52  |     teslathingies     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/teslathingies/lang) |
|  53  |     theframework      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/theframework/lang) |
|  54  |    totemessentials    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/totemessentials/lang) |
|  55  |        tracer         | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/tracer/lang) |
|  56  |       vampirism       | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/vampirism/lang) |
|  57  |    vampirismguide     | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/vampirismguide/lang) |
|  58  |         vials         | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/vials/lang) |
|  59  |    virtualmachines    | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/virtualmachines/lang) |
|  60  |      voltzengine      | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/voltzengine/lang) |
|  61  |        whoosh         | [URL](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/1.12.2/project/assets/whoosh/lang) |
