### ISSUE TITLE
目前列表内空 en_us.lang 的 Mod

### ISSUE THREAD

**Issue by YueLengM** [CFPAOrg/Minecraft-Mod-Language-Package#260]
- **evilcraftcompat** （ 附带在EvilCraft内的兼容性mod ）

- **torohealthmod** （ ToroHealth Damage Indicators 血量显示mod ）

- **packmode** （ 不认识:/ 看起来与整合有关 ）

- **shulkerbox** （ Advanced Shulkerboxes 一个可以在背包直接打开潜影盒的mod ）

**Comment by TartaricAcid** [comment]
收到反馈，正在处理

**Comment by TartaricAcid** [comment]
已经全部处理完毕
