### ISSUE TITLE
[其他]：关于模组翻译更新的问题

### ISSUE THREAD

**Issue by IceDragonFla** [CFPAOrg/Minecraft-Mod-Language-Package#2602]
### 详细信息

在游玩高版本游戏时发现有模组的汉化不完整， 想要对模组进行汉化的补全，现有如下问题：
1. 如何获取该模组低版本的汉化文件（为了能够省去一部分时间）
2. 获取后如何进行通篇的替换和比对（这个可以自行解决，仅列出，如果有好办法可以告诉我qwq）
3. 通篇翻译完成后如何提交在requests中（希望能够有一个教程什么的，github小白。。但是想为汉化出一份力）
4. 在git上提交以后如何得到反馈，得到反馈并且修改后如何再次提交（重新开一个新的request提交还是在原有的上面修改）

非常感谢大佬的解答 Orz

email : mrcrystalyan@163.com

**Comment by A-Black-Fish** [comment]
获取低版本的汉化文件可能有的文件是lang之类的，高版本通常是json，物品名也会不一样，翻译完成可以通过[https://www.bilibili.com/video/BV1Xi4y1r7S2/](url)来完成提交pr，并非重新开pr来提交（你想让我们血压高吗;w;）
不会可以找@Cactusstudent

**Comment by Cactusstudent** [comment]
> 获取低版本的汉化文件可能有的文件是lang之类的，高版本通常是json，物品名也会不一样，翻译完成可以通过[https://www.bilibili.com/video/BV1Xi4y1r7S2/](url)来完成提交pr，并非重新开pr来提交（你想让我们血压高吗;w;） 不会可以找@Cactusstudent

不止可以找我，CFPAMember和其他本仓库的维护者基本都可以找

**Comment by A-Black-Fish** [comment]
> > 获取低版本的汉化文件可能有的文件是lang之类的，高版本通常是json，物品名也会不一样，翻译完成可以通过[https://www.bilibili.com/video/BV1Xi4y1r7S2/](url)来完成提交pr，并非重新开pr来提交（你想让我们血压高吗;w;） 不会可以找@Cactusstudent
> 
> 不止可以找我，CFPAMember和其他本仓库的维护者基本都可以找

日常在线可能就一个人吧（？）

**Comment by Cactusstudent** [comment]
> > > 获取低版本的汉化文件可能有的文件是lang之类的，高版本通常是json，物品名也会不一样，翻译完成可以通过[https://www.bilibili.com/video/BV1Xi4y1r7S2/](url)来完成提交pr，并非重新开pr来提交（你想让我们血压高吗;w;） 不会可以找@Cactusstudent
> > 
> > 
> > 不止可以找我，CFPAMember和其他本仓库的维护者基本都可以找
> 
> 日常在线可能就一个人吧（？）

有 ChuijkYahus dovisutu Cyl18 几个在线的（）
