### ISSUE TITLE
有些mod是支持1.12全版本的，貌似现在的写法爬不到啊。

### ISSUE THREAD

**Issue by GF47** [CFPAOrg/Minecraft-Mod-Language-Package#270]
如连锁挖矿的新版本是支持1.12大版本的0.38.2，现在的写法只能爬到1.12.2版的0.38.1。
[连锁挖矿](https://minecraft.curseforge.com/projects/veinminer/files?filter-game-version=1738749986%3A628)
虽然貌似这种情况不多的样子。

**Comment by TartaricAcid** [comment]
这个情况属于作者版本书写不严谨导致的，这两个版本翻译区别大么？

**Comment by GF47** [comment]
基本没有区别……我后来大概看了下，支持大版本的一般都是功能稳定的mod，或者一些lib库，没有文字的那种，应该没啥影响。

**Comment by TartaricAcid** [comment]
那这个问题我无法修复，issues 我就关了啊

**Comment by GF47** [comment]
QK
