### ISSUE TITLE
[其他]：关于取消常用字符（省略号）替换的提议

### ISSUE THREAD

**Issue by ZHAY10086** [CFPAOrg/Minecraft-Mod-Language-Package#2721]
### 详细信息

本仓库的打包脚本会将省略号（……）替换为`\ue908\ue909`，辅以自制字体实现更好的视觉效果。
但是在实际使用过程中，当通过 Smooth Font 或 Modern UI （版本号 3.6.0.114 之前）等模组更换游戏内字体时，会导致替换后的省略号无法显示或显示为其他特殊字符。
故在此提议能否去除该项替换，或者采用兼容性更好方法实现？

**Comment by ZHAY10086** [comment]
先前关于该问题的讨论：#2716

**Comment by dovisutu** [comment]
话说你用的什么字体？可不可以看看往私有区塞了多少字形？
（希望没有离谱到塞满，要不然就麻烦了）

**Comment by ZHAY10086** [comment]
不是往私有区里塞了多少字符的问题，如果私有区里没有字符，那`\ue908\ue909`会直接无法显示的，比如这样
![GH04~9ADRVWBCNF@W_%B6$F](https://user-images.githubusercontent.com/34602681/209268876-2e414656-0c91-41e7-a197-fa4b55e01571.png)

**Comment by dovisutu** [comment]
也就是说，挂上smooth font以后不会加载资源包里的那个字体？

**Comment by ZHAY10086** [comment]
是的

**Comment by dovisutu** [comment]
完，这就更麻烦了
干脆直接打两个包，有外挂字体的用未替换包，没有挂上的就用替换包
这样子除了打包/（也许）i18nmod要改一改，以及玩家需要手动改配置，以及服务器占用x2，应该没有太多问题

**Comment by mczph** [comment]
哦对了，smoothfont的话私用区的元素也加载不来，如果能一并处理的话就更好了

**Comment by dovisutu** [comment]
不知道1122/smoothfont是否支持unicode的拓展平面......如果支持的话可以考虑在这种情况下把所有工作推给外挂字体
毕竟如果有完整的外挂字体，省略号和元素符号应该都没有必要修正了

就是i18nmod可能也要改，否则每次还得手动调资源包顺序

**Comment by mczph** [comment]
莫得，原版都不支持（）

**Comment by dovisutu** [comment]
> Emoji表情字符
> 从1.15开始，Minecraft可以支持 UTF-16 序列的表情字符，或 [Unicode辅助平面](https://zh.wikipedia.org/wiki/%E5%A4%9A%E6%96%87%E7%A7%8D%E8%A1%A5%E5%85%85%E5%B9%B3%E9%9D%A2)中的任何字符。
> 
> 为了在字体文件的 char数组中正确读取Emoji表情字符，字符可以：
> 
> 从其UTF-16代码点分为两个UTF-8代码点（代理）；如1F603 -> D83D DE03
> 直接输入
> 第一种方法用于标准字体文件，但两者都同样有效。 要将字符转换为代理对，可以使用以下等式，其中C是十进制中的代码点：
> 
> 高代理（第一个）：((C − 65536) − (C % 1024)) ÷ 1024 + 55296
> 低代理（第二个）：(C % 1024) + 56320

其实mc本身是支持加载拓展平面字体的，但是legacy_unicode加载器并不支持
而自带的那套unifont使用了legacy_unicode加载器，因此就造成了mc不支持拓展区的假象

不过看起来似乎是1.16做出的修改，那1.12估计确实不行

-------

那你们看给使用外挂字体的用户单独提供一个不进行替换的包可不可以
毕竟如果用户挂上了（肯定比mc自带的16px unifont好的）外挂字体，那我们也不用画蛇添足去做兼容性修改；但是对于更多的（？）没使用外挂字体的用户，这种修正还是有保留的价值。

不过可能需要做出不同格式的分发包：
- 省略号：采用\u2026\u2026 / 采用\ue908\ue909
- 元素符号：采用拓展平面字符 / 采用基本平面字符（繁体偏旁的哪个）/采用\ue9xx的替换字符
- ...

（实际上库里面还有全角符号的渲染修改，不过考虑到外挂字体一般会覆盖掉这些修改，应该不用特殊处理）

等到i18nmod+葫芦的服务器+这边的Packer和Uploader重构成支持bsdiff/bspatch以后可能会好用一点，只要按照选择加载相应的patch就好

-------

不过这个功能要等估计有点久。我等会估计会测试一下一些奇怪的东西，如果能在现有情况下保全全体要素（标准字符、16px宽度、等距加点）那也可以暂时用着。

**Comment by mamaruo** [comment]
已于 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/428c11a75214f8f718bf1eddca1945141cf926fa 取消，但不用关闭此 issue，关于这个问题的更多解决方案可以在此提出。

**Comment by Cactusstudent** [comment]
#1908 （相关的Issue）（现在颇有些炒冷饭的感觉）

**Comment by dovisutu** [comment]
现在一想，其实严格来说理想的字体渲染有以下三个要求：
- 严格保持字符位点（不仅是因为外挂字体，还有复制的考量，尽管MC中复制的场合不多）
- 严格保持排版字宽（这也是当初采用特殊字形的重要考量）
- 严格保持标准字形（由于原版的字形不甚合理）

对于省略号而言，唯一同时实现这三个目标的可能性目前看似乎只剩下用更精细的bitmap加载器微调，还不知道能不能成功；如果部分舍弃目标一，则可以利用零宽字符调节；
对于特殊元素符号而言，在1.12没有任何可能达成目标一，在1.15+则可直接用支持拓展平面的bitmap加载器挂载，倒是可以同时满足三个目标；

不过我在想，理论上有没有可能将我们的本地化资源、字形修正等功能分离开来？因为看起来似乎确实有需要分离挂载的场景存在。

~虽然说了这么久，时至今日我还是什么都没有开始做......~

**Comment by MY1L** [comment]
我偶然路过看到你们在讨论这个。的确，统一码迄今没有中文的**2倍全角居中六点**省略号，但用私用区字符充当省略号是极为不妥的，导致的问题这边都有人说过了。
对此在中文字体设计圈有各种暂时解决方法，其中我从2019年用的一个就是用数学的**居中三点**省略号 ⋯ U+22EF MIDLINE HORIZONTAL ELLIPSIS代替，将此符号造成**全角居中三点**是合理的：1.该符号没有被统一码规定为半角，2.该符号涵义就是省略号，不会引发误会，3.许多中文字体中数学符号是造成全角，甚至一些没有全角概念的西文字体（如视窗系统自带字体Cambria、Segoe UI Symbol）会把“⋯”造成接近全角宽度。

因此“……”可替换为“⋯⋯”如果你在视窗上阅读到这里，可能显示字体就是Segoe UI Symbol，那么你已经看到效果了。

实际多个应用案例：https://github.com/MY1L/CoQuBeLi https://github.com/MY1L/FontGame 等。这2个字体均为利用OpenType特性`calt`，在字体发现2个西文标点“…”（一般与西文A的底部基线对齐）相遇时自动替换为与汉字居中的全角“⋯”形成中文省略号。

顺带一提字体的字形可以对应不止一个码位（即[多重映射，一个字形可以对应上万个码位](https://github.com/MY1L/Unicode/releases/tag/Last8)），可以考虑将E908字形多重映射到码位22EF，这样字体文件几乎没有变化，只是多支持一个“⋯”而已。

**Comment by MY1L** [comment]
呃，其实“ttf字体支持”和“OT特性支持”相差很远，许多游戏引擎支持ttf字体，但有些连西文极重要的字体特性`kern`都不支持。我手头条件没法测试这个游戏，但做字体还是可以的。恰好我有做像素字体：https://github.com/MY1L/Ctrl/releases/tag/Zpix ，该像素字体也支持省略号OT特性！不妨试试。

**Comment by dovisutu** [comment]
了解。所以我加了个“不知道支持程度”。

我今天应该可以来测试一下（？）

**Comment by dovisutu** [comment]
Minecraft的”ttf支持“似乎确实很有限。已知kern和liga似乎全部没有启用，字形和偏移不知道选的哪一个（例如t存在明显的偏移，都跟l和i叠在一起了）；不过也可能是我没调好，毕竟以前没专门弄过这个。
理论上也确实可以通过安装模组来适配这一点（在以前的分发流程中，也确实存在分发用模组集成了其余功能的情况，尽管由于架构问题现在做不到了），但是这样操作的繁琐与其收益相较，或许还需权衡。

以下是测试渲染结果：

（size=18(px?pt?)，大小肯定不适配Minecraft的16字体，所以行间重叠了；没有调字体偏移参数）
（用18是因为9,12,24都是糊的）

<img width="215" alt="屏幕截图 2023-05-13 144228" src="https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/40313014/2ec70fa4-1140-44c9-90d7-a612f70841bf">
<img width="216" alt="屏幕截图 2023-05-13 144944" src="https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/40313014/79f55c7d-b559-45ea-b501-38330a1e0d9c">

其实主要的矛盾不在于水平位置，而在于省略号等距；在16px+1px间隔（？）的条件下应该需要些考量，并且可能需要试探Minecraft到底对ttf支持些什么功能（还是什么都不支持）。
如果暴力些或许可以把u2026渲染成32px6点的省略号，卸载字体之后变成3点的；这样子或许也勉强在容忍范围内，不过是下策了。

**Comment by MY1L** [comment]
截图这效果确实不对劲，t在默认情况下不应是这样。话说，那为何不用2个U+22EF“⋯⋯”呢？总比“把u2026渲染成32px6点的省略号”等等来得方便（对我来说只要能修改ttf字体解决的都不算麻烦事，麻烦事是指需要OT特性的，看上去你的需求还不需要，只用批量替换译文里的私用区字符即可）

**Comment by dovisutu** [comment]
之前有人说必须要求省略号等距......不过现在看起来没什么必要，只要“看起来”等距就行了（反正1/3em空格这种很多也不是严格的1/3em）
那确实用22ef就可以了，不需要ot特性，顶多就是我得研究一下怎么做ttf字体......

（其实这边是反过来的，不是译文用了私有区字符，而是分发的时候批量替换成私有区；不过也没太大区别）

**Comment by MY1L** [comment]
我可以帮你做，乃至优化一下（不过先前忘了说，咱“初来乍到”不清楚此Mod的ttf字体放在哪个位置上，不然我直接就修改了😂）

**Comment by MY1L** [comment]
我可以帮你做，乃至优化一下（不过先前忘了说，咱“初来乍到”不清楚此Mod的ttf字体放在哪个位置上，不然我直接就修改了😂）

**Comment by dovisutu** [comment]
> 我可以帮你做，乃至优化一下

非常感谢！

字体文件的位置可以在[mcwiki上的“资源包”界面](https://minecraft.fandom.com/zh/wiki/资源包)找到。具体而言，是assets/(namespace)/font/；此外需要用一个json文件配置加载方式，具体格式也写在那个界面中了。
在本库中，对应位置是./projects/(version)/assets/minecraft/minecraft/font/。

**Comment by dovisutu** [comment]
字体这一块本来不是我弄的，所以有些问题只能说个大概。今天可能可以测试一下。

没有字体文件这个，ttf字体是可选的，这里以前的方案没有用ttf，所以当然找不到；如果有问题，我再改位置就行了。
这个muii18ncompat好像是修改过的思源字体，不知道license放哪里的；我可能得考证一下这个文件的用途。

e908/e909我记得是有偏移量的，不是完全相同（否则当时也不会用私有字符）。

字体映射那个想不起来了，不过可能带映射和不带映射的各需要一份，因为这游戏低版本不支持bmp以外的字符，高版本可以。

（抱歉回复的有些晚；我可能只有周末才有时间处理这些。）

**Comment by dovisutu** [comment]
额，好像需求没说清楚，省略号就用2026或22ef位点，元素符号可能私有区和拓展区各需要一份（文件分开或者都有应该都可以，毕竟这边也是分版本的）

-------

感觉字形还是和既有字形不是很协调（虽然既有字形本身不是很好看），但是效果应该有了
我发一份游戏自带的旧unifont，中文就是调用的这个字形：
[minecraft-embedded-font.zip](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/11580793/minecraft-embedded-font.zip)

（格式是图片......直到最近他们才把这玩意“现代化”了一下，变成.hex了并且更新到unifont15了，但是旧版本还是这个）

-------

这游戏的显示效果有点怪异，省略号居然向上对齐了......
上面那一排“丫”是宽度对照，顺便也算是自带字形的例子
<img width="217" alt="屏幕截图 2023-05-27 105838" src="https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/40313014/8544002a-fb02-4f33-85ad-c98f7c3174d8">


不过我配置文件里有的参数（比如字形偏移）没调，调完估计就能正常一些了

**Comment by MY1L** [comment]
> e908/e909我记得是有偏移量的

呃……老实说我不建议在字体外完成字体的事，到时候冲突都调试不了——等等，你图中用的是私用区字符，或“……”，还是“⋯⋯”？

> 省略号就用2026**或**22ef位点

虽然字体可以2个都支持，但这2个字形是不一样的，最终只能选择用其一。我提议在遇到中西文混排的情况（如有）西文用“…”，中文用“⋯⋯”。

> 元素符号可能私有区和拓展区各需要一份

我上面发的 muii18ncompat1.001.zip 同时支持私用区和汉字扩充区段。
（[顺带一提PUA的“U”是“用”，所以不译“有”](https://github.com/MY1L/Unicode/tree/main/Blocks)😏）

**Comment by dovisutu** [comment]
其实这方面确实不是很了解，甚至可以算是现学的，因为我本来不是弄这个的......用词、观念有误请多见谅。

> 等等，你图中用的是私用区字符，或“……”，还是“⋯⋯”？

私用区。剩下两个也试过，渲染的应该是默认字形。

> > 省略号就用2026**或**22ef位点

这个是我没表述清楚，我的意思就是选**一个**。目前看起来用22ef可以，有问题的话后面再改。

> 同时支持私用区和汉字扩充区段

原来如此。我光顾看字形，忘记看编码表了。

> 但你发的一包是游戏用像素字贴图，不是“字体”。没法给不是字体的东西安排字体特性的，看上去这是一个游戏贴图的问题。

难怪。这么说，我怀疑所谓的“TTF支持”其实是把ttf提供的（某一个）字形直接转成贴图贴上去了，所以字体特性应该都失效了——虽说这里似乎不需要什么字体特性？

**Comment by dovisutu** [comment]
好吧，我现在想了一下，好像不需要ttf这么“重”的东西，干脆直接换贴图都行，反正游戏自己的像素字都是这么干的......
（这玩意甚至是可调尺寸的，就离谱）
