### ISSUE TITLE
[其他]：1.19支持

### ISSUE THREAD

**Issue by Grey-Wind** [CFPAOrg/Minecraft-Mod-Language-Package#2739]
### 详细信息

建议支持1.19版本
————————
小说一句：网址证书似乎出问题了

**Comment by dovisutu** [comment]
网站证书是已知问题，可能需要943来处理。

1.19暂时没有支持计划；目前的计划是在1.20版本稳定下来之后进入1.20；如果在1.19与1.20之间有足够大的更新间隙，能够让1.19的模组生态持续发展，也可能进入1.19，但目前而言还没有计划。
