### ISSUE TITLE
[模组翻译]：GregTech CE: Unofficial 1.12.2 变压器文字缺失、导线及线缆

### ISSUE THREAD

**Issue by 2211427551** [CFPAOrg/Minecraft-Mod-Language-Package#2830]
### 简体中文资源包信息

1.12.2     UTC+0 2023/01/08 23:48:39 

### 模组英文名

GregTech CE: Unofficial

### 模组版本

GregTech CE: Unofficial 1.12.2 2.3.4-beta

### 详细信息

在启用汉化资源包时，GTCEu的变压器“升压””降压“信息缺失
图一为启用汉化资源包，图二为禁用汉化资源包
![image](https://user-images.githubusercontent.com/61936979/213349310-60271101-30e0-48dd-84e4-3e7121dcdcf9.png)
![image](https://user-images.githubusercontent.com/61936979/213349841-524576f2-577d-4d77-9b50-cbaa03bc4053.png)

导线以及线缆的”线损“信息的单位”EU-V“缺失
图三、四为启用汉化资源包时导线（以MgB2导线为例）与线缆（以锡线缆为例）
图五、六为禁用汉化资源包时导线与线缆（例子同上）
![image](https://user-images.githubusercontent.com/61936979/213350580-29a6e14c-e8d1-4a78-9678-dea08b0d4e5a.png)
![image](https://user-images.githubusercontent.com/61936979/213350618-00f5bad8-55e4-4d48-a84c-91d67a05d450.png)
![image](https://user-images.githubusercontent.com/61936979/213351023-a519b2b2-621c-40f3-b52d-ae517f52cb1f.png)
![image](https://user-images.githubusercontent.com/61936979/213351058-282ce9de-90a5-44df-b470-0ef3a6ee96e2.png)

**Comment by mamaruo** [comment]
GTCE 和 GTCEu 冲突导致。

可能唯一解决办法就是干掉 GTCE，两个模组都不支持。
