### ISSUE TITLE
[其他]：翻译键名冲突

### ISSUE THREAD

**Issue by AnzhiZhang** [CFPAOrg/Minecraft-Mod-Language-Package#2854]
### 详细信息

1.12 模组 endreborn、wildnature、与biomesoplenty 冲突，`tile.ash_block.name` 分别被翻译为 `灰`、`灰烬块`、`火山灰块`。
![image](https://user-images.githubusercontent.com/37402126/214008378-d1cfa151-5605-4faf-9fd6-ee51caf3e301.png)

**Comment by kappa-maintainer** [comment]
#1945

**Comment by mamaruo** [comment]
Duplicate of #1954 
临时解决方案就是 [[辅助] 本地化冲突消除 (NoLocalizationConflict) ](https://www.mcmod.cn/class/6368.html)
