### ISSUE TITLE
[其他]：关于优化pr的审核流程

### ISSUE THREAD

**Issue by DrIceTea123** [CFPAOrg/Minecraft-Mod-Language-Package#2924]
### 详细信息

现有问题：
1. **pr过量堆积**（尤其是近几日有向200+冲锋的趋势）；
2. 审核人手不足、（高词条数/帕秋莉/多模组合并提交/等原因导致的）工作量较大、部分pr作者响应慢、早期工单无响应等原因导致的**审核周期过长**，且接下来半年左右还将面临审核更加不足的情况；
3. #2658 提出的pr响应措施“7+7” “3+7”虽有效，但由于人手不足，大多数已经超时未响应的pr**并没有执行相应操作**，甚至没有进入计时；在当前情况下也很难准确地对近200个open的pr进行逐一“7+7”监控；
4. 在pr预览界面**难以查看**pr当前的详细信息与状态，部分标签未能正常规范使用（正常使用的标签包括`词条数` `forge/fabric` `支持版本号` `patchouli` `ready to merge` `needs author action`等，未规范使用且可以有效利用的标签包括`need review` `changes required` `re-review`等）；

建议：
1. 鉴于审核人力远少于能支持稳定审核周期的现状，目前建议至少先对长于4周没有进行**初次review**的pr进行标记（可使用`need review`标签）；
2. 返查提交早的pr，对长时间无响应的pr重新启动“7+7”计时；
3. 完善（大致的）审核流程，例如：
> 1. 作者发布pr；
> 2. cfpa-bot对pr进行初期处理、识别与标记；
> 3. 某位贡献者进行初次review，提出修改意见；
> 4. 作者回应修改意见，或对某一命题进行讨论，或照意见进行修改，或拒绝修改意见；
> 5. 重复步骤3、4，直到贡献者approve了修改；
> 6. 某位贡献者进行二次review，重复步骤3-5，或/和添加`ready to merge`标签；
> 7. 有权限的贡献者重复步骤3-5或/和merge pr。
4. 基于上述审核流程，添加更多/修改部分标签类型，并建立有效利用标签标记pr的规范。例如：
> 1. 删除过期的、无明确意义的、不再使用的标签；
> 2. 前面提到的，规范`need review`的用法，仅对长于4周没有进行**初次**review的pr标记`need review`；
> 3. 区分意义相近的标签，例如`needs author action`和`changes required`，可以将`changes required`改为`needs author action (pinged)`作为“7+7”第二阶段的标签；
> 4. 添加新的阶段性标签，如`need discussion` `first review approved` `need re-review` `repetitive`；

<del>叠盾环节：</del>上述建议仅是我个人的一些想法，不一定需要全部采用，有些可能不够完整或不够合理，有些可能是有误的。我的想法是：有些模组的汉化文件提交很久了，但至今也没有玩家能体验到；有些pr等到初次审核时甚至已经需要更新语言文件。我希望能在有限的条件下优化pr的审核效率，也更方便作者们为汉化做贡献。

**Comment by Ricky-fight** [comment]
stale pull request貌似是可以用bot实现相关操作

**Comment by Ricky-fight** [comment]
> 在当前情况下也很难准确地对近200个open的pr进行逐一“7+7”监控；
7+7措施 2023-02-06 起开始自动执行

**Comment by Cactusstudent** [comment]
解决情况
PR过量堆积；作者回应较慢（加入了搁置规则，成效显著）
审核人手不足（已扩充人手）
无法及时完成搁置流程（引入了stale）
难以查看pr当前的详细信息与状态，标签未正确利用（CFPABot已正确应用部分label；部分label已于年中进行清理，目前情况有所改观）
