### ISSUE TITLE
[展望] 关于后续系统优化改良的一点想法

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#293]
![001](https://i.loli.net/2018/06/07/5b18d05ac11a0.png)

目前获取和翻译在大家的合作下基上完成了，反馈机制也在朋友的帮助下正在制作。  
除去还在制作的问题反馈系统，词典系统逐渐成为这个系统中还未完善的一环，weblate 本身自带词典系统，所以我们需要做的恰恰是获取词典源：

**如何获取统一的词典？按照当前翻译进行拆词？高频词组成词典？**
实际上这可能是比较好的解决办法，高频词，同时对出现该词语模组的个数进行加权，真正获取通用的高频词。

**还有很多争议词语，如何进行统一？**
也许又需要一个反馈系统了

**非 weblate 用户如何快捷使用词典，对翻译进行辅助和质量管控？**
也许做成各种文本编辑器插件（比如 Atom 插件）比较合适

**Comment by Yesterday17** [comment]
好吧，虽然和上文的关联性好像不大，但作为最近疯狂开坑的成果，有几个东西可以拿出来用了。

首先是翻译的问题，之前我记得943视频里说过，现在的机翻系统是需要按词收费的，我去瞅了一眼各大翻译的API，也确是如此。所以，作为坑的一部分，我把[百度翻译](https://github.com/Modlate/Modlate/blob/master/src/router/translate/baidu.ts)和[谷歌翻译](https://github.com/Modlate/Modlate/blob/master/src/router/translate/google.ts)加入了坑中。二者都使用了免费的API（某种意义上的奇淫技巧），因此不用担心收费的问题。

然后是爬虫，我另开了一个仓库负责爬虫部分，采用npm分发的形式进行包的引用。参考了汉化资源包中的爬虫（不同之处在于汉化资源包采用正则而我使用了类JQuery的方式），[这个项目](https://github.com/Modlate/minecraft-curseforge-getter)的目标是实现全CurseForge的接口化。最近的目标是把汉化需要爬取的部分完成（进度90%）。

最后的一切汇集到了[这个大坑](https://github.com/Modlate/Modlate)，它的的最终目标是实现类似Weblate的后端部分，前段部分交由不同的项目负责。

嘛，不管能用多少，我写得倒是挺开心的:smiley:

（所以讲道理词典一定要用Python写吗:confused:

**Comment by TartaricAcid** [comment]
词典？词典存成 csv 格式就行，webalte 可以直接导入。倒是获取词典的程序，随便啥语言都行啊

**Comment by ZeroAurora** [comment]
另外，issue 可以尝试统一管理，比如我就把这个 issue 归类到了 2018 第三季度（虽然只是划水罢了
