### ISSUE TITLE
关于部分翻译不统一问题

### ISSUE THREAD

**Issue by YueLengM** [CFPAOrg/Minecraft-Mod-Language-Package#297]
_Glowstone_ 有一部分被错误翻译成了**萤**石而不是**荧**石。相反真正的萤石 _Fluorite_ 意外的统一，均被译为氟石。

_Creeper_ 个人认为更应该翻译成**爬行者**而不是“苦力怕”。

**Comment by TartaricAcid** [comment]
`萤石`和`荧石`问题遵循原版，稍后我统一批量处理下；
`苦力怕`问题这个就麻烦了，因为这个词语并没有错误，而且更符合大众称呼，我个人认为应该两者均可。

**Comment by TartaricAcid** [comment]
萤石问题被修复：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/b863617b3399c6cdbd9427c6712c83f8b5d80d5b

**Comment by TartaricAcid** [comment]
`Creeper` 翻译问题目前争议很大，我看很多人支持两者均可。
其次我统计了现有翻译，发现两者数量都还停接近。暂定不做任何规范和修改。
