### ISSUE TITLE
请求汉化 Reskillable 和 CompatSkills 模组

### ISSUE THREAD

**Issue by masterbobli** [CFPAOrg/Minecraft-Mod-Language-Package#298]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
我最近在翻译`CraftTweaker`文档的`Reskillable`模组和`CompatSkills`模组部分，由于仓库并没有对应的翻译，因而担心现在我自己的译名和汉化模组的译名不同而造成偏差。希望能够尽快添加，谢谢。
注：4月汉化的`Skillable`模组的作者表示已经弃坑，由`Reskillable`接替

**Comment by TartaricAcid** [comment]
已经添加：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/a9eca8a2dc376820897b142f16e1ac3c0e84efb2
Reskillable 翻译地址：https://weblate.sayori.pw/projects/langpack/reskillable/zh_cn/
CompatSkills 翻译地址：https://weblate.sayori.pw/projects/langpack/compatskills/zh_cn/

**Comment by masterbobli** [comment]
谢谢
