### ISSUE TITLE
[其他]：CONTRIBUTING的文档长期未更新

### ISSUE THREAD

**Issue by luoxueyasha** [CFPAOrg/Minecraft-Mod-Language-Package#3054]
### 详细信息

涉事文档：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md
内容包括Weblate相关内容，翻译规范指向的是旧版的 https://rules.cfpa.team/ 。
而这份contributing文档还在readme上挂着，希望更新一下

**Comment by Ricky-fight** [comment]
#2857

**Comment by mamaruo** [comment]
欢迎来提意见，写文档真的头大

**Comment by luoxueyasha** [comment]
另： github的组织官网挂着的还是旧域名
![image](https://user-images.githubusercontent.com/38830216/230772428-c4e21cb9-2cc2-4726-b7cc-a2f7fedaacb6.png)

新域名：https://cfpa.site/
