### ISSUE TITLE
神秘基础学1.12.2非官方版汉化模组申请

### ISSUE THREAD

**Issue by Kapiw** [CFPAOrg/Minecraft-Mod-Language-Package#309]
[TB] 神秘基础学1.12.2非官方版：Thaumic Bases Unofficial 汉化文件貌似出错了，在客户端里加载不出来，所以想拿到这里让大家一起翻译一下这个mod,下载地址:https://minecraft.curseforge.com/projects/thaumic-bases-unofficial

**Comment by TartaricAcid** [comment]
https://github.com/Rumaruka/Thaumic-Bases-Unofficial/commit/9698876d704fcacc921babb491f3262b07abcd56
已经有人向原作者提交翻译了，目前先暂时不收入
