### ISSUE TITLE
[模组翻译]：

### ISSUE THREAD

**Issue by SakuraiMikoto** [CFPAOrg/Minecraft-Mod-Language-Package#3160]
### 简体中文资源包信息

1.18 2023-3-26 15:37

### 模组英文名

JustHammers

### 模组版本

0.1.2

### 详细信息

错误的将锤与冲击锤的描述，强化锤与强化冲击锤与破坏锤的描述翻译成相同的
原本应该为 锤 3*3*1 冲击锤3*3*3，强化锤5*5*1 强化冲击锤5*5*3 破坏锤5*5*5
均被翻译成了3*3*3与5*5*5

**Comment by A-Black-Fish** [comment]
已检查仓库
库中没有关于JustHammers模组的翻译
PR也没有发现相关翻译
结论：可能是非官方下载中包含zh_cn
（来回看了2次了 1.18\1.18-fabric都没看到关于这个模组的翻译）
1.18
![image](https://user-images.githubusercontent.com/101028476/228997848-d9bd0069-6112-44e3-b40c-5662861b4961.png)
1.18-fabric
![image](https://user-images.githubusercontent.com/101028476/228997916-9d857446-f7fc-4e07-bf6f-2e7f4b90f53b.png)
