### ISSUE TITLE
[其他]：对仓库的fork会按照计划运行Actions

### ISSUE THREAD

**Issue by luoxueyasha** [CFPAOrg/Minecraft-Mod-Language-Package#3167]
### 问题描述
一开始我并没有管这个问题，因为带来的影响只是不定时地给我发个运行失败的邮件，如下图：
![image](https://user-images.githubusercontent.com/38830216/229340610-424a8883-8900-4258-9501-fc3ea9368783.png)

但不久前发现#3154 里出现了大量的Formatter带来的格式更新，可能会导致仓库内与模组内的原文文本格式不一致，还会污染pr内容。

### 可能的解决方案

目前我将自己仓库的Formatter和Packer的workflow禁用了（反正也用不到），作为暂时的对策。
![image](https://user-images.githubusercontent.com/38830216/229340774-82d2bc19-ec65-49ac-91f2-89d8cd157325.png)

相关内容：https://github.com/orgs/community/discussions/26704
不清楚仓库侧有没有对应的设置

**Comment by ChuijkYahus** [comment]
我也是直接关的

**Comment by mamaruo** [comment]
- Formatter 我们仓库已经关掉了。在关闭之后 fork 的仓库应该不存在这个问题。
- 这个 [Discussion](https://github.com/orgs/community/discussions/26704) 提到的解决方案应该只能解决在我们修改 YMAL 文件之后 fork 的仓库，但如上一条所说， 这已没有意义。
- 我没找到相关设置。

**Comment by luoxueyasha** [comment]
以防有老人提交pr出现相同问题，先长期留着？
