### ISSUE TITLE
我想对Serilum 进行翻译 版本1.19.2 前置:fabric

### ISSUE THREAD

**Issue by fgr178707** [CFPAOrg/Minecraft-Mod-Language-Package#3242]
### 详细信息

我想对Serilum 进行翻译 版本1.19.2 前置:fabric

我在 projects 文件里 未发现有1.19 - fabric

我是直接填写到1.19这个文件夹下还是我自己创建一个
1.19 - fabric?

**Comment by mamaruo** [comment]
直接放到 1.19 文件夹

**Comment by fgr178707** [comment]
> 直接放到 1.19 文件夹

ok
