### ISSUE TITLE
翻译重复（很难解释，进来看吧）

### ISSUE THREAD

**Issue by saltycysg** [CFPAOrg/Minecraft-Mod-Language-Package#325]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
CareerBees（职业蜜蜂）的Devil蜂翻译与林业原版的恶魔蜂翻译重复。
建议翻译成“魔鬼蜂”。

**Comment by TartaricAcid** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/976a265aaf821b5a2b98b0149919bd7e0f96fa96
已修复
