### ISSUE TITLE
请求更新/添加binnie's mod系列翻译

### ISSUE THREAD

**Issue by saltycysg** [CFPAOrg/Minecraft-Mod-Language-Package#326]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
如题
赠送两张截图
https://i.loli.net/2018/08/27/5b83b4127f56d.png
https://i.loli.net/2018/08/27/5b83b4128969a.png

**Comment by saltycysg** [comment]
更新了吧_(:з」∠)_
那我那两张图怎么回事

**Comment by TartaricAcid** [comment]
你的 binnie 是最新的么？

**Comment by saltycysg** [comment]
是最新的

**Comment by TartaricAcid** [comment]
我回头查证下，刚刚看了下进度，是 100%

**Comment by saltycysg** [comment]
emm机器内部的说明什么的是不是不属于汉化范围

**Comment by TartaricAcid** [comment]
说一下你的 binnie 版本，不要用一句 最新的 带过

**Comment by TartaricAcid** [comment]
只要有语言文件，都是应该翻译的，除非原作者硬编码

**Comment by saltycysg** [comment]
1.12.2-2.5.0.168

**Comment by TartaricAcid** [comment]
建议你重启客户端试试，我看了下版本也没问题

**Comment by TartaricAcid** [comment]
实际查证了下，确实存在此问题，但是很疑惑，相关词条确实翻译过了啊

**Comment by TartaricAcid** [comment]
这几处翻译似乎都是硬编码，这个建议你直接向原作者反馈
