### ISSUE TITLE
[其他]：如何提交位于data文件夹下的Patchouli手册文件？

### ISSUE THREAD

**Issue by HfSrJun** [CFPAOrg/Minecraft-Mod-Language-Package#3365]
### 详细信息

一般来说模组的语言相关文件都在asset文件夹中。但是我翻译好的一个模组，其手册放在data文件夹中（供帕秋莉手册使用）。请问如何PR这样的文件

**Comment by dovisutu** [comment]
patchouli手册啊......是哪个版本的？不同版本手册的处理方式不太一样

**Comment by HfSrJun** [comment]
> patchouli手册啊......是哪个版本的？不同版本手册的处理方式不太一样

1.18.2-71.1

**Comment by mamaruo** [comment]
见此 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3366#issuecomment-1586029649
