### ISSUE TITLE
1.19.4 资源包错误

### ISSUE THREAD

**Issue by shenyx110** [CFPAOrg/Minecraft-Mod-Language-Package#3417]
加载完出现资源包错误 手动使用1.19也会报错 用1.18可行
[minecraft-exported-logs-2023-06-27T10-08-41.log](https://github.com/CFPAOrg/I18nUpdateMod3/files/11877006/minecraft-exported-logs-2023-06-27T10-08-41.log)

**Comment by ALINGCAT** [comment]
1.19.2也碰到这个问题

**Comment by n-507** [comment]
```
net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: all the creatures:texts/blueprint/splashes.json
```

"all the creature"文件夹包含空格，导致崩溃。查看Commit发现此问题已修复，但最新版资源包似乎尚未构建，因此i18n模组仍然会下载出现错误的资源包，从而导致玩家无法运行游戏。

**Comment by Cactusstudent** [comment]
已完成修复，可以手动下载修复后的资源包或是使用i18n模组下载。
