### ISSUE TITLE
LiteLoader翻译讨论

### ISSUE THREAD

**Issue by liach** [CFPAOrg/Minecraft-Mod-Language-Package#343]
- [ ] ~反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；~讨论帖
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

最早的文件（两年前的）： https://gist.github.com/liach/197a4a3e32675aacf272a4b560b0fbfe
（被墙的话告诉，你实际上就和现在的文件一样啦）

问题：
1.文件要改名
2.全半角符号
3.tweaker mixin等术语翻译
4.前后空格

**Comment by TartaricAcid** [comment]
- 文件名不存在错误（具体可见 <https://minecraft.gamepedia.com/Resource_pack> pack_format 部分）
- 全半角已经修复
- `tweaker` `mixin` 等术语不需要翻译
- 前后空格问题已修复
