### ISSUE TITLE
疑似 craftpresence 加载汉化文件时出现问题

### ISSUE THREAD

**Issue by InsulateJustf** [CFPAOrg/Minecraft-Mod-Language-Package#362]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
确认了不是 `I18nUpdateMod` 的 bug，是资源包的问题。
表现为：首次进入游戏在游戏中加载资源包是正常的，关闭游戏后就无法再次启动，`craftpresence.properties` 文件被清空。也就是说，游戏启动前和启动时不能加载资源包否则必定出错。疑似和此 repo 下的 [issue#283](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/283) 是一样的情况。

**Comment by InsulateJustf** [comment]
好的，非常感谢，麻烦了( •̀ ω •́ )

**Comment by TartaricAcid** [comment]
已经删除此模组翻译
