### ISSUE TITLE
模组手册翻译进度公示

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#364]
现在基本上各大模组都添加了手册，但是手册标准五花八门，很难用一个脚本进行更新处理，进一步进行翻译。只能通过公示方式，主动招标，让翻译者提交 PR 进行翻译。

- [ ] pewter 手册，包括匠魂和匠魂护甲两个模组手册部分；
- [ ] factorytech 手册，只完成了一半，还有大约两三章节未完成；

**Comment by dovisutu** [comment]
@TartaricAcid 要不要考虑一下把这个issue给pin起来？这样子看到的人会多一点
另，添加两个手册：
- [ ] bewitchment  > 有两本书，曾经因为翻译跟不上而被删去，现在 @TUsama 正在试图翻译
- [ ] root > 情况不太了解

**Comment by fansi2020** [comment]
#781 this is a sample comment.
