### ISSUE TITLE
[模组翻译]：对1.12.2的热力物流学mod的汉化语言文件中缺少汉化文段

### ISSUE THREAD

**Issue by lava191810** [CFPAOrg/Minecraft-Mod-Language-Package#3703]
### 简体中文资源包信息

1.12.2，2023-08-14T10:37:56Z

### 模组英文名

thermallogistics

### 模组版本

0.3-40

### 详细信息

汉化文件中缺少info.logistics.terminal.requester字段，原文为“Please put a requester in the requester slot before requesting items.”在终端中请求器槽未插入请求器时拿取终端内物品时出现。

**Comment by lava191810** [comment]
还有四条与jei的联动翻译缺失，分别是:
`info.logistics.terminal.autofocus.true=Autofocus search bar
info.logistics.terminal.autofocus.false=Don't autofocus search bar
info.logistics.terminal.jei.true=Synchronize with JEI
info.logistics.terminal.jei.false=Don't synchronize with JEI`
用于终端界面中左上角按键的提示

**Comment by lava191810** [comment]
缺的不是一般的多……
热力物流学的en_us.lang有74行
汉化资源包的zh_cn.lang只有63行
差了11条

**Comment by DrIceTea123** [comment]
这种一般都是模组翻译未及时更新，在这里特定模组的翻译更新不是分交给某个人持续跟进的，而是由所有贡献者自由选择
因此，诸如“模组汉化不全”“模组翻译缺失”等问题请提交到 #2702 或[翻译请求问卷](https://wj.qq.com/s2/11799706/c2b7)，不要单独开issue
