### ISSUE TITLE
[其他]：修改版模组怎么处理？

### ISSUE THREAD

**Issue by RuiXuqi** [CFPAOrg/Minecraft-Mod-Language-Package#3725]
### 详细信息

如题，随着1.12.2的逐渐衰老，很多模组的1.12.2版本已经停更，也因此诞生了许多修改版/续更版/社区版，意在修复bug和添加一些新特性，不少都已在curseforge等大平台上发布，也得到了很多玩家和整合包作者的支持
但既然是修改版，就有可能会添加一些新key、更改一些旧文本，也就需要更新汉化了。根据个人测试，构建出来的汉化包因为modid相同的缘故导致汉化半新半旧，是否有解决方法？还是说应该覆盖掉原版的汉化而不是新建一个？

**Comment by Cyl18** [comment]
#2336

**Comment by mamaruo** [comment]
现阶段是无法处理的。
