### ISSUE TITLE
沉浸工程含有重复的中文物品名称

### ISSUE THREAD

**Issue by mcBegins2Snow** [CFPAOrg/Minecraft-Mod-Language-Package#393]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

最近我去浏览沉浸工程百科物品方块页面 https://www.mcmod.cn/item/list/463-1.html ，发现有些物品不存在，最可能的原因是中文物品名重复。
现在给百科添加资料使用由 IRR https://www.mcmod.cn/class/1166.html 导出的 json 文件进行批量更新/添加，以确保资料信息是完全正确的。缺点是一旦遇到中文名重复的资料，它会被覆盖，造成缺失。
重名物品列表：
`item.immersiveengineering.material.stick_steel.name=钢杆（Steel Rod）`
`tile.immersiveengineering.metal_decoration2.steel_post.name=钢杆（Steel Post）`
`item.immersiveengineering.material.stick_aluminum.name=铝杆（Aluminium Rod）`
`tile.immersiveengineering.metal_decoration2.aluminum_post.name=铝杆（Aluminium Post）`
`item.immersiveengineering.wirecoil.hv.name=高压线圈（HV Wire Coil）`
`tile.immersiveengineering.metal_decoration0.coil_hv.name=高压线圈（High-Voltage Coil Block）`
这些问题如果得不到修复，缺失的资料将无法加进去。

**Comment by TartaricAcid** [comment]
我刚刚特意进了游戏看了下。
1. 两个重名的词条实际上指的是同一个事物。只不过一个是物品，一个是实际的方块。
2. 这个翻译英文虽然表达略有不同，但是实际含义也是指的同一个事物。
3. 模组目前自带翻译也是这样的，即不存在翻译错误，也不需修改。

我还注意到模组百科方面的描述，有两个观点算是稍微补充说明下：
1. 翻译重名问题不单单存在于资源包中，实际上连同英文原文，自带中文都是一样的。这即不存在翻译错误，也更不是自动汉化模组的问题。
2. 翻译方面目前的原则就是尽可能与原作者那里翻译同步，如果存在不同，是需要进行处理的。我看到有指出翻译存在不同，如果可以的话希望能反馈具体哪个模组存在不同，我们这边尽可能进行同步。

**Comment by mcBegins2Snow** [comment]
那么我可以依据 IRR 导出的 json 文件手动加资料，并加上消歧义声明，这样就能解决问题。
