### ISSUE TITLE
仓库是否仍接受1.12版本汉化贡献

### ISSUE THREAD

**Issue by HfSrJun** [CFPAOrg/Minecraft-Mod-Language-Package#3967]
### 详细信息

想询问一下，仓库是否接受新添加的1.12版本汉化，以及是否接受对现存1.12版本汉化的修改

**Comment by dovisutu** [comment]
答案是肯定的。
比如说，[这里](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pulls?q=is%3Apr+is%3Aopen+label%3A1.12.x)就列出了所有涉及1.12版本的、正在审核的提交。

**Comment by HfSrJun** [comment]
> 答案是肯定的。 比如说，[这里](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pulls?q=is%3Apr+is%3Aopen+label%3A1.12.x)就列出了所有涉及1.12版本的、正在审核的提交。

感谢解答，因为前段时间有人说1.12不再接收贡献，而我要修订1.12版本某模组的翻译，因此来求证。
