### ISSUE TITLE
沉浸工程部分 debuff 的中文名不符合英文意思

### ISSUE THREAD

**Issue by mcBegins2Snow** [CFPAOrg/Minecraft-Mod-Language-Package#398]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

`immersiveengineering.potion.concreteFeet=缓慢`（Concrete Feet）
在玩家陷进固化的液态混凝土时会获得效果，玩家无法动弹，不是移动速度变慢的意思。
https://ftb.gamepedia.com/Concrete_Feet
`immersiveengineering.potion.flashed=闪现`（Flashed）
给盾牌装了闪光灯后，格挡敌人时会获得这个效果。“闪现”是指短暂地出现；忽然出现。（https://baike.baidu.com/item/闪现/5087712?fr=aladdin ）这样翻译不合适。
https://ftb.gamepedia.com/Flashed

**Comment by TartaricAcid** [comment]
收到
`Concrete Feet` 也许可以翻译成 `凝滞`，我发现如果带上`脚`这个字可能不是太好听，当然只是作为建议。
`Flashed` 应该没啥疑问，直接翻译成`闪光`，那个效果也有点像闪光弹。

**Comment by mcBegins2Snow** [comment]
感谢回复

**Comment by mcBegins2Snow** [comment]
感谢回复
