### ISSUE TITLE
FTB Beyond 整合包汉化补全进度表

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#4]
- [x] Advanced Machines 补全汉化
- [x] BloodArsenal 补全缺失部分汉化
- [x] Dark Utilities 完成
- [x] Draconic Evolution 完成补充
- [x] DeepResonance 完成缺失手册汉化
- [x] DecoCraft 补全缺失部分汉化
- [x] Extra Utilities 2 补全缺失汉化
- [x] JourneyMap 补全部分汉化
- [x] Immersive Engineering 完成缺失部分汉化
- [x] Modular Force Field System 补全汉化
- [x] RFTools Dimension 完成手册汉化
- [x] Signals 补全缺少汉化
- [x] TechReborn 完成缺失部分汉化
- [x] XNet 完成手册汉化 
- [x] Zerocore 完成

**Comment by mgdgfbhevdyeh** [comment]
TechReborn交给我吧，我玩一段世界了
