### ISSUE TITLE
[模组翻译]：在安装了汉化材质后高清修复中部分词条出现翻译错误

### ISSUE THREAD

**Issue by xx146542xx** [CFPAOrg/Minecraft-Mod-Language-Package#4018]
### 简体中文资源包信息

1.7.10 12月11日自动下载

### 模组英文名

optifine

### 模组版本

1.7.10_HD_U_E7

### 详细信息

https://github.com/CFPAOrg/I18nUpdateMod3/issues/17

**Comment by Cactusstudent** [comment]
1.7.10 为不受支持的版本，不会进行维护
