### ISSUE TITLE
Thermal Foundation 焦煤块&焦炭翻译不一致

### ISSUE THREAD

**Issue by Snownee** [CFPAOrg/Minecraft-Mod-Language-Package#409]
- [X] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [X] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

**Comment by TartaricAcid** [comment]
我的天，这仓库的 issues 我每次都忘了看了

**Comment by Snownee** [comment]
有的时候在忙别的事情，碰巧看到就暂时记下来了 😂
