### ISSUE TITLE
星芒宝典技能点描述不正确

### ISSUE THREAD

**Issue by mcBegins2Snow** [CFPAOrg/Minecraft-Mod-Language-Package#420]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

下面是三个截图：
![2019-01-14_18.29.51.png](https://i.loli.net/2019/01/14/5c3c65dc5c535.png)
![2019-01-14_18.29.34.png](https://i.loli.net/2019/01/14/5c3c65dc72c36.png)
![2019-01-14_18.30.00.png](https://i.loli.net/2019/01/14/5c3c65dd6dba5.png)
百分数不能正确显示

**Comment by Water-Moon** [comment]
成功修复了这个bug.
已经提交Pull Request.
祝玩得开心~
效果截图：
![image](https://user-images.githubusercontent.com/43123946/51286048-492bc800-1a2c-11e9-8e30-ac9b743eb7c4.png)
![image](https://user-images.githubusercontent.com/43123946/51286066-5648b700-1a2c-11e9-8f49-5bdc59fa69fc.png)

**Comment by TartaricAcid** [comment]
问题已经解决
