### ISSUE TITLE
翻译请求：The Dawn Era  1.20.1

### ISSUE THREAD

**Issue by bitlittl** [CFPAOrg/Minecraft-Mod-Language-Package#4416]
### 详细信息

https://www.mcmod.cn/class/13500.html

**Comment by SlimeSB** [comment]
#4315 很抱歉一直挂着没过

**Comment by bitlittl** [comment]
[https://pan.baidu.com/s/1M6CuR9_961J8ngZp63jIBQ=ucwk](url)行吗

**Comment by bitlittl** [comment]
> #4315 很抱歉一直挂着没过

[https://pan.baidu.com/s/1M6CuR9_961J8ngZp63jIBQ=ucwk](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/url) 行吗
