### ISSUE TITLE
[其他]：Roguelike Adventures and Dungeons 2 请求汉化

### ISSUE THREAD

**Issue by SC0624a** [CFPAOrg/Minecraft-Mod-Language-Package#4442]
### 详细信息

整合包：Roguelike Adventures and Dungeons 2
Forgr：1.16
MC版本：1.16.5
整合包版本：RAD-1.11

**Comment by Cactusstudent** [comment]
本仓库主要负责模组汉化，整合包汉化请求不接受，十分抱歉
