### ISSUE TITLE
Invasion 整合包汉化补全进度表

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#45]
- [x] adhooks
- [x] air_support
- [x] animalium
- [x] dooglamoocitiesmod
- [x] dungeontactics
- [x] earthworks
- [x] ediblebugs
- [x] foragecraft
- [x] furnus
- [x] gearswap
- [x] geneticsreborn
- [x] hardcorewither
- [x] kaishiweapons
- [x] lcrdrfs
- [x] littlelooter
- [x] minecolonies
- [x] mfs
- [x] morefurnaces
- [x] ompd
- [x] openmodularturrets
- [x] quantumflux
- [ ] reccomplex
- [x] ropebridge
- [x] spartanshields
- [x] voxels
- [x] wired
- [x] wtfcore
- [x] wtfgameplay

**Comment by mgdgfbhevdyeh** [comment]
foragecraft是什么Mod怎么重来没见过

**Comment by TartaricAcid** [comment]
不知道，这个本地化出了点错，等会儿还要改

**Comment by TartaricAcid** [comment]
ompd是invasion里面一个模组的缩写，你得按照invasion包来检索模组
