### ISSUE TITLE
汉化资源包仓库 Label 名称更改草案（WIP）

### ISSUE THREAD

**Issue by Cactusstudent** [CFPAOrg/Minecraft-Mod-Language-Package#4611]
仓库内 Label 名称更改草案：

更改，删除如下：

| 原先 Label | 更改后 Label | 原因 |
| :-----------: | :-----------: | ----------- |
| **wont fix** | `不会修复` | 保持原先意思，仅翻译 |
| **warn** | 直接移除 | 现在也没啥用了，因为 label 都逐渐细化然后取代了 warn |
| **suggestion** | `建议` | 保持原先意思，仅翻译 |
| **question** | `尚有疑问` | 保持原先意思，仅翻译 |
| **obsolete** | 直接移除 | 将 obsolete 更换为新的两个 label |
| **meaningless** | `无意义` | 保持原先意思，仅翻译 |
| **laborious** | `审阅困难` | 保持原先意思，仅翻译 |
| **in progress** | `未完成` | 保持原先意思，仅翻译 |
| **Forge** | `(Neo)Forge` | 适应 1.20 之后版本 NeoForge 端模组的兴起 |
| **enhancement** | 直接移除 | 被 feature 取代 |
| **duplicate** | `重复` | 保持原先意思，仅翻译 |
| **changes require** | `需要更改` | 保持原先意思，仅翻译 |
| **机器翻译** | `生硬翻译` | 群内讨论 |

新增如下

| 新增 Label | 原因 |
| :-----------: | ----------- |
| ~**需要自校**~ | ~为了适应新的“硬茬”审阅方式~ 移动到 `生硬翻译` 内 |
| **已过时** | 原来已经删除的`outdated` label的中文形式 |
| **feature** | 才发现库里面没有这个label，这次补上 |

需要考虑：
- [x] 1. 文档的撰写
- [x] 2. Boring-Bot的配置文件改写

**Comment by SlimeSB** [comment]
laborious 描述新增一个：合并前需二次审校

**Comment by SlimeSB** [comment]
question其实是issue的分类
