### ISSUE TITLE
有两个物品的名称显示不正常

### ISSUE THREAD

**Issue by qq512065439** [CFPAOrg/Minecraft-Mod-Language-Package#469]
查了一下应该是和其他MOD冲突了

> Minecraft-Mod-Language-Package\project\assets\fossil\lang\zh_cn.lang:
> 155: tile.cultivate.name=培养槽
> Minecraft-Mod-Language-Package\project\assets\jurassicraft\lang\zh_cn.lang
> tile.cultivate.name={color}培养仓

> Minecraft-Mod-Language-Package\project\assets\fossil\lang\zh_cn.lang:
> 264: item.shell.name=鹦鹉螺
> Minecraft-Mod-Language-Package\project\assets\flansmod\lang\zh_cn.lang:
> 547: item.shell.name=AP 坦克炮弹

- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

**Comment by TartaricAcid** [comment]
请向该模组原作者反馈，我这边无法处理这种冲突
