### ISSUE TITLE
[其他]：统一库内“凤梨”丨“菠萝”的翻译 

### ISSUE THREAD

**Issue by AnzhiZhang** [CFPAOrg/Minecraft-Mod-Language-Package#4740]
### 详细信息

根据 #3935 中各位仓库维护者的指示精神，提出此相关问题联动 issue

早上好CFPA，现在我有~凤梨~ 菠萝！

2011年/2016年的《现代汉语词典》推荐规范字形为`凤梨`，1994年《农学名词》规定为`菠萝`。 本pr因此将库内的`凤梨`统一进行修改为`菠萝`。

---

根据 #3935 中各位仓库维护者的指示精神，补充以下依据：

- 《[现代汉语词典](https://cd.hwxnet.com/view/ahjnmjmpjmcefmkb.html)》在线查询结果：
  - 凤梨：词典解释 ①多年生草本植物，叶子大，边缘有锯齿，花紫色，果实密集在一起，外部呈鳞片状，果肉味甜酸，有很浓的香味。产于热带，我国广东、台湾等地都有出产。②这种植物的果实。‖也叫菠萝，俗称菠萝蜜。
  - 菠萝：1.即凤梨。... [pineapple] 见“凤梨”
- 《农学名词》在线检索
  - [凤梨](https://termonline.cn/search?searchText=%E5%87%A4%E6%A2%A8)：抱歉，您搜索的关键词，全国科技名词委尚未审定公布。
  - [菠萝](https://termonline.cn/search?searchText=%E8%8F%A0%E8%90%9D)：英文对照：pineapple,Ananas comosus (L.) Merr. 学科领域： 「农学名词」
- 根据[CCL语料库检索系统](http://ccl.pku.edu.cn:8080/ccl_corpus)的搜索结果，“菠萝”一词在 **9464** 个文档中出现，而“凤梨”共在 **1872** 个文档中出现。
- 根据国内版必应使用“菠萝”与“凤梨”作为关键词并排除对方后的搜索结果，搜索“菠萝”有**399,000**条结果，搜索“凤梨”只有**101,000**条结果。
- 2019年《[植物学名词（第二版）](https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B92460D2C12469275E053010B0A0A786D000)》使用一处 “菠萝”、两处 “凤梨”。
- [联合国粮食及农业组织术语门户网站](https://www.fao.org/faoterm/zh/)：凤梨科、凤梨属、菠萝

根据 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3935#issuecomment-2426472961 提出的 `使用词频、行业标准乃至原文上下文亦应该是影响因素`，“菠萝” 是词频使用更多的用词。

---

[据悉](http://www.cnterm.cn/xwdt/zhxw/202302/t20230220_733523.html)，2023年2月11-12日，农学名词委在京召开新版农学名词终审会。

新版农学名词现已于2024年5月[公开征求意见](http://www.cnterm.cn/xwdt/tzgg/202405/t20240507_779153.html)：http://www.cnctst.cn/news/tzgg/202407/W020240819368474786601.pdf

5. 1. 98 菠 萝 　 pineapple, Ananas comosus
(L. ) Merr
又称“凤梨”。 凤梨科凤梨属果树,多年生单
子叶草本植物。 原产巴西。 喜温暖,忌霜冻,
根端有菌根共生,叶背茸毛和气生根均可吸
收空气中的水分。 是果树中少有的景天酸代
谢植物。 果实鲜食或加工用。

5. 3. 75 紫凤梨　 tillandsias, air plant, Tillandsia cyanea
又称“铁兰”。 凤梨科铁兰属多年生常绿草
本花卉。 染色体数多数 2n = 2x = 50。 植株呈
莲座状、筒状、线状或辐射状,叶子呈莲座状
或呈束集状或沿茎分布,多列或二列,全缘,
有披针形、线形,直立、弯曲或先端卷曲。 主
要观赏花序。

5. 3. 76 观赏凤梨　 ornamental bromeliad
凤梨科(Brome liaceae)多年生草本植物。 以
附生种类为主,一般附生于树干或石壁上,性
喜温暖、潮湿的半遮阴环境。 常见的种类和
品种,主要属于凤梨科的珊瑚凤梨属( Aechmea)、水塔花属(Billbergia)、果子蔓属(Guzmania)、 彩 叶 凤 梨 属 ( Neoregelia)、 铁 兰 属
(Tillandsia)和莺歌属( Vriesea) 这 6 个类群。
以观花为主,也可观叶。

---

该 issue 供讨论或**搁置**，如有需要可像 #3935 一样修改方向，改为统一为 `凤梨`

**Comment by AnzhiZhang** [comment]
新版农学名词现已于2024年5月[公开征求意见](http://www.cnterm.cn/xwdt/tzgg/202405/t20240507_779153.html)：http://www.cnctst.cn/news/tzgg/202407/W020240819368474786601.pdf

5. 1. 98 菠 萝 　 pineapple, Ananas comosus
(L. ) Merr
又称“凤梨”。 凤梨科凤梨属果树,多年生单
子叶草本植物。 原产巴西。 喜温暖,忌霜冻,
根端有菌根共生,叶背茸毛和气生根均可吸
收空气中的水分。 是果树中少有的景天酸代
谢植物。 果实鲜食或加工用。

5. 3. 75 紫凤梨　 tillandsias, air plant, Tillandsia cyanea
又称“铁兰”。 凤梨科铁兰属多年生常绿草
本花卉。 染色体数多数 2n = 2x = 50。 植株呈
莲座状、筒状、线状或辐射状,叶子呈莲座状
或呈束集状或沿茎分布,多列或二列,全缘,
有披针形、线形,直立、弯曲或先端卷曲。 主
要观赏花序。

5. 3. 76 观赏凤梨　 ornamental bromeliad
凤梨科(Brome liaceae)多年生草本植物。 以
附生种类为主,一般附生于树干或石壁上,性
喜温暖、潮湿的半遮阴环境。 常见的种类和
品种,主要属于凤梨科的珊瑚凤梨属( Aechmea)、水塔花属(Billbergia)、果子蔓属(Guzmania)、 彩 叶 凤 梨 属 ( Neoregelia)、 铁 兰 属
(Tillandsia)和莺歌属( Vriesea) 这 6 个类群。
以观花为主,也可观叶。

**Comment by luoxueyasha** [comment]
#关于#3935 及相关PR的处理

关于#3935 与 #4738 #4739 #4740 （下文称“相关PR”）的相关问题讨论如下：
* #3935 与相关PR的改动本质不同，#3935 为同一汉语词汇的两种字形的变更，相关PR为两个同义或近义汉语词汇的相互替换。从语义上来讲，相关PR的相互替换会构成一定程度的语义变更，而#3935 不会。
* #3935 出于统一游戏内搜索关键词、统一模组翻译用语的目的提出；但就目前的汉语语言环境，“冰淇淋”“冰激凌”均有较高的使用频率，各方标准的推荐字形也不一致（数据见#3935 内的讨论）。其中近年网络交流环境与食品工业环境推倡“冰淇淋”，而《现代汉语词典》与出版业推倡“冰激凌”。
* 相关PR内具有大量的忽略原文内容、强制统一而做出的修改，例如“小土豆”→“小马铃薯”（“Tiny Potato”, Botania（植物魔法）），这是违反《[翻译规范](https://cfpa.site/TransRules/)》 06. 专有名词 一节的。
* 相关PR的数据支持与论据不足。例如#4738 在已给出“土豆”为词频使用更多的情况下，仍然选择强制统一为“马铃薯”（不论语境），自相矛盾。
* 相关PR具有破坏嫌疑，表现为借用#3935 内的讨论格式，通过全库批量替换提出大量的修改请求。
* 库内原版名词不统一（例如土豆→马铃薯）的问题客观存在。

经内部协商讨论，关于#3935 相关 Pull Request 及 Issue 处理结果如下：
* 基于实际语言环境与“铁质/铁制”原则，不强制模组间统一“冰激凌”/“冰淇淋”。#3935 的改动只有6行，影响较小；库内标准化为“冰淇淋”的理由充足（见#3935 讨论），可以保留此PR。但其提交的模组文本落后于模组最新版文本，可能面临进入3+7流程。若需要合并，则仍需公示。
* 因为破坏性，关闭相关PR（#4738、#4379、#4740）。若@AnzhiZhang 仍需提交对“土豆/马铃薯”在合理语境（如：Minecraft原版）下的术语统一，需另开Pull Request，且仍需审阅后公示。相关pr内交流时，各方应注意讨论礼仪。
* 另提交对贡献方针中“铁质/铁制”原则的扩充Pull Request，由@luoxueyasha 提交。
* CFPA对于“Icecream”的译法，以及“冰激凌”/“冰淇淋”的字形没有推荐。在合理的语境下，可以使用“冰激凌”、“冰淇淋”、“雪糕”、“冰棍”、“冻奶油”等译名（需要做到模组内/联动、附属模组间统一）。

特此公告。有异议请于#3935 下提出。
