### ISSUE TITLE
[其他]：使用材质包并强制使用unicode字体，但数字跟英文没有生效

### ISSUE THREAD

**Issue by BlackRiceXY** [CFPAOrg/Minecraft-Mod-Language-Package#4768]
### 详细信息

![image](https://github.com/user-attachments/assets/188e7af2-be06-465b-b577-75c3cd3acb56)
1.21.1 neoforge i18n-3.6.0
当不使用汉化包，不会出现这个问题

**Comment by dovisutu** [comment]
1.20.5中，自定义字体引入了filter机制，原版字体在强制Unicode时似转为用filter+uniform选项而非使用uniform字体，但仓库侧的字体修复文件尚未更正，这似乎导致了1.20.5及1.21中强制Unicode失效。

以下是原版的default.json。
```json
{ 
     "providers": [ 
         { 
             "type": "reference", 
             "id": "minecraft:include/space" 
         }, 
         { 
             "type": "reference", 
             "id": "minecraft:include/default", 
             "filter": { 
                 "uniform": false 
             } 
         }, 
         { 
             "type": "reference", 
             "id": "minecraft:include/unifont" 
         } 
     ] 
 }
```
注意filter一项。

[询问] 该现象能在1.20.5中复现吗？能在1.20.4及以下复现吗？

-------

1.21的字体文件将于近期更正。由于发包策略问题，1.20.5（如有问题）的更正可能较为复杂，需要更长时间。
