### ISSUE TITLE
[TOP]The One Probe请求汉化

### ISSUE THREAD

**Issue by yuehongcheng** [CFPAOrg/Minecraft-Mod-Language-Package#479]
- [ ] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [ ] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

在服务器上安装了[TOP]The One Probe和TOP Addons
![QQ截图20190520112657](https://user-images.githubusercontent.com/48173817/57994964-416f5380-7af2-11e9-88f1-c7327b355749.png)
个别内容显示为英文的。  想请求汉化一下。

**Comment by TartaricAcid** [comment]
才发现这里居然有反馈问题的，TOP 服务器显示问题在于作者本身源代码问题，汉化做不到
