### ISSUE TITLE
[其他]模组翻译

### ISSUE THREAD

**Issue by cqwlxc** [CFPAOrg/Minecraft-Mod-Language-Package#4797]
### 详细信息

https://www.mcmod.cn/class/12504.html
https://www.curseforge.com/minecraft/mc-mods/resource-chickens
这个资源鸡的lang文件没有物品的语言内容,游戏内的各种鸡还有联动的鸡的名称文件在mod里的daata/configs内.  我没有办法自己进行简单的翻译

**Comment by luoxueyasha** [comment]
data/configs属于无法被资源包替换的内容，我们也无能为力。
请考虑使用mixin或者Vault Patcher这类工具，或者直接联系模组作者。
