### ISSUE TITLE
Sky Factory 3 整合包汉化补全进度表

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#5]
- [x] baconators
- [x] beneath
- [x] cyclopscore
- [x] extrabitmanipulation
- [x] fenceoverhaul
- [x] headcrumbs
- [x] hydrogel
- [x] integrateddynamics
- [x] integratedtunnels
- [x] llibrary
- [x] lootbags
- [x] mysticalagriculture
- [x] packingtape
- [x] randomthings
- [x] redstonepaste
- [x] shearmadness
- [x] simplebarrels
- [x] voidcup
- [x] waddles
- [x] withercrumbs
- [x] xprings

**Comment by chaoyi4523** [comment]
大大能汉化一下任务书吗

**Comment by TartaricAcid** [comment]
什么任务书？

**Comment by chaoyi4523** [comment]
SF3里头有个MOD叫Simple Achievements里头的任务书

**Comment by subtank** [comment]
就是开始游戏的那个任务书。其实那个任务书没啥意思的，就是告诉你这个游戏该怎么玩。各种mod（大型）该怎么开局而已，具体的东西没啥的。汉化与否根本没什么区别，不像天空2那种不汉化没法玩。

**Comment by subtank** [comment]
在SF3里面也有Immersive Engineering这个模组的。这个模组应该没有汉化完全的吧？

**Comment by TartaricAcid** [comment]
请看这个https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/issues/4
@subtank

**Comment by subtank** [comment]
搜嘎~

**Comment by 3TUSK** [comment]
我看了一下 Simple Achievement 的具体情况... 那个书不是 Mod 本身的内容，不可能翻译的。
至于整合的汉化，我承认——这是个空白。整合的本地化基本是不可能完成的任务，整合的发布若是要和本地化进度同步，所带来的挑战绝对会是**空前的**。

**Comment by DSLM** [comment]
@3TUSK 那目前有无方法汉化写在代码里面的条目？

**Comment by 3TUSK** [comment]
...Yes and no.

**Comment by chaoyi4523** [comment]
我看过马里奥红叔的sf3视屏里头的任务书是汉化的去微博问他他也没回。。。

**Comment by 1793907272** [comment]
Integrated Dynamics 已经被汉化了？

**Comment by TartaricAcid** [comment]
没有，东西太多目前还没法填坑

**Comment by 1793907272** [comment]
@TartaricAcid 我clone下来之后是是有的..

**Comment by TartaricAcid** [comment]
但是不全，还差几个

**Comment by 1793907272** [comment]
@TartaricAcid ok  
PS：回复我的时候@我行吗？

**Comment by mgdgfbhevdyeh** [comment]
我感觉国内没有玩家玩过 integrateddynamics

**Comment by 3TUSK** [comment]
@mgdgfbhevdyeh 你说这些mod有哪些国内玩家经常接触？

**Comment by mgdgfbhevdyeh** [comment]
我除了integrateddynamics其他都多多少少接触过，其他国内玩家我不清楚，但是我感觉接触redstonepaste应该也不少

**Comment by TartaricAcid** [comment]
>我感觉国内没有玩家玩过 integrateddynamics

没事，我做个教程大家就都知道了_(:з)∠)_
@mgdgfbhevdyeh

**Comment by mgdgfbhevdyeh** [comment]
@TartaricAcid 真良心
(Integrated Dynamics虽说感觉这个没XNet和SFM好)

**Comment by DSLM** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3/files/2429921

> Mod(s) Added
> Farming for Blockheads by BlayTheNinth (1.1.13)

**Comment by DSLM** [comment]
已完成SF3最新版本汉化检查
需汉化文本已提交
baconators更新了文本，但无需汉化，故不更新
Farming for Blockheads已加入本整合包（见上）
@TartaricAcid
