### ISSUE TITLE
请求汉化气动工艺手册

### ISSUE THREAD

**Issue by scikirbypoke** [CFPAOrg/Minecraft-Mod-Language-Package#500]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
气动工艺也出了patchouli手册，但资源包内并没有汉化

**Comment by TartaricAcid** [comment]
慢慢来吧
