### ISSUE TITLE
请求汉化LordCraft

### ISSUE THREAD

**Issue by Water-Moon** [CFPAOrg/Minecraft-Mod-Language-Package#505]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

Lord Craft （ https://minecraft.curseforge.com/projects/lord-craft ） 是一个魔法主题的模组，现阶段有稳定版本且比较热门，但似乎汉化包并不包含其翻译。

**Comment by Water-Moon** [comment]
__*不如我直接给翻译了吧*__
__*反正现在还没期末考试*__

**Comment by TartaricAcid** [comment]
因为之前我把它加到爬虫黑名单里面去了
