### ISSUE TITLE
部分模组指导书汉化无效

### ISSUE THREAD

**Issue by RUInsYi** [CFPAOrg/Minecraft-Mod-Language-Package#510]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
---
基于`book.json`（如 MagnetiCraft）的指导书，资源包提供的汉化无法使用。将翻译文件手动添加至模组文件内后可正常使用。

已确认游戏语言环境为简体中文。

**Comment by xinyuan-liu** [comment]
指导手册每个模组的实现都不一样，不是这个资源包能统一解决汉化问题的。
除非是这个资源包里的目录结构错了，改目录就够就能解决，否则都得去找模组作者。
要么把汉化传给作者；
要么说服作者改代码逻辑，优先去资源包里找assets，比如Patchouli这种可以这样搞试试。

**Comment by xinyuan-liu** [comment]
顺带提一下，还是有的模组作者代码非常友好，可以用资源包汉化作者自己实现的指导手册,比如better with mods。

**Comment by Water-Moon** [comment]
那个啥... Better With Mods手册真的汉化完了么

**Comment by xinyuan-liu** [comment]
> 那个啥... Better With Mods手册真的汉化完了么

据我知道的是BTM手册汉化在别处有人在维护，这个仓库里的可能不是最新的。

**Comment by TartaricAcid** [comment]
Patchouli 手册的资源包可以覆盖啊，只不过 `book.json` 的无法覆盖而已

**Comment by RUInsYi** [comment]
> Patchouli 手册的资源包可以覆盖啊，只不过 `book.json` 的无法覆盖而已

抱歉， Patchouli 手册是我搞错了。那`book.json`类的现在只能发给作者吗？

**Comment by xinyuan-liu** [comment]
> > Patchouli 手册的资源包可以覆盖啊，只不过 `book.json` 的无法覆盖而已
> 
> 抱歉， Patchouli 手册是我搞错了。那`book.json`类的现在只能发给作者吗？

book.json不支持本地化
