### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by AltairEzioConor** [CFPAOrg/Minecraft-Mod-Language-Package#523]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [X] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

汉化包是放进\.minecraft\resourcepacks文件夹里面吗？为什么我在游戏中一点加载资源包就闪退
我添加了20个mod，平常使用时很正常。
mod列表：
JEI物品管理器
拔刀剑
拔刀剑日系附属包
变形
等价交换
地幔
匠魂
动画优化
高清修复
极简血条
科技重生
重生核心
砍树
快速腐烂
暮色森林
苹果皮
生命附魔
网易小精灵
战利品袋
自动拾取

**Comment by AltairEzioConor** [comment]
其中大部分mod有自带汉化，主要是科技重生没有汉化，所以我来寻找汉化包，但是打了这个补丁之后却发生了闪退，请问这是兼容性的bug还是因为汉化冲突？

**Comment by baka-gourd** [comment]
> 其中大部分mod有自带汉化，主要是科技重生没有汉化，所以我来寻找汉化包，但是打了这个补丁之后却发生了闪退，请问这是兼容性的bug还是因为汉化冲突？

重启应该就好了，mod加载资源包大概率爆炸

**Comment by AltairEzioConor** [comment]
> > 其中大部分mod有自带汉化，主要是科技重生没有汉化，所以我来寻找汉化包，但是打了这个补丁之后却发生了闪退，请问这是兼容性的bug还是因为汉化冲突？
> 
> 重启应该就好了，mod加载资源包大概率爆炸

但是重启也没用啊，已经闪退多次

**Comment by AltairEzioConor** [comment]
> > 其中大部分mod有自带汉化，主要是科技重生没有汉化，所以我来寻找汉化包，但是打了这个补丁之后却发生了闪退，请问这是兼容性的bug还是因为汉化冲突？
> 
> 重启应该就好了，mod加载资源包大概率爆炸

我刚才重新试了一下，这次没有闪退，但是该汉化的也没有汉化出来，科技重生还是没有汉化

**Comment by TartaricAcid** [comment]
闪退没有错误报告么？错误报告在游戏主目录下的 crash-report 文件夹中，注意文件名

**Comment by tai-shang-bai-he** [comment]
你这怕不是网易的吧，网易自带反作弊，汉化包基本加不上

**Comment by Chenwe-i-lin** [comment]
emmm这也太久远了吧,并且没提出实际的解决方法和问题跟踪,关了好了...
