### ISSUE TITLE
somanyenchantments的翻译简直就是机翻

### ISSUE THREAD

**Issue by POPTHREE** [CFPAOrg/Minecraft-Mod-Language-Package#532]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
mob=暴徒
Smite=铁匠
user=用户
enchant=迷住
无法理解

**Comment by TartaricAcid** [comment]
我的错，没有复核提交者的翻译就匆忙上传到仓库中，现已做删除处理，非常抱歉
