### ISSUE TITLE
沉浸工程0.12-92版本的部分条目难以翻译

### ISSUE THREAD

**Issue by mcBegins2Snow** [CFPAOrg/Minecraft-Mod-Language-Package#551]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

沉浸工程版本：0.12-92 https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/2799143
github上的en_us.lang中有些条目项目难以翻译：[这个链接](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/resources/assets/immersiveengineering/lang/en_us.lang#L716-L736)
这些条目和左轮手枪有关，用这些带属性的左轮手枪部件制作左轮手枪会施加对应的属性。

**Comment by mcBegins2Snow** [comment]
我对其进行试翻译，如果直接提交，一旦出问题，会影响很多玩家的游戏体验：

key|英文|中文
-- | -- | --
desc.immersiveengineering.info.revolver.perk.cooldown | Firerate: %1$s%% | 射速：%1$s%%
desc.immersiveengineering.info.revolver.perk.cooldown.tier-3 | Slow %1$s | 缓慢 %1$s
desc.immersiveengineering.info.revolver.perk.cooldown.tier-2 | Stuttering %1$s | 口吃 %1$s
desc.immersiveengineering.info.revolver.perk.cooldown.tier-1 | Squeaky %1$s | 嘎吱作响 %1$s
desc.immersiveengineering.info.revolver.perk.cooldown.tier1 | Fanned %1$s | 风扇 %1$s
desc.immersiveengineering.info.revolver.perk.cooldown.tier2 | Selfrepeating %1$s | 自我重复 %1$s
desc.immersiveengineering.info.revolver.perk.cooldown.tier3 | Autococking %1$s | 自动扳机 %1$s
desc.immersiveengineering.info.revolver.perk.noise | Noise: %1$s%% | 噪音：%1$s%%
desc.immersiveengineering.info.revolver.perk.noise.tier-3 | Bellowing %1$s | 吼叫 %1$s
desc.immersiveengineering.info.revolver.perk.noise.tier-2 | Loud %1$s | 大声 %1$s
desc.immersiveengineering.info.revolver.perk.noise.tier-1 | Noisy %1$s | 吵闹 %1$s
desc.immersiveengineering.info.revolver.perk.noise.tier1 | Whisper %1$s | 低语 %1$s
desc.immersiveengineering.info.revolver.perk.noise.tier2 | Silenced %1$s | 沉默 %1$s
desc.immersiveengineering.info.revolver.perk.noise.tier3 | Muted %1$s | 静音 %1$s
desc.immersiveengineering.info.revolver.perk.luck | Luck: %1$s%% | 幸运：%1$s%%
desc.immersiveengineering.info.revolver.perk.luck.tier-3 | Tough %1$s | 倒霉 %1$s
desc.immersiveengineering.info.revolver.perk.luck.tier-2 | Unlucky %1$s | 不幸 %1$s
desc.immersiveengineering.info.revolver.perk.luck.tier-1 | Inauspicious %1$s | 不祥 %1$s
desc.immersiveengineering.info.revolver.perk.luck.tier1 | Fortunate %1$s | 吉利 %1$s
desc.immersiveengineering.info.revolver.perk.luck.tier2 | Lucky %1$s | 幸运 %1$s
desc.immersiveengineering.info.revolver.perk.luck.tier3 | Gamblers %1$s | 赌徒 %1$s

有什么需要改进的，请提出来。

**Comment by TartaricAcid** [comment]
因为没具体体验过游戏内容，所以不好下结论，但是我这边更新速度很快，所以无须担心

**Comment by Water-Moon** [comment]
emm等下
这个是对IE的那个手枪的翻译吧
如果是手枪的话有一些词有专门的意思
首先是射速的那些

desc.immersiveengineering.info.revolver.perk.cooldown.tier-2 | Stuttering %1$s 
-- | --

Shutter除了口吃的意思之外在军械方面有卡壳的意思，所以是否可以翻译为"卡壳 %1$s"?


desc.immersiveengineering.info.revolver.perk.cooldown.tier-1 | Squeaky %1$s
-- | --

如果说一把枪是嘎吱作响显然不是十分妥当？或许可以改为"生锈的 %1$s"


desc.immersiveengineering.info.revolver.perk.cooldown.tier1 | Fanned %1$s
-- | --


Fanned在枪械方面有“速射”、“连射”之意，是否可以翻译为"速射 %s$1"?


desc.immersiveengineering.info.revolver.perk.cooldown.tier2 | Selfrepeating %1$s
-- | --


Self repeating的意思是可以自动上弹的枪械，因此是否翻译为"半自动(枪机) %1$s"


desc.immersiveengineering.info.revolver.perk.cooldown.tier3 | Autococking %1$s
-- | --


Autococking有连发和自动射击的意思，因此是否翻译为“全自动(枪机) %1$s”

同理，噪音的那些似乎也不完全合适


desc.immersiveengineering.info.revolver.perk.noise.tier-3 | Bellowing %1$s
-- | --


说一个枪械是在“吼叫”显然不妥。用“震耳欲聋”这个词或许会好些？所以是否可以考虑翻译为"震耳欲聋 %1$s"？


desc.immersiveengineering.info.revolver.perk.noise.tier3 | Muted %1$s 
-- | -- 


“静音”一词通常用于生活中的“降低音量”之意，但是在军械上通常用“消音”一词。因此是否可以翻译为"消音 %1$s"?

**Comment by mcBegins2Snow** [comment]
我到时候再改，今晚8点改完。

**Comment by mcBegins2Snow** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/555/commits/be361b2622f9ac602c4e24b0331882a431d5e2cc
@Water-Moon
