### ISSUE TITLE
Craft Of The Titans 整合包汉化进度表

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#57]
- [x] adinferos
- [x] aquacreeper
- [x] avaritiaadditions
- [x] baublesstuff
- [x] betterquesting
- [x] bq_standard
- [x] creativeplus
- [x] deeznuts
- [x] dmonsters
- [x] dragonmounts
- [x] dragonrealm
- [x] enchiridion
- [x] grimoireofgaia
- [x] ichunutil
- [x] infernalmobs
- [x] inventorypets
- [x] itank
- [x] kitchensink
- [x] levels
- [x] mekfarm
- [x] mikedongles
- [x] mysticalagriculture
- [x] natural_absorption
- [x] nuclearcraft
- [x] plustic
- [x] prefab
- [x] simplyjetpacks
- [x] slug
- [x] teslacorelib
- [x] thinkbigcore
- [x] tinker_io
- [x] vc

**Comment by luckyu19** [comment]
@TartaricAcid Inventory Pets我应该更新了，是还有新的版本吗？
还是需要把其余的名字都翻译？

**Comment by TartaricAcid** [comment]
抱歉，是我忘记打钩了
