### ISSUE TITLE
All The Mods 整合包汉化补全进度表

### ISSUE THREAD

**Issue by TartaricAcid** [CFPAOrg/Minecraft-Mod-Language-Package#6]
- [ ] TAIGA
- [ ] Advanced Rocketry
- [ ] Extra Utilities 2
- [x] Armor Plus
- [x] Blood Arsenal
- [ ] Computronics
- [ ] Immersive Petroleum
- [ ] Draconic Evolution
- [ ] Nuclear Craft
- [ ] Pam's Harvest Craft
- [x] RFTools
- [x] Router Reborn
- [x] Tinker IO
- [x] Abyssal Craft
- [x] Compact Machines 2
- [ ] Extra Bit Manipulation
- [x] Mine Factory Reload
- [ ] Thermal Foundation
- [x] Simply Jetpack 2
- [x] End Metals

**Comment by TartaricAcid** [comment]
@DSLM 今天我把三个issues都写好了，接锅以前先看看是否已经被完成，避免做重复工作。

**Comment by 3TUSK** [comment]
ArmorPlus????

**Comment by TartaricAcid** [comment]
ArmorPlus咋了？！

**Comment by 3TUSK** [comment]
我前几个星期刚提交过汉化的。

**Comment by TartaricAcid** [comment]
好的，我这就去扒过来

**Comment by 3TUSK** [comment]
扒的时候记得补一下，我刚才看了一眼发现还是少了不到10行...

**Comment by TartaricAcid** [comment]
好的

**Comment by DSLM** [comment]
知道了，谢谢@TartaricAcid

**Comment by 3TUSK** [comment]
以及Correlated——注意Co1和Co2之间的差别

**Comment by subtank** [comment]
哈哈，找到以前的组织了。。。滚去汉化插件的像三位大佬致敬！

**Comment by 3TUSK** [comment]
@subtank ？？？

**Comment by subtank** [comment]
清溪

**Comment by 3TUSK** [comment]
“以前的组织”是什么鬼...

**Comment by subtank** [comment]
帮忙增加过一部分匠魂翻译么。。。后来实在太忙了潜了很久。最近去做sponge的本地化了。

**Comment by 3TUSK** [comment]
0. ...这都没有你所谓的“组织”的，只是自发的而已；
1. Sponge 的本地化？？？还是基于 Sponge 编写的插件的本地化？

**Comment by subtank** [comment]
各种插件。

**Comment by 3TUSK** [comment]
> 我还以为是 SpongeDocs.
