### ISSUE TITLE
汉化数据源

### ISSUE THREAD

**Issue by jihuayu** [CFPAOrg/Minecraft-Mod-Language-Package#613]
[仓库地址](https://github.com/jihuayu/mclang)
该仓库的主分支会每个小时更新curseforge上版本为1.12.2，下载量截止到目前大于100w的模组的en_us.json文件。
文件位置是`/mod名/modID/en_us.lang`。

不知道有没有用。

**Comment by Summpot** [comment]
这是一次弄多少下来啊

**Comment by jihuayu** [comment]
只会更新有新版本的项目，暂时拉了900多个，如果需要可以全拉下来。

**Comment by Summpot** [comment]
github action貌似会被搞?

**Comment by jihuayu** [comment]
会吗？如果不行那就把更新改为手动更新。

**Comment by Summpot** [comment]
得看github怎么来

**Comment by jihuayu** [comment]
这个算构建。\滑稽
被警告了再说吧。

**Comment by Summpot** [comment]
怎么接入这个项目啊

**Comment by jihuayu** [comment]
要么你自己clone我的仓库，然后自己处理，要么你告诉我你的需求我来写。

**Comment by Chenwe-i-lin** [comment]
...太玄了, 我还是自己写一套去

**Comment by Summpot** [comment]
玄啥啊

**Comment by Summpot** [comment]
@Chenwe-i-lin

**Comment by Chenwe-i-lin** [comment]
这个项目有毒 我开不出来, 一直卡着...

**Comment by Summpot** [comment]
你不是有梯子么

**Comment by jihuayu** [comment]
可能文件太多了

**Comment by Summpot** [comment]
我开的时候好像也蛮卡

**Comment by Summpot** [comment]
我已经在写了好像

**Comment by Chenwe-i-lin** [comment]
是的 你可以放在类似 `assets` 这样的子文件夹内

**Comment by Summpot** [comment]
就是目前日期转换有点问题

**Comment by jihuayu** [comment]
好
