### ISSUE TITLE
最新版本汉化资源包部分汉化失效

### ISSUE THREAD

**Issue by dong031001** [CFPAOrg/Minecraft-Mod-Language-Package#643]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

经查证，出现问题的主要位置有：
- 自然灵气指南书
- B.A.S.E.所有金属的Def名

**Comment by Summpot** [comment]
请问是哪里？可以贴上地址吗？

**Comment by dong031001** [comment]
未知缘由，可参考https://github.com/ET-Team/EnigTech2/issues/310

**Comment by friendlyhj** [comment]
敲了一下，有些地方落了`%s`
已在#644 中补上

**Comment by Summpot** [comment]
@dong031001 自然灵气指导书在之前就修复好了,换成最新版应该可用
