### ISSUE TITLE
和五边形材质一起卡顿

### ISSUE THREAD

**Issue by Silver47Gin** [CFPAOrg/Minecraft-Mod-Language-Package#660]
1.12.2版本的，和五边形材质x256一起的时候就会出现非常厉害的卡顿，任何一个单独使用都没问题。卡顿时cpu与gpu占用率都不高，cpu单线程性能也未到瓶颈。想问下可能由什么情况引起的

**Comment by Chenwe-i-lin** [comment]
能否提交更为详细的信息以供分析, 例如 mods列表, 是否服务器, 是否装有一些"优化"mod 等.

**Comment by Chenwe-i-lin** [comment]
Reason: 无可追问事项
