### ISSUE TITLE
Minecraft Comes Alive的汉化部分似乎在游戏中只生效了一小部分

### ISSUE THREAD

**Issue by kerocate** [CFPAOrg/Minecraft-Mod-Language-Package#665]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译
MCA的版本为：6.1.0

![最后一次debug文件中搜索相关报错无果](https://s2.ax1x.com/2020/03/05/3TQdO0.png)

最后一次debug.log文件中搜索相关报错无果

具体生效的就是村民职业标记，交谈和右键开启gui都是英文的奥 :)

**Comment by TartaricAcid** [comment]
我记得这一部分语言文件似乎是无法通过资源包加载的
