### ISSUE TITLE
对#666的补充（千年村庄）

### ISSUE THREAD

**Issue by ShimmeringLight** [CFPAOrg/Minecraft-Mod-Language-Package#674]
之前在#666打错了字，抱歉，现重新提issue
问题如图，这两个翻译
![截屏2020-03-16上午8 15 22](https://user-images.githubusercontent.com/33362058/76713959-424b3300-675f-11ea-9173-0eab2ac17220.png)

![截屏2020-03-16上午8 15 06](https://user-images.githubusercontent.com/33362058/76713964-48d9aa80-675f-11ea-9d1e-dfedb37b6995.png)

**Comment by Exildoutsider** [comment]
补图

![截屏2020-03-16上午8 15 22](https://user-images.githubusercontent.com/33362058/76713986-73c3fe80-675f-11ea-800f-808f1046949e.png)

![截屏2020-03-16上午8 15 06](https://user-images.githubusercontent.com/33362058/76713999-7fafc080-675f-11ea-9e58-abdaece23b18.png)

**Comment by Exildoutsider** [comment]
我佛，图传不上，贴一个网盘链接吧
链接: https://pan.baidu.com/s/1smaOLRikEOeZK80yZNTMxQ 提取码: hkjx 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by TUsama** [comment]
这个远古问题居然留到现在还没有修复。。。顺便其实图可以正常加载

**Comment by dovisutu** [comment]
诺曼**稿**可还行...另一个标准错误

**Comment by TUsama** [comment]
这应该是远古版本的问题，在最新版的millenaire的自带汉化以及库这边的汉化都已经全部更正了
