### ISSUE TITLE
等价交换修改物品EMC之后不再翻译

### ISSUE THREAD

**Issue by lhjda** [CFPAOrg/Minecraft-Mod-Language-Package#686]
等价交换修改物品EMC之后不再翻译

**Comment by Water-Moon** [comment]
您好，虽然在下并非CFPAOrg的成员，但是这里或许有一些可供参考的建议，以便能更快解决问题：
建议您详细描述这个错误，比如：
- 是所有物品都有这个问题还是只限于部分模组？
- 修改之后是所有翻译都失效还是只有被修改的失效？
- 您的等价交换是否安装了其他附属？是什么版本的？
同时，建议附上出现问题的物品在修改EMC前后的ToolTip截图，谢谢。

**Comment by Chenwe-i-lin** [comment]
请附上更加详细的问题说明, 以便于对问题的判断

**Comment by lhjda** [comment]
发现重启游戏后会恢复翻译 再次重启后又会不翻译 在翻译和不翻译之间有规律的循环

**Comment by lhjda** [comment]
发现重启游戏后会恢复翻译，再次重启后又会不翻译。在不翻译和翻译之间有规律的循环

**Comment by Water-Moon** [comment]
听起来更像是算法出错而不是资源包的问题
虽然不知道是什么模组导致的
