### ISSUE TITLE
两个汉化项目立项问题

### ISSUE THREAD

**Issue by ChromaPIE** [CFPAOrg/Minecraft-Mod-Language-Package#689]
- [x] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

- **NuclearCraft Overhauled**（核电工艺重置版）与**NuclearCraft**（核电工艺）的modid均为nuclearcraft，目前无汉化立项，现阶段模组内的汉化似均为官方汉化，通篇看来遗漏错误颇多，请求立项。

- 请求为**Future MC**（futuremc）立项。

**Comment by Chenwe-i-lin** [comment]
知道了

**Comment by Water-Moon** [comment]
#724 
1/2 (50%)
