### ISSUE TITLE
汉化资源包导致游戏音效加载失败

### ISSUE THREAD

**Issue by kikbi** [CFPAOrg/Minecraft-Mod-Language-Package#696]
汉化资源包和soartex_fanver4.1.0共同使用会导致偶尔游戏声音加载失败。无论怎么设置声音都没有游戏声音。有时重启游戏后还是没有声音。进入游戏资源包管理界面调整顺序或者直接点击完成，游戏重新加载资源包后，游戏声音能正常加载。单独使用soartex_fanver4.1.0材质无问题。未试过单独只用汉化资源包的情况。

**Comment by Water-Moon** [comment]
这个有可能是因为加载的数据太多导致OpenAL（MC的音效引擎）在启动的时候MemoryBuffer之类的东西flip()失败导致...
建议检查一下logs中是否有提及关于OpenAL没能正常启动的报错，或者调大内存，或者更新显卡驱动？
