### ISSUE TITLE
与Tekxit整合包中的Basic Nether Ores模组崩溃

### ISSUE THREAD

**Issue by Inkerf** [CFPAOrg/Minecraft-Mod-Language-Package#698]
- [是 ] 反馈的问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [是 ] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
Minecraft Tekxit整合包 1.12.2 0.972版本，可以再Technic启动器上下到，整合包在中国好像名气不太大（？）
安装了材质包后无法启动 崩溃报告如下 （显示是什么下界矿物模组的冲突）
删除材质包后可正常启动
不知道这个mod包不包括在资源包的翻译范畴，但是打上之后确实崩溃了。抱着试一试的心态写下了问题报告，就是告知一下吧\(^o^)/

第一次写问题报告，不知道规矩，请多包涵。

---- Minecraft Crash Report ----
// You're mean.

Time: 2020-04-13 18:20:49 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Basic Nether Ores (bno)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -4
    at java.lang.String.substring(Unknown Source)
    at cscot.basicnetherores.registries.OreDictionaryRegistry.registerDictionaryBlocks(OreDictionaryRegistry.java:36)
    at cscot.basicnetherores.util.handler.RegistryHandler.initRegistries(RegistryHandler.java:114)
    at cscot.basicnetherores.BasicNetherOres.init(BasicNetherOres.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_73, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3042523480 bytes (2901 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
  JVM Flags: 5 total; -Xms5120m -Xmx5120m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 138 mods loaded, 138 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version           | Source                                             | Signature                                |
       |:----- |:--------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft                         | 1.12.2            | minecraft.jar                                      | None                                     |
       | LCHI  | mcp                               | 9.42              | minecraft.jar                                      | None                                     |
       | LCHI  | FML                               | 8.0.99.99         | modpack.jar                                        | None                                     |
       | LCHI  | forge                             | 14.23.5.2847      | modpack.jar                                        | None                                     |
       | LCHI  | creativecoredummy                 | 1.0.0             | minecraft.jar                                      | None                                     |
       | LCHI  | ivtoolkit                         | 1.3.3-1.12        | minecraft.jar                                      | None                                     |
       | LCHI  | littletilescore                   | 1.0.0             | minecraft.jar                                      | None                                     |
       | LCHI  | micdoodlecore                     |                   | minecraft.jar                                      | None                                     |
       | LCHI  | smoothfontcore                    | mc1.12.2-2.1.1    | minecraft.jar                                      | None                                     |
       | LCHI  | xaerominimap_core                 | 1.12.2-1.0        | minecraft.jar                                      | None                                     |
       | LCHI  | openmodscore                      | 0.12.2            | minecraft.jar                                      | None                                     |
       | LCHI  | foamfixcore                       | 7.7.4             | minecraft.jar                                      | None                                     |
       | LCHI  | randompatches                     | 1.12.2-1.21.0.0   | randompatches-1.12.2-1.21.0.0.jar                  | None                                     |
       | LCHI  | smoothfont                        | mc1.12.2-2.1.1    | SmoothFont-mc1.12.2-2.1.1.jar                      | None                                     |
       | LCHI  | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHI  | jei                               | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                          | None                                     |
       | LCHI  | botania                           | r1.10-363         | Botania+r1.10-363.jar                              | None                                     |
       | LCHI  | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHI  | cofhcore                          | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
       | LCHI  | craftstudioapi                    | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHI  | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHI  | natura                            | 1.12.2-4.3.2.69   | natura-1.12.2-4.3.2.69.jar                         | None                                     |
       | LCHI  | harvestcraft                      | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
       | LCHI  | ctm                               | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
       | LCHI  | twilightforest                    | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHI  | animania                          | 1.7.3             | animania-1.12.2-1.7.3.jar                          | None                                     |
       | LCHI  | appleskin                         | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LCHI  | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHI  | attributefix                      | 1.0.10            | AttributeFix-1.12.2-1.0.10.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | quark                             | r1.6-178          | Quark-r1.6-178.jar                                 | None                                     |
       | LCHI  | autoreglib                        | 1.3-32            | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHI  | backpack                          | 3.0.2             | backpack-3.0.2-1.12.2.jar                          | None                                     |
       | LCHI  | ichunutil                         | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHI  | backtools                         | 7.0.0             | BackTools-1.12.2-7.0.0.jar                         | None                                     |
       | LCHE  | bno                               | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar                 | None                                     |
       | LCH   | battletowers                      | 1.6.5             | BattleTowers-1.12.2_1.6.5.jar                      | None                                     |
       | LCH   | bibliocraft                       | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCH   | bookshelf                         | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | bspkrscore                        | 7.6.0.1           | bspkrsCore-universal-7.6.0.1.jar                   | None                                     |
       | LCH   | buildcraftlib                     | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | buildcraftcore                    | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | buildcraftbuilders                | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | buildcrafttransport               | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | buildcraftsilicon                 | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | crafttweaker                      | 4.1.20            | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCH   | buildcraftcompat                  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | buildcraftenergy                  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | buildcraftfactory                 | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | buildcraftrobotics                | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                       | None                                     |
       | LCH   | cctweaked                         | 1.86.2            | cc-tweaked-1.12.2-1.86.2.jar                       | None                                     |
       | LCH   | computercraft                     | 1.86.2            | cc-tweaked-1.12.2-1.86.2.jar                       | None                                     |
       | LCH   | chesttransporter                  | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | LCH   | chisel                            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                       | None                                     |
       | LCH   | chococraft                        | 0.9.8.0           | chococraft_1.12.2-0.9.8.0.jar                      | None                                     |
       | LCH   | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | cofhworld                         | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | cosmeticarmorreworked             | 1.12.2-v4b        | CosmeticArmorReworked-1.12.2-v4b.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | ctgui                             | 1.0.0             | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCH   | crafttweakerjei                   | 2.0.3             | CraftTweaker2-1.12-4.1.20.jar                      | None                                     |
       | LCH   | creativecore                      | 1.10.0            | CreativeCore_v1.10.9_mc1.12.2.jar                  | None                                     |
       | LCH   | custommainmenu                    | 2.0.8             | CustomMainMenu-MC1.12.2-2.0.8.jar                  | None                                     |
       | LCH   | defaultoptions                    | 9.2.8             | DefaultOptions_1.12.2-9.2.8.jar                    | None                                     |
       | LCH   | dimdoors                          | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                     | None                                     |
       | LCH   | ding                              | 1.0.1             | Ding-1.12.1-1.0.1.jar                              | None                                     |
       | LCH   | dungeontactics                    | DT-0.16.6         | DungeonTactics-1.12.2-0.16.6.jar                   | None                                     |
       | LCH   | durabilityshow                    | 5.0.0             | Durability+Show-1.12-5.0.0.jar                     | None                                     |
       | LCH   | eplus                             | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | enchdesc                          | 1.1.15            | EnchantmentDescriptions-1.12.2-1.1.15.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | endercore                         | 1.12.2-0.5.73     | EnderCore-1.12.2-0.5.73.jar                        | None                                     |
       | LCH   | thermalfoundation                 | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | thermalexpansion                  | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | enderio                           | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderiointegrationtic             | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderiobase                       | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderioconduits                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderioconduitsappliedenergistics | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderioconduitsopencomputers      | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderioconduitsrefinedstorage     | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderiointegrationforestry        | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | LCH   | enderiointegrationticlate         | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | ftblib                            | 5.4.7.0           | FTBLib-5.4.7.0.jar                                 | None                                     |
       | LCH   | enderiomachines                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderiopowertools                 | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                          | None                                     |
       | LCH   | enderstorage                      | 2.4.6.137         | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | energyconverters                  | 1.3.6.24          | energyconverters_1.12.2-1.3.6.24.jar               | None                                     |
       | LCH   | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LCH   | featuredservers                   | 1.12-1.0.6        | FeaturedServers-1.12-1.0.6.jar                     | None                                     |
       | LCH   | foamfix                           | 0.10.10-1.12.2    | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCH   | forgelin                          | 1.8.4             | Forgelin-1.8.4.jar                                 | None                                     |
       | LCH   | forgemultipartcbe                 | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | microblockcbe                     | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
       | LCH   | minecraftmultipartcbe             | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
       | LCH   | cfm                               | 6.3.1             | furniture-6.3.1-1.12.2.jar                         | None                                     |
       | LCH   | ic2                               | 2.8.1001          | IC2Classic+1.12-1.5.4.5.jar                        | None                                     |
       | LCH   | galacticraftcore                  | 4.0.2.244         | GalacticraftCore-1.12.2-4.0.2.244.jar              | None                                     |
       | LCH   | galacticraftplanets               | 4.0.2.244         | Galacticraft-Planets-1.12.2-4.0.2.244.jar          | None                                     |
       | LCH   | helpfixer                         | 1.12.1-1.5.18     | HelpFixer-1.12.1-1.5.18.jar                        | None                                     |
       | LCH   | placebo                           | 1.5.1             | Placebo-1.12.2-1.5.1.jar                           | None                                     |
       | LCH   | hexxitgear                        | 2.8.0             | Hexxit+Gear-1.12.2-2.8.0.jar                       | None                                     |
       | LCH   | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCH   | ic2-classic-spmod                 | 0.0.0.0           | IC2Classic+1.12-1.5.4.5.jar                        | None                                     |
       | LCH   | teslacorelib                      | 1.0.17            | tesla-core-lib-1.12.2-1.0.17.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
       | LCH   | infernalmobs                      | 1.7.6             | InfernalMobs-1.12.1.jar                            | None                                     |
       | LCH   | inventorysorter                   | 1.13.3+57         | inventorysorter-1.12.2-1.13.3+57.jar               | None                                     |
       | LCH   | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCH   | jrftl                             | 1.1               | JRFTL[1.12.2]-1.1.jar                              | None                                     |
       | LCH   | laggoggles                        | FAT-1.12.2-4.9    | LagGoggles-FAT-1.12.2-4.9.jar                      | None                                     |
       | LCH   | littletiles                       | 1.5.0             | LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar          | None                                     |
       | LCH   | mcmultipart                       | 2.5.3             | MCMultiPart-2.5.3.jar                              | None                                     |
       | LCH   | recipehandler                     | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
       | LCH   | openmods                          | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCH   | openblocks                        | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCH   | quacklib                          | 2.2.5             | quacklib-2.2.5.jar                                 | None                                     |
       | LCH   | quickhomes                        | 1.2.2             | QuickHomes-1.2.2.jar                               | None                                     |
       | LCH   | quickteleports                    | 1.1.0             | quickteleports-1.1.0.jar                           | None                                     |
       | LCH   | railcraft                         | 12.0.0            | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCH   | reccomplex                        | 1.4.8.2           | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | LCH   | redstonearsenal                   | 2.6.3             | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | redwoods                          | 1.2.2             | Redwoods-1.12-1.2.2.jar                            | None                                     |
       | LCH   | reforged                          | 0.7.5             | Reforged-0.7.5-1.12+.jar                           | None                                     |
       | LCH   | xreliquary                        | 1.12.2-1.3.4.796  | Reliquary-1.12.2-1.3.4.796.jar                     | None                                     |
       | LCH   | rswires                           | 1.0               | rswires-3.0.1.jar                                  | None                                     |
       | LCH   | thermaldynamics                   | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | simplyjetpacks                    | 2.2.14.67         | SimplyJetpacks2-1.12.2-2.2.14.67.jar               | None                                     |
       | LCH   | soulshardsrespawn                 | 1.12.2-1.1.1-13   | SoulShardsRespawn-1.12.2-1.1.1-13.jar              | None                                     |
       | LCH   | torohealthmod                     | 1.12.2-11         | torohealth-1.12.2-11.jar                           | None                                     |
       | LCH   | traverse                          | 1.6.0             | Traverse-1.12.2-1.6.0-69.jar                       | None                                     |
       | LCH   | treecapitator                     | 1.43.0            | TreeCapitator-client-1.43.0.jar                    | None                                     |
       | LCH   | vanillafix                        | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCH   | wanionlib                         | 1.12.2-2.4        | WanionLib-1.12.2-2.4.jar                           | None                                     |
       | LCH   | xaerominimap                      | 20.5.2            | Xaeros_Minimap_20.5.2_Forge_1.12.jar               | None                                     |
       | LCH   | xaeroworldmap                     | 1.5.6             | XaerosWorldMap_1.5.6_Forge_1.12.jar                | None                                     |
       | LCH   | yabba                             | 1.1.2.54          | YABBA-1.1.2.54.jar                                 | None                                     |
       | LCH   | reauth                            | 3.6.0             | reauth-3.6.0.jar                                   | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCH   | teslacorelib_registries           | 1.0.17            | tesla-core-lib-1.12.2-1.0.17.jar                   | None                                     |
       | LCH   | unidict                           | 1.12.2-2.9.6      | UniDict-1.12.2-2.9.6.jar                           | None                                     |
  Loaded coremods (and transformers): CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      LoadingPlugin (Xaeros_Minimap_20.5.2_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
                                        bre.smoothfont.asm.Transformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
                                        
                                      PluginLoader (MemoryTester-0.4.2.jar)
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) Iris(TM) Pro Graphics 5200'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Basic Nether Ores (bno)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) Iris(TM) Pro Graphics 5200 GL version 4.3.0 - Build 20.19.15.4835, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Minecraft-Mod-Language-Package-2.2.85.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz

**Comment by dovisutu** [comment]
奇怪，汉化包里没有这个 mod 啊...
不过估计和汉化包还是有一定关系

**Comment by dovisutu** [comment]
破案了
```java
			OreDictionary.registerOre("block" + block.getLocalizedName().substring(0, block.getLocalizedName().length() - 6), block);
```
[这里](https://github.com/cScotPlay/BasicNetherOres/blob/e3c139ebdd76741aee04da98b1293c029da89f16/src/main/java/cscot/basicnetherores/registries/OreDictionaryRegistry.java#L36)原作者做了一件很神奇的事：直接偷懒用从本地化后的文本中去掉最后 6 个字符，然后再在前面加上`block`，一点都不考虑本地化问题

而尴尬的是用到这个方法的`key`有两个，齐刷刷的*撞key*了...
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/432c79060070d9b3dbe942f7d1694ef0e741bad2/project/assets/progressivecore/lang/zh_cn.lang#L217
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/432c79060070d9b3dbe942f7d1694ef0e741bad2/project/assets/progressivecore/lang/zh_cn.lang#L220
可以看到，这两个*（实际上所有重key的）翻译都不足 6 个字符，根本截取不了，就报错了...
这个不是我们可以解决的问题了，况且就算substring能截取出来，加入矿辞的时候中文大概率过不去→_→

**Comment by dovisutu** [comment]
已经在 cscotplay/basicnetherores#10 提交了问题

**Comment by dovisutu** [comment]
更新：原作者已经在版本1.12.2-1.0.5修复了此问题，可以尝试用该版本测试
