### ISSUE TITLE
斯巴达的武器（Spartan Weaponry）的翻译文件为空

### ISSUE THREAD

**Issue by CJYKK** [CFPAOrg/Minecraft-Mod-Language-Package#746]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：Minecraft-Mod-Language-Modpack-Snapshot-20200624153443；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

斯巴达的武器（Spartan Weaponry）这个MOD的zh_cn翻译文件的内容是空的！

![屏幕截图_743_.png](https://i.loli.net/2020/06/25/aLCmNDjlYdcve2r.png)

![屏幕截图_744_.png](https://i.loli.net/2020/06/25/awR6KqNbYX7cWim.png)

**Comment by a5161655** [comment]
呃，之前我也发现了，本来想做这个的，但是做到一半文件找不到了

**Comment by dovisutu** [comment]
似乎是在一次spider修复之后这边把所有未翻译的mod都加上了空zn_cn.lang，～用来修复weblate～，要翻译的话直接替换这个文件就好

**Comment by a5161655** [comment]
已上传汉化
