### ISSUE TITLE
核电工艺汉化缺失

### ISSUE THREAD

**Issue by pandaducks** [CFPAOrg/Minecraft-Mod-Language-Package#781]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；
核电工艺的汉化自某一快照（Snapshot-20200627070155）之后就开始缺失了，直到我目前正在使用的最新版（Snapshot-20200802083453）都没有加回来。
这是一个失误造成的缺失，还是一次有意图的删除？如果是前者希望能早日得到修正。

**Comment by dovisutu** [comment]
因为nuclearcraft出了一个重制版（nuclearcraft overhaul），结果很神奇的同样使用nuclearcraft这个mod id......为了避免两个mod打上汉化包后都冲突，目前是把它删掉了，但是好像有人在弄官中，所以理论上来说不用这个包也可以得到不错的汉化效果（？）
