### ISSUE TITLE
工业2物品名称异常

### ISSUE THREAD

**Issue by BackOnTruck** [CFPAOrg/Minecraft-Mod-Language-Package#790]
- [X] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [X] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

打开MC一段时间后聊天框中出现“[调试功能] 重载成功”, 此后工业2物品名称无法正常显示。
![image](https://user-images.githubusercontent.com/36351601/90327235-0a714180-dfc4-11ea-8b38-1bfac96a4da4.png)

刚启动MC时正常：
![image](https://user-images.githubusercontent.com/36351601/90327151-3d670580-dfc3-11ea-9015-2feb403b8b69.png)

其他模组汉化正常。

**Comment by TartaricAcid** [comment]
i18n 模组的一个 bug，下个版本修复
