### ISSUE TITLE
载入汉化资源包后，打开Roots手册后游戏会崩溃

### ISSUE THREAD

**Issue by UOYZAL** [CFPAOrg/Minecraft-Mod-Language-Package#791]
rt

**Comment by dovisutu** [comment]
能否发一下crash_report？

**Comment by UOYZAL** [comment]
https://github.com/ET-Team/EnigTech2/issues/521
https://github.com/ET-Team/EnigTech2/issues/535

**Comment by dovisutu** [comment]
如果不加汉化资源包是否崩溃？

**Comment by UOYZAL** [comment]
![IJW_87)LDZ307ZKVTB~{UUP](https://user-images.githubusercontent.com/59724679/91442296-333ae600-e8a4-11ea-9591-5a150b190514.png)
没事了，打扰了

**Comment by Fodoth-jinzi89** [comment]
初步发现确实是汉化资源包导致崩溃，因为汉化资源包适配的是最新版本（3.1+）的roots，而模组用的是老版本（3.0）。
删掉汉化资源包中特定文件夹（并禁用对应模组）后，解决了几本书打开崩溃的问题，之后是否发生崩溃还需要观察。
另：由于删除了元素土的配方，对应页面由于有link_recipe会导致加载错误。虽不至于崩溃。不知道其它物品是否有这个问题。
![image](https://user-images.githubusercontent.com/49546344/152720045-330367ce-a360-4261-9e6a-1e376f85b87f.png)
