### ISSUE TITLE
1.16 hwyla invalid JSON

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#797]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.16` 的翻译；
```
JSONDecodeError('Invalid control character at: line 33 column 62 (char 1388)')
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/03537822baa876a4c02b295dc8f9c0692951caf3/projects/1.16.1/assets/hwyla/waila/lang/en_us.json#L34-L35

**Comment by exzhawk** [comment]
https://github.com/TehNut/HWYLA/blob/1.16_forge/src/main/resources/assets/waila/lang/en_us.json#L33
源文件似乎是正常的, 这是爬虫处理的问题吗 @baka-gourd

**Comment by dovisutu** [comment]
看起来这个文件现在应该是好的了
不知道等formatter再跑一次后会不会炸掉（

**Comment by exzhawk** [comment]
好 现在就差汉化了.jpg

**Comment by baka-gourd** [comment]
> 看起来这个文件现在应该是好的了
> 不知道等formatter再跑一次后会不会炸掉（

不会有格式化都。。
