### ISSUE TITLE
爬虫白名单添加？

### ISSUE THREAD

**Issue by TUsama** [CFPAOrg/Minecraft-Mod-Language-Package#801]
- [ ] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [ ] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

目前工作流程为爬虫抓取→推送GitHub→推送wl→反推送GitHub

不使用wl的在野汉化工通过pr投放汉化+en

但是由在野汉化工投放的mod是否应该加入到爬虫爬取的列表里？这样可以较为方便的跟进新的汉化，不用再去原库那边clone然后手动替换并翻译新的条目了，很方便。

**Comment by dovisutu** [comment]
*在野*汉化如果确实在cf上白名单还是比较好做的（每次爬取时顺便把这几个一起拉了）
如果**不在cf上**准备怎么弄？

此外，需要那些放pr的去手动加白名单，还是做个action来对每个pr自动加？

**Comment by TUsama** [comment]
我建议是action加白名单，因为每次打包之后运行，扫一下CF ID，然后往白名单里面加。

不在cf上的只能自力更生了，除非研发一套爬其它网站的爬虫。

**Comment by baka-gourd** [comment]
在做了在做了

**Comment by baka-gourd** [comment]
Done.
