### ISSUE TITLE
手册上 weblate

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#802]
1. 手册能否通过资源包方式加载&覆盖
1. 手册有若干格式. 可能需要用类似 https://github.com/CFPAOrg/ModpackTransTools 的方式进行前后处理

cc @502y

**Comment by dovisutu** [comment]
手册至少patchouli式的应该是可以覆盖的（book.json除外
如果实测不能被资源包覆盖的格式，可以直接扔黑名单+公示吗？

**Comment by GreyElaina** [comment]
> 如果实测不能被资源包覆盖的格式，可以直接扔黑名单+公示吗？

那就没办法了....

**Comment by scikirbypoke** [comment]
手册放在resources/data/crossroads/patchouli_books的能不能覆盖？资源包里的文件结构应该是怎样的？
一个这么放的[例子](https://github.com/Da-Technomancer/Crossroads/tree/1.16/src/main/resources/data/crossroads/patchouli_books/manual)
