### ISSUE TITLE
1.12 defiled lands bad char

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#806]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/defiled-lands/defiledlands/lang/en_us.lang#L194
https://github.com/Lykrast/DefiledLands/blob/master/src/main/resources/assets/defiledlands/lang/en_us.lang#L194
https://github.com/Lykrast/DefiledLands/commit/eca3ee6b7e076209a545b9d6c1e6278443da0304#diff-aa1b2148d51a2eb5db4e16a4ca6f3140

**Comment by dovisutu** [comment]
刚刚看了一下，似乎原文里的那个符号也是乱码...那玩意本来是什么，怎么乱码的？

**Comment by TUsama** [comment]
![image](https://user-images.githubusercontent.com/21279092/95577491-d4e95180-0a64-11eb-8979-d93aa4699b75.png)

vsc直接无法读取

**Comment by KevinLL218** [comment]
![image](https://user-images.githubusercontent.com/43089601/121016974-58fc0080-c7cf-11eb-8872-a056b849fe89.png)

utf-8 十六进制编码是00 15，其他的我也不知道了
