### ISSUE TITLE
1.16 litematica invalid JSON

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#807]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.16/projects/1.16.1/assets/litematica/litematica/lang/zh_cn.json#L731

**Comment by exzhawk** [comment]
maybe related to https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/797
@baka-gourd

**Comment by baka-gourd** [comment]
理论上并不会操作zhcn，奇怪

**Comment by TUsama** [comment]
这些好像并不是bug。。。那些key居然可以正常被加载，没有这些key的情况下，mod中对应的文本是没有翻译的，在en_us也没有相应的key以供翻译。但是如果将这些文本复制到lang里并且将其作为key，居然可以被翻译，翻译之后在游戏中对应的文本就会变成你翻译之后的值。这就是fabric吗.jpg

**Comment by Summpot** [comment]
enus没有那不就是硬编码？难道fabric会自己把硬编码的字符串找出来asm掉？

**Comment by TUsama** [comment]
不知道，真的很奇妙。

我把我测试的这两个mod都发出来好了。。
[测试用mod，内含修改过的zh_cn.zip](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/5468352/mod.zh_cn.zip)

**Comment by 10935336** [comment]
The JSON is NOT invalid, it works well.
