### ISSUE TITLE
Mystical World 模组部分物品丢失、错误翻译

### ISSUE THREAD

**Issue by RisingInIris2017** [CFPAOrg/Minecraft-Mod-Language-Package#823]
- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2` 的翻译；

涉及到的物品包括：
-  银工具、银矿石、银块，丢失中文翻译；
-  银粉，错译为“亮灰萤石粉”；
- 纺锤，错译为“栏杆桩”。

但是问题在于，我对照检查了 [en_us.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/mystical-world/mysticalworld/lang/en_us.lang) 和 [zh_cn.lang](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/mystical-world/mysticalworld/lang/zh_cn.lang)，发现上述漏翻译、错翻译的情况均没有出现。
我起初怀疑是自动汉化更新模组自动下载了一个过期的资源包，特意下载了 [汉化资源包-Snapshot-20200927115243](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/tag/Snapshot-20200927115243) 装入游戏，发现上述错漏翻译的情况在这一版本中仍然存在。

究竟是什么导致了这个问题？
我近期在做使用了 Mystical World 模组的整合包，急需正确的汉化包。
在此先感谢各位的帮助！

**Comment by Fangshing87** [comment]
银一类问题出在[这个链接](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/wildnature/wildnature/lang/zh_cn.lang)里。
而纺锤的问题出在[这里](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/missing-pieces/missing_pieces/lang/zh_cn.lang)

**Comment by TUsama** [comment]
一般来说，翻译不对查到的是对的，均为重key问题，建议整合包内只保留自己需要的mod即可。

可以close了。
