### ISSUE TITLE
weblate特殊字符提供点啥

### ISSUE THREAD

**Issue by exzhawk** [CFPAOrg/Minecraft-Mod-Language-Package#838]
普通翻译界面输入框右上角的软键盘, 可以预置一些常用特殊字符方便插入, 比如 §(分节符号)
@dovisutu @baka-gourd @WuzgXY-GitHub 有什么建议的, 可以直接放进weblate配置中, 默认提供

**Comment by WuzgXY-GitHub** [comment]
我个人觉得没啥必要，因为输入法，比如搜狗，本身可以提供添加短语的功能，我自己是可以快速地打出一个乃至多个字符的。当然能加的话加上绝无坏处，不过由于我也许久未参与主动翻译工作了，故恐怕帮不上列举的什么忙

**Comment by 502y** [comment]
win10输入法表示需要。

**Comment by dovisutu** [comment]
分节符可以加上
