### ISSUE TITLE
使用/提交需要注意的事项

### ISSUE THREAD

**Issue by baka-gourd** [CFPAOrg/Minecraft-Mod-Language-Package#847]
- 请尽量在pr上使用label标注状态（need change，need review）。
- 没有完工的汉化仍可提交pr，但请设置为draft并打上need change（不会设的可以只打need change）
- 所有提交的翻译都是**人工完成**，由pr提供的翻译都经过**人工审核**，不是机翻。
- 1.12版本支持模组白名单/黑名单，如有需要请在config文件夹下的spider/1.12.2中的文件夹配置。
- 不要望文生义，有些看起来十分离谱的东西可能是正确的。
- 尽量做到边开游戏边翻译。
- 请确认翻译能够正常使用并按照规范格式提交。
- 善用更新、提交等词语。提交汉化文件时请一并上传英文原文。提交英文原文时请一并上传空白中文文件（1.12的文件为无内容的文件，1.16的文件为为只包含左右花括号的文件，例如 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/50b4d47d320ac9b78192e9adec19bff0a4948d57/projects/1.16.1/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/zh_cn.json ）。

**Comment by dovisutu** [comment]
（要不要加一条不要直接在自己fork上的main/1.16 commit？那样子多次投pr commit历史有可能会变得略混乱）
此外，在commit msg的第三行（正文）加上更详细的描述可以鼓励一下吧，虽说不是必要的，有些时候标题已经说明的很明确了

**Comment by baka-gourd** [comment]
任何格式有问题的都可以引用这个issue。同时查看[指南](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)

**Comment by GreyElaina** [comment]
@baka-gourd CONTRIBUTING.md 里的奇怪的 typo 已经修掉了, 麻烦不要再出这样的乌龙..
