### ISSUE TITLE
关于 Arctic Code Vault Contributor 勋章的疑问

### ISSUE THREAD

**Issue by xiaopangju** [CFPAOrg/Minecraft-Mod-Language-Package#873]
各位好。
先向各位道个歉（虽然可能不被接受），本人之前年轻气盛，英语水平不佳。在很久之前的贡献中，用名为bcjz（**非** GitHub 用户名）账户中机器翻译文本，给管理人员带来了不小的麻烦。
但我莫名有了 Arctic Code Vault Contributor 勋章，里面写着`Arctic Code Vault Contributor
bingchuanjuzi contributed code to 2 repositories in the 2020 GitHub Archive Program:

**CFPAOrg/Minecraft-Mod-Language-Package**, and **SettingDust/Minecraft-Mod-Language-Package**.

请问谁知道为什么我明明没有在GitHub上做过贡献，却显示我贡献过了的吗？
另外，郑重的说一声：“**对不起**”

**Comment by GreyElaina** [comment]
因为有贡献记录; 另: 之前的问题不必追究.

**Comment by xiaopangju** [comment]
抱歉，我想多嘴一句:可以删掉贡献吗？

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GreyElaina** [comment]
删不掉的.
