### ISSUE TITLE
星辉魔法的目录结构出错

### ISSUE THREAD

**Issue by JZYFC** [CFPAOrg/Minecraft-Mod-Language-Package#875]
最新的1.16汉化资源包星辉魔法(Astral Sorcery)的目录结构出错

(截至2020年11月21日，release为”1-16-汉化资源包-Snapshot-2020112010271605868037“)

![image](https://user-images.githubusercontent.com/22959764/99871335-6f1be800-2c14-11eb-99a8-75f335cc4c33.png)

- [x] 反馈问题之前，我确认我用的是该仓库最新版翻译：[最新版下载地址](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest)；
- [x] 我所反馈的翻译问题版本正确，是 `1.12.2/1.15/1.16` 的翻译；

**Comment by baka-gourd** [comment]
已解决。
