### ISSUE TITLE
翻译质量跟踪

### ISSUE THREAD

**Issue by baka-gourd** [CFPAOrg/Minecraft-Mod-Language-Package#878]
机翻，漏翻，质量不高的翻译可以在这里提出。

**Comment by baka-gourd** [comment]
[巫术手册](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/62f1ca7e8eb220e5a126d5ed9ecfe7a7d68e2410)

**Comment by baka-gourd** [comment]
待删除：iceandfire

**Comment by baka-gourd** [comment]
11月24日及25日凌晨的翻译有大问题。

**Comment by baka-gourd** [comment]
> 待删除：iceandfire

done

**Comment by baka-gourd** [comment]
1.16沉浸科技手册崩溃

**Comment by TUsama** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.16/projects/1.16.1/assets/azuredoom-dothack-mod/dothack/lang/en_us.json

令人疑惑的格式问题。

**Comment by baka-gourd** [comment]
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.16/projects/1.16.1/assets/azuredoom-dothack-mod/dothack/lang/en_us.json
> 
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.16/projects/1.16.1/assets/azuredoom-doom-mod/doomweapon/lang/en_us.json
> 
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.16/projects/1.16.1/assets/aquaculture/aquaculture/lang/en_us.json
> 
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.16/projects/1.16.1/assets/amb-aurums-more-blocks/amb/lang/en_us.json
> 
> 令人疑惑的格式问题。

这个个是作者的格式问题，新爬虫可以尝试解决下。

**Comment by baka-gourd** [comment]
对于翻译错误，如其它，熔岩(岩浆)需要统一修改
