### ISSUE TITLE
[Feature] 自動添加繁體中文

### ISSUE THREAD

**Issue by flier268** [CFPAOrg/Minecraft-Mod-Language-Package#886]
我寫了一個[Node.js腳本](https://gist.github.com/flier268/9cf9ca2a5b012f344d2b26bba5baaa66)，能夠自動把簡體中文轉成繁體，請問如何添加？

**Comment by baka-gourd** [comment]
這個想法很棒。但是存在很多問題。
- 正體中文与簡體中文的遣詞造句不同
- 常用翻譯不同（拉杆，控制杆）
- 語序不同
如果只將简体中文轉換成正體中文，可能會造成很多理解上的錯誤。
[繁體漢化倉庫](https://github.com/chesterccj305/Mods-zh_tw-Lang-Pack)是一個已有的，舞秋風維護的繁體中文倉庫，港澳臺友人可以試一試。

**Comment by baka-gourd** [comment]
所以，如果需要添加，必須解決以上問題。但是在現在，就連機器翻譯都不能很好的解決該問題，添加可能會引起漢化質量的下降。

**Comment by flier268** [comment]
這個問題主要在於用詞不同的關係

安德/終界使者的問題，可以在後續慢慢添加相關的轉換

我所用的套件會先把中文做分詞，然後依照詞性再去做轉換，你可以先試試看效果如何

我覺得先暫時不用改變太多，先默默地在資源包中添加繁體中文就好了，翻譯來源照舊就好了，因為至少就我來說，還不至於因為用詞不同而完全看不懂

**Comment by baka-gourd** [comment]
> 這個問題主要在於用詞不同的關係
> 
> 安德/終界使者的問題，可以在後續慢慢添加相關的轉換
> 
> 我所用的套件會先把中文做分詞，然後依照詞性再去做轉換，你可以先試試看效果如何
> 
> 我覺得先暫時不用改變太多，先默默地在資源包中添加繁體中文就好了，翻譯來源照舊就好了，因為至少就我來說，還不至於因為用詞不同而完全看不懂

高版本其實簡體也沒有做多少……

再者，就“完全看不懂”來說，如果翻譯的目的是“基本看得懂”而不是“信達雅”，那機器翻譯就差不多足夠了。

我認為對外釋出是包一定要有質量，不能像機器翻譯一樣要求他，必須考慮其他人的感受。

這個事情需要進一步的討論。

**Comment by TUsama** [comment]
能不能做一个文本替换的工作，参照译名表在打包的时候把特定的词替换为繁体的官译？

**Comment by flier268** [comment]
轉換某些詞彙這個完全可以做到

Clefal <notifications@github.com> 於 2020年12月5日 週六 10:42 寫道：

**Comment by GreyElaina** [comment]
好主意, 谁提出谁做(

**Comment by 1478599553** [comment]
繁体的语序与简体有一定出入，这个可能不是机器能完成的工作。

**Comment by Summpot** [comment]
好耶

**Comment by Summpot** [comment]
还有分词，太棒了（）

**Comment by 1478599553** [comment]
作者是不是鸽了（
没回声了

**Comment by baka-gourd** [comment]
> 轉換某些詞彙這個完全可以做到
> […](#)
> 能不能做一个文本替换的工作，参照译名表在打包的时候把特定的词替换为繁体的官译？

请问现在还需要吗

**Comment by flier268** [comment]
我覺得需要，但是有人提出反對
由軟體自動轉換很方便，我自己有用過我自己轉出來的資源包，大部分都沒問題，只有少部分用詞是台灣少用的詞，但問題不是很大，因為還是能看懂是什麼意思
有興趣的人可以自己試試看
[Minecraft-Mod-Language-Package-1-16.zip](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/5885919/Minecraft-Mod-Language-Package-1-16.zip)
這是2021/1/1做的

**Comment by baka-gourd** [comment]
> 我覺得需要，但是有人提出反對
> 由軟體自動轉換很方便，我自己有用過我自己轉出來的資源包，大部分都沒問題，只有少部分用詞是台灣少用的詞，但問題不是很大，因為還是能看懂是什麼意思
> 有興趣的人可以自己試試看
> [Minecraft-Mod-Language-Package-1-16.zip](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/5885919/Minecraft-Mod-Language-Package-1-16.zip)
> 這是2021/1/1做的

其實是這樣
我們需要一個報告（投票）之類的東西來看看別人的態度怎麼樣。
再者我們也不想應為漢化質量問題受到口誅筆伐:(
因為質量問題所以一直放著

**Comment by baka-gourd** [comment]
也沒有渠道去和繁體的使用者進行溝通，由於機翻也肯定看著不舒服:-C...
而且是舞秋風已經有一個漢化包了（雖然內容可能比較少

**Comment by baka-gourd** [comment]
> 我覺得需要，但是有人提出反對
> 由軟體自動轉換很方便，我自己有用過我自己轉出來的資源包，大部分都沒問題，只有少部分用詞是台灣少用的詞，但問題不是很大，因為還是能看懂是什麼意思
> 有興趣的人可以自己試試看
> [Minecraft-Mod-Language-Package-1-16.zip](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/5885919/Minecraft-Mod-Language-Package-1-16.zip)
> 這是2021/1/1做的

可以到玩家社區里去徵求一下意見嗎，比如irc頻道之類的😄

**Comment by baka-gourd** [comment]
https://www.rpmtw.ga/

**Comment by flier268** [comment]
我最後還是自己搞定了，有需要的朋友可以在[這邊](https://github.com/flier268/Minecraft-Mod-Traditional-Chinese-Language-Package/releases)下載，機器翻譯的，因為我沒有時間弄這些，但應該還是看得懂，簡體轉繁體就差在用詞不同而已
