### ISSUE TITLE
[翻译问题]汉化包对末影设备模组的垃圾存储单元名称翻译影响玩家对功能的理解

### ISSUE THREAD

**Issue by Gan-N** [CFPAOrg/Minecraft-Mod-Language-Package#898]
- MC版本：1.12.2
- MOD版本：1.1.0
![image](https://user-images.githubusercontent.com/35490649/102017127-f128a800-3d9f-11eb-97b5-fb61f43d95f7.png)
该物品是用来存储一些元数据/NBT标签相同，但是在物品栏或一般存储设备中无法堆叠的物品的。翻译为垃圾存储单元影像玩家对该物品的理解。
官方翻译为杂物箱。

**Comment by GreyElaina** [comment]
Suggest Translate: `杂物储存单元`

**Comment by ChromaPIE** [comment]
须知：在初版会以原文为标准进行翻译 原文为Junk 所以**官方名称有歧义在先** 并非**翻译**影响玩家理解
