### ISSUE TITLE
1.16.4无法加载资源包

### ISSUE THREAD

**Issue by rainsillwood** [CFPAOrg/Minecraft-Mod-Language-Package#906]
1.16.4无法加载资源包，显示版本不兼容，将pack.mcmeta内的pack_format改为6可解决

**Comment by 1478599553** [comment]
可能是偶然问题，请尝试稳定复现这个问题并详细说明（其他人没有这个问题）

**Comment by rainsillwood** [comment]
游戏版本：1.16.4
MCP版本：20201102.104115
Froge版本：35.1.13
只装了Forge和i18，稳定复现

**Comment by dovisutu** [comment]
在加载资源包界面显示`（不兼容）`是正常的，如果试图加载时在警告界面确认后出现了问题才是真正的问题
请自己检查一下，如果真的出了问题（比如无汉化，乱码等）在这里放上来，~我估计得再去修一遍了（~
