### ISSUE TITLE
翻译后的工程师手册开启时崩溃

### ISSUE THREAD

**Issue by morilk** [CFPAOrg/Minecraft-Mod-Language-Package#921]
我的世界版本：1.15.2
沉浸工程（IE）版本：125
在装载有i18自动汉化模组的情况下打开工程师手册会造成客户端崩溃，该BUG实测对服务器没有影响。
其次想请问一下1.15.2的汉化是否有打包文件，通过修改文本语言汉化mod不适用自动汉化模组也是一个有效的办法虽然很繁琐但是很有用。

**Comment by dovisutu** [comment]
> java.lang.RuntimeException: 4 manual entries failed to load, **see log for details**!

所以，请把崩溃那次的日志一起传上来

**Comment by Fr0zenSpirits** [comment]
here is the log，但是这不是那次的，那次的我都删了好像，这个是我重新弄的
https://paste.ubuntu.com/p/9xjxnqgMWQ/

**Comment by TUsama** [comment]
理论上现在没问题了？
还有1.15.2的其实是不维护了的。
