### ISSUE TITLE
[1.12.2]Hello World🐍

### ISSUE THREAD

**Issue by botax-issue** [CFPAOrg/Minecraft-Mod-Language-Package#971]
## 反馈模组

i18n update mod

## 问题描述

Hello, world!

## 游戏版本

1.12.2

***

Sender Platform: QQ

Sender ID: 263612114049691

**Comment by botax-issue** [comment]
114514
![pic](https://i.loli.net/2021/02/11/uiSC2KP3rfonZVy.gif)
***
`Sender Platform: QQ`
`Sender ID: 13263604969131263604969113`

**Comment by botax-issue** [comment]
emmmmmm
***
`Sender Platform: QQ`
`Sender ID: 13140511640431140511640413`

**Comment by Summpot** [comment]
艹

**Comment by botax-issue** [comment]
1145141919810
![pic](https://i.loli.net/2021/02/12/yf8rCh1otVN3giD.gif)
***
`Sender Platform: QQ`
`Sender ID: 13263604969131263604969113`

**Comment by botax-issue** [comment]
dodofasodofa
***
`Sender Platform: QQ`
`Sender ID: 13263604969131263604969113`
